{
  "formatVersion": "1.1",
  "component": {
    "group": "org.grails",
    "module": "grails-web-sitemesh",
    "version": "6.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.codehaus.groovy",
          "module": "groovy",
          "version": {
            "requires": "3.0.11"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "javax.servlet",
          "module": "javax.servlet-api",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "org.grails",
          "module": "grails-web-common",
          "version": {
            "requires": "6.1.1"
          }
        },
        {
          "group": "opensymphony",
          "module": "sitemesh",
          "version": {
            "requires": "2.4.4"
          }
        }
      ],
      "files": [
        {
          "name": "grails-web-sitemesh-6.1.3.jar",
          "url": "grails-web-sitemesh-6.1.3.jar",
          "size": 43541,
          "sha512": "fbb844ae07b28198d3f9a850be54ab120d28753db22448eb307c307f212ab19b6f570710a4796774db857de2514b6da92cc4d94fbe7d76a37740e6c2a13cf04e",
          "sha256": "39fc4a3a2a140760e64cd5278b6a995b81c616d0e37339d5eacf239a74fa6d06",
          "sha1": "cbd23242f07048fe182d7e40fee501321d87da24",
          "md5": "efd591796c1ce5ae9f69c98981ef65f4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.codehaus.groovy",
          "module": "groovy",
          "version": {
            "requires": "3.0.11"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "javax.servlet",
          "module": "javax.servlet-api",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "org.grails",
          "module": "grails-web-common",
          "version": {
            "requires": "6.1.1"
          }
        },
        {
          "group": "opensymphony",
          "module": "sitemesh",
          "version": {
            "requires": "2.4.4"
          }
        }
      ],
      "files": [
        {
          "name": "grails-web-sitemesh-6.1.3.jar",
          "url": "grails-web-sitemesh-6.1.3.jar",
          "size": 43541,
          "sha512": "fbb844ae07b28198d3f9a850be54ab120d28753db22448eb307c307f212ab19b6f570710a4796774db857de2514b6da92cc4d94fbe7d76a37740e6c2a13cf04e",
          "sha256": "39fc4a3a2a140760e64cd5278b6a995b81c616d0e37339d5eacf239a74fa6d06",
          "sha1": "cbd23242f07048fe182d7e40fee501321d87da24",
          "md5": "efd591796c1ce5ae9f69c98981ef65f4"
        }
      ]
    }
  ]
}
