{
  "formatVersion": "1.1",
  "component": {
    "group": "org.grails",
    "module": "grails-gradle-plugin",
    "version": "6.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.gradle-nexus",
          "module": "publish-plugin",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.bmuschko",
          "module": "gradle-nexus-plugin",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "org.grails",
          "module": "grails-gradle-model",
          "version": {
            "requires": "6.0.0"
          }
        },
        {
          "group": "org.grails",
          "module": "grails-shell",
          "version": {
            "requires": "6.0.0"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-bootstrap",
          "version": {
            "requires": "6.0.0"
          },
          "excludes": [
            {
              "group": "org.apache.ant",
              "module": "ant-junit"
            },
            {
              "group": "org.fusesource.jansi",
              "module": "jansi"
            },
            {
              "group": "org.apache.ivy",
              "module": "ivy"
            },
            {
              "group": "org.apache.ant",
              "module": "ant-trax"
            },
            {
              "group": "org.codehaus.groovy",
              "module": "groovy-ant"
            },
            {
              "group": "org.apache.ant",
              "module": "ant"
            },
            {
              "group": "net.java.dev.jna",
              "module": "jna"
            },
            {
              "group": "org.apache.ant",
              "module": "ant-launcher"
            },
            {
              "group": "org.codehaus.gant",
              "module": "gant_groovy1.8"
            },
            {
              "group": "jline",
              "module": "jline"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-gradle-plugin",
          "version": {
            "requires": "2.7.12"
          }
        },
        {
          "group": "io.spring.gradle",
          "module": "dependency-management-plugin",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "com.netflix.nebula",
          "module": "gradle-extra-configurations-plugin",
          "version": {
            "requires": "7.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "grails-gradle-plugin-6.0.0.jar",
          "url": "grails-gradle-plugin-6.0.0.jar",
          "size": 382867,
          "sha512": "37feed3d3f40794debd7cee44a79d142f51f6456d9482266189061ee4872803952f15aa71880cdd041e44e9def0b9197b89cb38fa2c5f9abddaaaa2901a5924d",
          "sha256": "2563da67d4fc8ad0ee2a935a99978f18ff7f9a5cc2dfcb29ba474903ad5e021a",
          "sha1": "8cca982bc0506c28b12daf13efe2d827a90626b0",
          "md5": "4b1ea2fdcb5edbc1e35cc6c7ef42565a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.gradle-nexus",
          "module": "publish-plugin",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.bmuschko",
          "module": "gradle-nexus-plugin",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "org.grails",
          "module": "grails-gradle-model",
          "version": {
            "requires": "6.0.0"
          }
        },
        {
          "group": "org.grails",
          "module": "grails-shell",
          "version": {
            "requires": "6.0.0"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-bootstrap",
          "version": {
            "requires": "6.0.0"
          },
          "excludes": [
            {
              "group": "org.apache.ant",
              "module": "ant-junit"
            },
            {
              "group": "org.fusesource.jansi",
              "module": "jansi"
            },
            {
              "group": "org.apache.ivy",
              "module": "ivy"
            },
            {
              "group": "org.apache.ant",
              "module": "ant-trax"
            },
            {
              "group": "org.codehaus.groovy",
              "module": "groovy-ant"
            },
            {
              "group": "org.apache.ant",
              "module": "ant"
            },
            {
              "group": "net.java.dev.jna",
              "module": "jna"
            },
            {
              "group": "org.apache.ant",
              "module": "ant-launcher"
            },
            {
              "group": "org.codehaus.gant",
              "module": "gant_groovy1.8"
            },
            {
              "group": "jline",
              "module": "jline"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-gradle-plugin",
          "version": {
            "requires": "2.7.12"
          }
        },
        {
          "group": "io.spring.gradle",
          "module": "dependency-management-plugin",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "com.netflix.nebula",
          "module": "gradle-extra-configurations-plugin",
          "version": {
            "requires": "7.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "grails-gradle-plugin-6.0.0.jar",
          "url": "grails-gradle-plugin-6.0.0.jar",
          "size": 382867,
          "sha512": "37feed3d3f40794debd7cee44a79d142f51f6456d9482266189061ee4872803952f15aa71880cdd041e44e9def0b9197b89cb38fa2c5f9abddaaaa2901a5924d",
          "sha256": "2563da67d4fc8ad0ee2a935a99978f18ff7f9a5cc2dfcb29ba474903ad5e021a",
          "sha1": "8cca982bc0506c28b12daf13efe2d827a90626b0",
          "md5": "4b1ea2fdcb5edbc1e35cc6c7ef42565a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "grails-gradle-plugin-6.0.0-javadoc.jar",
          "url": "grails-gradle-plugin-6.0.0-javadoc.jar",
          "size": 261,
          "sha512": "0ff3830c1ffc959a1824fa75cc0d3d3fc914d7b653aa90a70b2ae201cf45d096f674ffa5c6b5bd65621b708deda5df9637973cbb06d69222b9933a3dcac88328",
          "sha256": "4fb0b83ad4a4ec517aa5ab6af3919f6b28257a89cad74a24c7c3b7c8bd89bf4e",
          "sha1": "35980caf6fdbf3b305ee14f81f88c705fff3aad9",
          "md5": "df8fbd6891face14159f0496dc2e50fa"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "grails-gradle-plugin-6.0.0-sources.jar",
          "url": "grails-gradle-plugin-6.0.0-sources.jar",
          "size": 45628,
          "sha512": "aa6f983b289f9f569352c3e07113cb8500dd577397deaace026a2703ec0645e8b80990ff67cac40d2e86d0f0bab0efb83bea5940f493bc0ac9cf09fd907c3c3e",
          "sha256": "fd59d17a7fb6ad5f8625a30e7853add341d1e3619abe3c9baeaccf2b26cb51f2",
          "sha1": "cbe3756c808d2fe46507406356fc73364d3b1778",
          "md5": "5ee7d30345af5f057e1b41249350dba4"
        }
      ]
    }
  ]
}
