{
  "formatVersion": "1.1",
  "component": {
    "group": "org.grails",
    "module": "grails-spring",
    "version": "6.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.codehaus.groovy",
          "module": "groovy",
          "version": {
            "requires": "3.0.11"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            },
            {
              "group": "*",
              "module": "commons-cli"
            },
            {
              "group": "*",
              "module": "ant"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "jcl-over-slf4j",
          "version": {
            "requires": "1.7.36"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-tx",
          "version": {
            "requires": "5.3.27"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "5.3.27"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "5.3.27"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-bootstrap",
          "version": {
            "requires": "6.0.0"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            },
            {
              "group": "org.apache.ant",
              "module": "ant-junit"
            },
            {
              "group": "org.fusesource.jansi",
              "module": "jansi"
            },
            {
              "group": "org.apache.ivy",
              "module": "ivy"
            },
            {
              "group": "org.apache.ant",
              "module": "ant-trax"
            },
            {
              "group": "org.apache.ant",
              "module": "ant"
            },
            {
              "group": "net.java.dev.jna",
              "module": "jna"
            },
            {
              "group": "org.apache.ant",
              "module": "ant-launcher"
            },
            {
              "group": "org.codehaus.gant",
              "module": "gant_groovy1.8"
            },
            {
              "group": "jline",
              "module": "jline"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "grails-spring-6.0.0.jar",
          "url": "grails-spring-6.0.0.jar",
          "size": 39825,
          "sha512": "a97f72d89167942e43c419100e8b16f9dc0f4a052d87f942713280acfb7ea7d49afcc733fc663d8fef2b64676ad1ad6c67ad088d67445c9e79ee9454b8ce49d3",
          "sha256": "0b43aa36179bdf9d418093a9c8f9cce1f85b1abb475376d4bf68add95c3dccfc",
          "sha1": "369c0b41f2664c380dc4fb358bd88fb5dd8261a2",
          "md5": "70342e1ad0fcf71e0a4c40de0946e137"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.codehaus.groovy",
          "module": "groovy",
          "version": {
            "requires": "3.0.11"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            },
            {
              "group": "*",
              "module": "commons-cli"
            },
            {
              "group": "*",
              "module": "ant"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "jcl-over-slf4j",
          "version": {
            "requires": "1.7.36"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-tx",
          "version": {
            "requires": "5.3.27"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "5.3.27"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "5.3.27"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-bootstrap",
          "version": {
            "requires": "6.0.0"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            },
            {
              "group": "org.apache.ant",
              "module": "ant-junit"
            },
            {
              "group": "org.fusesource.jansi",
              "module": "jansi"
            },
            {
              "group": "org.apache.ivy",
              "module": "ivy"
            },
            {
              "group": "org.apache.ant",
              "module": "ant-trax"
            },
            {
              "group": "org.apache.ant",
              "module": "ant"
            },
            {
              "group": "net.java.dev.jna",
              "module": "jna"
            },
            {
              "group": "org.apache.ant",
              "module": "ant-launcher"
            },
            {
              "group": "org.codehaus.gant",
              "module": "gant_groovy1.8"
            },
            {
              "group": "jline",
              "module": "jline"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "grails-spring-6.0.0.jar",
          "url": "grails-spring-6.0.0.jar",
          "size": 39825,
          "sha512": "a97f72d89167942e43c419100e8b16f9dc0f4a052d87f942713280acfb7ea7d49afcc733fc663d8fef2b64676ad1ad6c67ad088d67445c9e79ee9454b8ce49d3",
          "sha256": "0b43aa36179bdf9d418093a9c8f9cce1f85b1abb475376d4bf68add95c3dccfc",
          "sha1": "369c0b41f2664c380dc4fb358bd88fb5dd8261a2",
          "md5": "70342e1ad0fcf71e0a4c40de0946e137"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "grails-spring-6.0.0-javadoc.jar",
          "url": "grails-spring-6.0.0-javadoc.jar",
          "size": 360387,
          "sha512": "624da1c7dcaeb449357b785109b440cfb3b50916b75f4bc6bcc5e168025fc2b667a25b8c2a417fd1ae5f05d91830f18e7b8e9c3d19ee9bc46ceb66a9a6443a4a",
          "sha256": "21bcb2a69beac1ffc75fb38a5d7efcb4b951b94ed83f159a9c6e5b407703663b",
          "sha1": "ade4c401a7447633dc3f4be54fafd2af18a119f0",
          "md5": "54320cc2b85355da939c399ce254335b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "grails-spring-6.0.0-sources.jar",
          "url": "grails-spring-6.0.0-sources.jar",
          "size": 23475,
          "sha512": "30c937abf0db7242be31cb3d7717bfbc8401b518d9308727b84910f97a7c320c9c18d6d7ba62ac8e4d097add3a3c20f41c812b8bd9952d511e93afb0b81eecf7",
          "sha256": "dfd88e88a6a201ff0a7ffbad592b69c2a03ac482640dc8c88012a1d46b548f3e",
          "sha1": "2f1da691df6b00a025812f9033a3ea6cfe3eb320",
          "md5": "07688ae2546247bee0273e5be53f7b94"
        }
      ]
    }
  ]
}
