{
  "formatVersion": "1.1",
  "component": {
    "group": "org.grails",
    "module": "grails-plugin-datasource",
    "version": "6.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "javax.servlet",
          "module": "javax.servlet-api",
          "version": {
            "requires": "4.0.1"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-test",
          "version": {
            "requires": "5.3.27"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy",
          "version": {
            "requires": "3.0.11"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            },
            {
              "group": "*",
              "module": "commons-cli"
            },
            {
              "group": "*",
              "module": "ant"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "jcl-over-slf4j",
          "version": {
            "requires": "1.7.36"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-jdbc",
          "version": {
            "requires": "5.3.27"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy-sql",
          "version": {
            "requires": "3.0.11"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "5.3.27"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-datastore-gorm",
          "version": {
            "requires": "8.0.0"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-datastore-core",
          "version": {
            "requires": "8.0.0"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-core",
          "version": {
            "requires": "6.0.0"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "grails-plugin-datasource-6.0.0.jar",
          "url": "grails-plugin-datasource-6.0.0.jar",
          "size": 24765,
          "sha512": "56c7c38a8c705d77fc15c4b682955f8c1d85f58b73dc93fbc71d0fe8dd830e5180a6ea3321d856a894000c208db12f5c672794b25951ed605dc1dd2ddd3f5c9d",
          "sha256": "8770f714f920cb9543c7001d2369133c9fb28c6b6af0f4dc2a9ce4145b9b335b",
          "sha1": "f7538906abed1d68b30f25cc84304fc5d7972ed5",
          "md5": "37bb6ccf886cfd94869024bd7e12bf43"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "javax.servlet",
          "module": "javax.servlet-api",
          "version": {
            "requires": "4.0.1"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-test",
          "version": {
            "requires": "5.3.27"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy",
          "version": {
            "requires": "3.0.11"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            },
            {
              "group": "*",
              "module": "commons-cli"
            },
            {
              "group": "*",
              "module": "ant"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "jcl-over-slf4j",
          "version": {
            "requires": "1.7.36"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-jdbc",
          "version": {
            "requires": "5.3.27"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy-sql",
          "version": {
            "requires": "3.0.11"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "5.3.27"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-datastore-gorm",
          "version": {
            "requires": "8.0.0"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-datastore-core",
          "version": {
            "requires": "8.0.0"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-core",
          "version": {
            "requires": "6.0.0"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "grails-plugin-datasource-6.0.0.jar",
          "url": "grails-plugin-datasource-6.0.0.jar",
          "size": 24765,
          "sha512": "56c7c38a8c705d77fc15c4b682955f8c1d85f58b73dc93fbc71d0fe8dd830e5180a6ea3321d856a894000c208db12f5c672794b25951ed605dc1dd2ddd3f5c9d",
          "sha256": "8770f714f920cb9543c7001d2369133c9fb28c6b6af0f4dc2a9ce4145b9b335b",
          "sha1": "f7538906abed1d68b30f25cc84304fc5d7972ed5",
          "md5": "37bb6ccf886cfd94869024bd7e12bf43"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "grails-plugin-datasource-6.0.0-javadoc.jar",
          "url": "grails-plugin-datasource-6.0.0-javadoc.jar",
          "size": 307340,
          "sha512": "33057b35aef2dc70877813c1f8b0a2a5bf80f4c72f1b96a388a2fc33f04438a99ad2fcf815b2dceb8d1daf969694ee45b8215b74c86a35af4a150d8b8d737c07",
          "sha256": "07708c550faefe8d5f99e8d8b082814f3816f4aa7f277c8bbd5625292c70ae98",
          "sha1": "31de30bbc6c647f8c0e5e08b311a7c1f7f064d44",
          "md5": "858b989a5a821db8ece84696a4bcb6d1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "grails-plugin-datasource-6.0.0-sources.jar",
          "url": "grails-plugin-datasource-6.0.0-sources.jar",
          "size": 8303,
          "sha512": "88b4f2e19167f339bdc8f136d570e5896d699bb98daab01018e1ff5e06c358dbb4553d20da69d14b5620d84ee5dcaeb8bc3cb09cb4a7c1f04acf5472b249b4e3",
          "sha256": "a83a0bc00af03fe1e60e004074b6a1292730d6bb65e87b3b27b4900da55b81e4",
          "sha1": "811a5746abe52780db519b5fa94c60bc09246be5",
          "md5": "c9a273f8e78b299ea30aed113ded3a77"
        }
      ]
    }
  ]
}
