{
  "formatVersion": "1.1",
  "component": {
    "group": "org.grails",
    "module": "grails-plugin-services",
    "version": "6.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "javax.servlet",
          "module": "javax.servlet-api",
          "version": {
            "requires": "4.0.1"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-test",
          "version": {
            "requires": "5.3.27"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy",
          "version": {
            "requires": "3.0.11"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            },
            {
              "group": "*",
              "module": "commons-cli"
            },
            {
              "group": "*",
              "module": "ant"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "jcl-over-slf4j",
          "version": {
            "requires": "1.7.36"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-tx",
          "version": {
            "requires": "5.3.27"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-core",
          "version": {
            "requires": "6.0.0"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-plugin-datasource",
          "version": {
            "requires": "6.0.0"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "grails-plugin-services-6.0.0.jar",
          "url": "grails-plugin-services-6.0.0.jar",
          "size": 17678,
          "sha512": "704963f8140f92e094b6311573e35469f47d7e072ef18eb4ba465df0a58184b7e0d6156ab7e359c80fc0ad18c2e959f3ea4e87b45b4105aeee52f9c24cfe7f37",
          "sha256": "c20e9d08732814223e396bacf39c25cd1563be8177af5d5c1a7173733ece11c3",
          "sha1": "c12e21f64c6b1344ccff02eb283edd92307030ee",
          "md5": "33df31799aef84605640f8eee8b40066"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "javax.servlet",
          "module": "javax.servlet-api",
          "version": {
            "requires": "4.0.1"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-test",
          "version": {
            "requires": "5.3.27"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy",
          "version": {
            "requires": "3.0.11"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            },
            {
              "group": "*",
              "module": "commons-cli"
            },
            {
              "group": "*",
              "module": "ant"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "jcl-over-slf4j",
          "version": {
            "requires": "1.7.36"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-tx",
          "version": {
            "requires": "5.3.27"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-core",
          "version": {
            "requires": "6.0.0"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-plugin-datasource",
          "version": {
            "requires": "6.0.0"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "grails-plugin-services-6.0.0.jar",
          "url": "grails-plugin-services-6.0.0.jar",
          "size": 17678,
          "sha512": "704963f8140f92e094b6311573e35469f47d7e072ef18eb4ba465df0a58184b7e0d6156ab7e359c80fc0ad18c2e959f3ea4e87b45b4105aeee52f9c24cfe7f37",
          "sha256": "c20e9d08732814223e396bacf39c25cd1563be8177af5d5c1a7173733ece11c3",
          "sha1": "c12e21f64c6b1344ccff02eb283edd92307030ee",
          "md5": "33df31799aef84605640f8eee8b40066"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "grails-plugin-services-6.0.0-javadoc.jar",
          "url": "grails-plugin-services-6.0.0-javadoc.jar",
          "size": 261,
          "sha512": "268df5d1b89483ffbd32a765804db11357aae2a836d632f25bdcc15e836de292e15d9a7fbf882d63ec0120ed47c662f8c21dbfbf28ee388077b03625aca130ed",
          "sha256": "0a9c254f0381f3e3f7897c8ad6d77fe5b6167022cae5ace5db66d15f25c99d8a",
          "sha1": "0eb009dea0109f20b6fce33c445104468324a8b8",
          "md5": "ed83a66281e5227fa5aca83c68bcd24d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "grails-plugin-services-6.0.0-sources.jar",
          "url": "grails-plugin-services-6.0.0-sources.jar",
          "size": 4280,
          "sha512": "d5308e5b82c2c8104fe8e034ef0aa49393eb56fafaf4b2a5c62b00ed7bd129e6196311e75ab3bd0df8b0a2c6e2440246c7127d6e22dc8ee8ff5b273d239cea7f",
          "sha256": "018ffef85afba6b36ee963d16795e5a992a53d0fe5b4ff3077f8c3e5028e8b31",
          "sha1": "5ff1dbe3d3ea086247b23784d7fa0d4e81d5bba7",
          "md5": "a9ed3353015e7c460230c280f741fcb7"
        }
      ]
    }
  ]
}
