{
  "formatVersion": "1.1",
  "component": {
    "group": "io.micronaut.security",
    "module": "micronaut-security-bom",
    "version": "3.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "java-api"
      },
      "dependencyConstraints": [
        {
          "group": "com.nimbusds",
          "module": "nimbus-jose-jwt",
          "version": {
            "requires": "9.25.6"
          }
        },
        {
          "group": "io.micronaut.security",
          "module": "micronaut-security",
          "version": {
            "requires": "3.9.0"
          }
        },
        {
          "group": "io.micronaut.security",
          "module": "micronaut-security-annotations",
          "version": {
            "requires": "3.9.0"
          }
        },
        {
          "group": "io.micronaut.security",
          "module": "micronaut-security-aot",
          "version": {
            "requires": "3.9.0"
          }
        },
        {
          "group": "io.micronaut.security",
          "module": "micronaut-security-jwt",
          "version": {
            "requires": "3.9.0"
          }
        },
        {
          "group": "io.micronaut.security",
          "module": "micronaut-security-ldap",
          "version": {
            "requires": "3.9.0"
          }
        },
        {
          "group": "io.micronaut.security",
          "module": "micronaut-security-oauth2",
          "version": {
            "requires": "3.9.0"
          }
        },
        {
          "group": "io.micronaut.security",
          "module": "micronaut-security-session",
          "version": {
            "requires": "3.9.0"
          }
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "com.nimbusds",
          "module": "nimbus-jose-jwt",
          "version": {
            "requires": "9.25.6"
          }
        },
        {
          "group": "io.micronaut.security",
          "module": "micronaut-security",
          "version": {
            "requires": "3.9.0"
          }
        },
        {
          "group": "io.micronaut.security",
          "module": "micronaut-security-annotations",
          "version": {
            "requires": "3.9.0"
          }
        },
        {
          "group": "io.micronaut.security",
          "module": "micronaut-security-aot",
          "version": {
            "requires": "3.9.0"
          }
        },
        {
          "group": "io.micronaut.security",
          "module": "micronaut-security-jwt",
          "version": {
            "requires": "3.9.0"
          }
        },
        {
          "group": "io.micronaut.security",
          "module": "micronaut-security-ldap",
          "version": {
            "requires": "3.9.0"
          }
        },
        {
          "group": "io.micronaut.security",
          "module": "micronaut-security-oauth2",
          "version": {
            "requires": "3.9.0"
          }
        },
        {
          "group": "io.micronaut.security",
          "module": "micronaut-security-session",
          "version": {
            "requires": "3.9.0"
          }
        }
      ]
    },
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "micronaut-security-bom-3.9.0.toml",
          "url": "micronaut-security-bom-3.9.0.toml",
          "size": 1361,
          "sha512": "06b3c8743401cb4d8a43f598af65992ced01e1f4501c5115d0b2fb824dc742db1d26dcfe343cea6b4bfce4ead308558f92ce10ce005776ebcf07c9c105a95105",
          "sha256": "438525bb3994372dd93f88fe5b76faff63cae468f9e50c515ab13c7c51b88482",
          "sha1": "533233d9c3b34277d6dcd774d7cc4a039df1d794",
          "md5": "7976c60a583a0fd4d1e002102dd83b44"
        }
      ]
    }
  ]
}
