{
  "formatVersion": "1.1",
  "component": {
    "group": "org.grails.plugins",
    "module": "database-migration",
    "version": "4.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.liquibase",
          "module": "liquibase-core",
          "version": {
            "requires": "4.19.0"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "org.liquibase.ext",
          "module": "liquibase-hibernate5",
          "version": {
            "requires": "4.19.0"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            },
            {
              "group": "org.hibernate",
              "module": "hibernate-core"
            },
            {
              "group": "org.hibernate",
              "module": "hibernate-entitymanager"
            },
            {
              "group": "org.liquibase",
              "module": "liquibase-core"
            },
            {
              "group": "org.hibernate",
              "module": "hibernate-envers"
            },
            {
              "group": "com.h2database",
              "module": "h2"
            },
            {
              "group": "org.liquibase",
              "module": "liquibase-test-harness"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-shell",
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "database-migration-4.2.0-plain.jar",
          "url": "database-migration-4.2.0-plain.jar",
          "size": 413986,
          "sha512": "8190df6a2282fc4afb33508657ca1096d4cda0233beb5c66050dff55ac1c0651ed39116b2c8d9fe8ba40e8572a2b0ad8e75d6159e805140ceb89f389cc7901b5",
          "sha256": "190d3880038ba497fff7e36e95b5d2d50c8d7ccc2d827d032abed31d8b2c9168",
          "sha1": "bd6abf4576a1c63a7bca056438ff6e7c1d81d69b",
          "md5": "d96eb1f4453d43d136b4d85169955154"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.liquibase",
          "module": "liquibase-core",
          "version": {
            "requires": "4.19.0"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "org.liquibase.ext",
          "module": "liquibase-hibernate5",
          "version": {
            "requires": "4.19.0"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            },
            {
              "group": "org.hibernate",
              "module": "hibernate-core"
            },
            {
              "group": "org.hibernate",
              "module": "hibernate-entitymanager"
            },
            {
              "group": "org.liquibase",
              "module": "liquibase-core"
            },
            {
              "group": "org.hibernate",
              "module": "hibernate-envers"
            },
            {
              "group": "com.h2database",
              "module": "h2"
            },
            {
              "group": "org.liquibase",
              "module": "liquibase-test-harness"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-shell",
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "database-migration-4.2.0-plain.jar",
          "url": "database-migration-4.2.0-plain.jar",
          "size": 413986,
          "sha512": "8190df6a2282fc4afb33508657ca1096d4cda0233beb5c66050dff55ac1c0651ed39116b2c8d9fe8ba40e8572a2b0ad8e75d6159e805140ceb89f389cc7901b5",
          "sha256": "190d3880038ba497fff7e36e95b5d2d50c8d7ccc2d827d032abed31d8b2c9168",
          "sha1": "bd6abf4576a1c63a7bca056438ff6e7c1d81d69b",
          "md5": "d96eb1f4453d43d136b4d85169955154"
        }
      ]
    }
  ]
}
