{
  "formatVersion": "1.1",
  "component": {
    "group": "io.opentelemetry",
    "module": "opentelemetry-bom-alpha",
    "version": "1.19.0-alpha",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-bom",
          "version": {
            "requires": "1.19.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "dependencyConstraints": [
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-opencensus-shim",
          "version": {
            "requires": "1.19.0-alpha"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-opentracing-shim",
          "version": {
            "requires": "1.19.0-alpha"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-semconv",
          "version": {
            "requires": "1.19.0-alpha"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-api-logs",
          "version": {
            "requires": "1.19.0-alpha"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-exporter-prometheus",
          "version": {
            "requires": "1.19.0-alpha"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-extension-incubator",
          "version": {
            "requires": "1.19.0-alpha"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-sdk-logs",
          "version": {
            "requires": "1.19.0-alpha"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-sdk-logs-testing",
          "version": {
            "requires": "1.19.0-alpha"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-sdk-extension-autoconfigure",
          "version": {
            "requires": "1.19.0-alpha"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-sdk-extension-incubator",
          "version": {
            "requires": "1.19.0-alpha"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-exporter-otlp-logs",
          "version": {
            "requires": "1.19.0-alpha"
          }
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-bom",
          "version": {
            "requires": "1.19.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "dependencyConstraints": [
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-opencensus-shim",
          "version": {
            "requires": "1.19.0-alpha"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-opentracing-shim",
          "version": {
            "requires": "1.19.0-alpha"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-semconv",
          "version": {
            "requires": "1.19.0-alpha"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-api-logs",
          "version": {
            "requires": "1.19.0-alpha"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-exporter-prometheus",
          "version": {
            "requires": "1.19.0-alpha"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-extension-incubator",
          "version": {
            "requires": "1.19.0-alpha"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-sdk-logs",
          "version": {
            "requires": "1.19.0-alpha"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-sdk-logs-testing",
          "version": {
            "requires": "1.19.0-alpha"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-sdk-extension-autoconfigure",
          "version": {
            "requires": "1.19.0-alpha"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-sdk-extension-incubator",
          "version": {
            "requires": "1.19.0-alpha"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-exporter-otlp-logs",
          "version": {
            "requires": "1.19.0-alpha"
          }
        }
      ]
    }
  ]
}
