{
  "formatVersion": "1.1",
  "component": {
    "group": "org.grails",
    "module": "grails-taglib",
    "version": "6.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.codehaus.groovy",
          "module": "groovy",
          "version": {
            "requires": "3.0.11"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.grails",
          "module": "grails-core",
          "version": {
            "requires": "6.1.1"
          },
          "excludes": [
            {
              "group": "org.grails",
              "module": "grails-spring"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-encoder",
          "version": {
            "requires": "6.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "grails-taglib-6.1.3.jar",
          "url": "grails-taglib-6.1.3.jar",
          "size": 96506,
          "sha512": "e35584eb135ec173a05151cdd31e75ac2ec0279bc597bafbe88ca3912de8a518676e79b1a0c32085b4db1ff164f1b1c5340756974cbfe073a6b69dccfa764047",
          "sha256": "2facce9175ed3bdbfd374e8a2b6a016c9e4ff0c4cd6cd8d3c8abcc1a648d89d0",
          "sha1": "fe360aa558397c996572585a910140759542ae21",
          "md5": "471012ac40ba2ad552c60cd6318b2b54"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.codehaus.groovy",
          "module": "groovy",
          "version": {
            "requires": "3.0.11"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.grails",
          "module": "grails-core",
          "version": {
            "requires": "6.1.1"
          },
          "excludes": [
            {
              "group": "org.grails",
              "module": "grails-spring"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-encoder",
          "version": {
            "requires": "6.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "grails-taglib-6.1.3.jar",
          "url": "grails-taglib-6.1.3.jar",
          "size": 96506,
          "sha512": "e35584eb135ec173a05151cdd31e75ac2ec0279bc597bafbe88ca3912de8a518676e79b1a0c32085b4db1ff164f1b1c5340756974cbfe073a6b69dccfa764047",
          "sha256": "2facce9175ed3bdbfd374e8a2b6a016c9e4ff0c4cd6cd8d3c8abcc1a648d89d0",
          "sha1": "fe360aa558397c996572585a910140759542ae21",
          "md5": "471012ac40ba2ad552c60cd6318b2b54"
        }
      ]
    }
  ]
}
