{
  "formatVersion": "1.1",
  "component": {
    "group": "io.opentelemetry",
    "module": "opentelemetry-bom-alpha",
    "version": "1.15.0-alpha",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "java-api"
      },
      "dependencyConstraints": [
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-micrometer1-shim",
          "version": {
            "requires": "1.15.0-alpha"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-opencensus-shim",
          "version": {
            "requires": "1.15.0-alpha"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-opentracing-shim",
          "version": {
            "requires": "1.15.0-alpha"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-semconv",
          "version": {
            "requires": "1.15.0-alpha"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-exporter-prometheus",
          "version": {
            "requires": "1.15.0-alpha"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-extension-incubator",
          "version": {
            "requires": "1.15.0-alpha"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-extension-noop-api",
          "version": {
            "requires": "1.15.0-alpha"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-sdk-logs",
          "version": {
            "requires": "1.15.0-alpha"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-sdk-logs-testing",
          "version": {
            "requires": "1.15.0-alpha"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-sdk-extension-autoconfigure",
          "version": {
            "requires": "1.15.0-alpha"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-sdk-extension-jfr-events",
          "version": {
            "requires": "1.15.0-alpha"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-sdk-extension-metric-incubator",
          "version": {
            "requires": "1.15.0-alpha"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-sdk-extension-tracing-incubator",
          "version": {
            "requires": "1.15.0-alpha"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-sdk-extension-zpages",
          "version": {
            "requires": "1.15.0-alpha"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-exporter-otlp-logs",
          "version": {
            "requires": "1.15.0-alpha"
          }
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-micrometer1-shim",
          "version": {
            "requires": "1.15.0-alpha"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-opencensus-shim",
          "version": {
            "requires": "1.15.0-alpha"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-opentracing-shim",
          "version": {
            "requires": "1.15.0-alpha"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-semconv",
          "version": {
            "requires": "1.15.0-alpha"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-exporter-prometheus",
          "version": {
            "requires": "1.15.0-alpha"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-extension-incubator",
          "version": {
            "requires": "1.15.0-alpha"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-extension-noop-api",
          "version": {
            "requires": "1.15.0-alpha"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-sdk-logs",
          "version": {
            "requires": "1.15.0-alpha"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-sdk-logs-testing",
          "version": {
            "requires": "1.15.0-alpha"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-sdk-extension-autoconfigure",
          "version": {
            "requires": "1.15.0-alpha"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-sdk-extension-jfr-events",
          "version": {
            "requires": "1.15.0-alpha"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-sdk-extension-metric-incubator",
          "version": {
            "requires": "1.15.0-alpha"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-sdk-extension-tracing-incubator",
          "version": {
            "requires": "1.15.0-alpha"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-sdk-extension-zpages",
          "version": {
            "requires": "1.15.0-alpha"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-exporter-otlp-logs",
          "version": {
            "requires": "1.15.0-alpha"
          }
        }
      ]
    }
  ]
}
