{
  "formatVersion": "1.1",
  "component": {
    "group": "io.micronaut.testresources",
    "module": "micronaut-test-resources-bom",
    "version": "1.2.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.testcontainers",
          "module": "testcontainers-bom",
          "version": {
            "requires": "1.17.6"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "dependencyConstraints": [
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-build-tools",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-client",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-core",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-elasticsearch",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-embedded",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-hashicorp-vault",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-hibernate-reactive-core",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-hibernate-reactive-mariadb",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-hibernate-reactive-mssql",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-hibernate-reactive-mysql",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-hibernate-reactive-oracle-xe",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-hibernate-reactive-postgresql",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-hivemq",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-jdbc-core",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-jdbc-mariadb",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-jdbc-mssql",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-jdbc-mysql",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-jdbc-oracle-xe",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-jdbc-postgresql",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-kafka",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-mongodb",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-neo4j",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-r2dbc-core",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-r2dbc-mariadb",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-r2dbc-mssql",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-r2dbc-mysql",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-r2dbc-oracle-xe",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-r2dbc-pool",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-r2dbc-postgresql",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-rabbitmq",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-redis",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-server",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-testcontainers",
          "version": {
            "requires": "1.2.3"
          }
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.testcontainers",
          "module": "testcontainers-bom",
          "version": {
            "requires": "1.17.6"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "dependencyConstraints": [
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-build-tools",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-client",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-core",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-elasticsearch",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-embedded",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-hashicorp-vault",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-hibernate-reactive-core",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-hibernate-reactive-mariadb",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-hibernate-reactive-mssql",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-hibernate-reactive-mysql",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-hibernate-reactive-oracle-xe",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-hibernate-reactive-postgresql",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-hivemq",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-jdbc-core",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-jdbc-mariadb",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-jdbc-mssql",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-jdbc-mysql",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-jdbc-oracle-xe",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-jdbc-postgresql",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-kafka",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-mongodb",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-neo4j",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-r2dbc-core",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-r2dbc-mariadb",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-r2dbc-mssql",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-r2dbc-mysql",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-r2dbc-oracle-xe",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-r2dbc-pool",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-r2dbc-postgresql",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-rabbitmq",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-redis",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-server",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "io.micronaut.testresources",
          "module": "micronaut-test-resources-testcontainers",
          "version": {
            "requires": "1.2.3"
          }
        }
      ]
    },
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "micronaut-test-resources-bom-1.2.3.toml",
          "url": "micronaut-test-resources-bom-1.2.3.toml",
          "size": 5988,
          "sha512": "d203a3e5bb1c659c60c37c499a8666dc009baf29b38f0b7fe2662275c8664112e1d7c72c9ca18fad49c6a51bb7497e72a591d2dc7c4c16366649ed5e4d8f117c",
          "sha256": "ff5617e16ec08e081de21f5dd9b4eac97fcafdd93d2f61e6dc8952510f8c51ad",
          "sha1": "550154bdd4a4e0db783ca195cc7954019e49442d",
          "md5": "548aad4956f626e7382d20fcce90684a"
        }
      ]
    }
  ]
}
