{
  "formatVersion": "1.1",
  "component": {
    "group": "org.grails",
    "module": "grails-datastore-core",
    "version": "8.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy",
          "version": {
            "requires": "3.0.11"
          }
        },
        {
          "group": "javax.transaction",
          "module": "jta",
          "version": {
            "requires": "1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "org.slf4j",
          "module": "jcl-over-slf4j",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "javax.persistence",
          "module": "javax.persistence-api",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.27"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "5.3.27"
          },
          "excludes": [
            {
              "group": "org.springframework",
              "module": "spring-core"
            },
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-tx",
          "version": {
            "requires": "5.3.27"
          },
          "excludes": [
            {
              "group": "org.springframework",
              "module": "spring-core"
            },
            {
              "group": "org.springframework",
              "module": "spring-aop"
            },
            {
              "group": "org.springframework",
              "module": "spring-beans"
            },
            {
              "group": "commons-logging",
              "module": "commons-logging"
            },
            {
              "group": "org.springframework",
              "module": "spring-context"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "5.3.27"
          },
          "excludes": [
            {
              "group": "org.springframework",
              "module": "spring-expression"
            },
            {
              "group": "org.springframework",
              "module": "spring-core"
            },
            {
              "group": "org.springframework",
              "module": "spring-aop"
            },
            {
              "group": "org.springframework",
              "module": "spring-asm"
            },
            {
              "group": "org.springframework",
              "module": "spring-beans"
            },
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "grails-datastore-core-8.0.0.jar",
          "url": "grails-datastore-core-8.0.0.jar",
          "size": 593533,
          "sha512": "b1467ca57a0707d2afc855bf64a3f464600070770e2f1c1aba2ba2e5a2881012e198599fd94240583ad38e3fcf71f47630cbb20290497001e326a2830e7feff4",
          "sha256": "ee5abdd879cbff79bd7de9a4ca073a91be4d877f32f4515621d45aa7e33b1062",
          "sha1": "a91f9d67526e74e8c658c4ee2a910ac832e7bede",
          "md5": "4ae7ec97f4a777df5541c7c70cda179c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.ben-manes.caffeine",
          "module": "caffeine",
          "version": {
            "requires": "2.9.3"
          }
        },
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.29.2-GA"
          }
        },
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy",
          "version": {
            "requires": "3.0.11"
          }
        },
        {
          "group": "javax.transaction",
          "module": "jta",
          "version": {
            "requires": "1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "org.slf4j",
          "module": "jcl-over-slf4j",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "javax.persistence",
          "module": "javax.persistence-api",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.27"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "5.3.27"
          },
          "excludes": [
            {
              "group": "org.springframework",
              "module": "spring-core"
            },
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-tx",
          "version": {
            "requires": "5.3.27"
          },
          "excludes": [
            {
              "group": "org.springframework",
              "module": "spring-core"
            },
            {
              "group": "org.springframework",
              "module": "spring-aop"
            },
            {
              "group": "org.springframework",
              "module": "spring-beans"
            },
            {
              "group": "commons-logging",
              "module": "commons-logging"
            },
            {
              "group": "org.springframework",
              "module": "spring-context"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "5.3.27"
          },
          "excludes": [
            {
              "group": "org.springframework",
              "module": "spring-expression"
            },
            {
              "group": "org.springframework",
              "module": "spring-core"
            },
            {
              "group": "org.springframework",
              "module": "spring-aop"
            },
            {
              "group": "org.springframework",
              "module": "spring-asm"
            },
            {
              "group": "org.springframework",
              "module": "spring-beans"
            },
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "grails-datastore-core-8.0.0.jar",
          "url": "grails-datastore-core-8.0.0.jar",
          "size": 593533,
          "sha512": "b1467ca57a0707d2afc855bf64a3f464600070770e2f1c1aba2ba2e5a2881012e198599fd94240583ad38e3fcf71f47630cbb20290497001e326a2830e7feff4",
          "sha256": "ee5abdd879cbff79bd7de9a4ca073a91be4d877f32f4515621d45aa7e33b1062",
          "sha1": "a91f9d67526e74e8c658c4ee2a910ac832e7bede",
          "md5": "4ae7ec97f4a777df5541c7c70cda179c"
        }
      ]
    }
  ]
}
