{
  "formatVersion": "1.1",
  "component": {
    "group": "io.micronaut.gcp",
    "module": "micronaut-gcp-bom",
    "version": "4.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "java-api"
      },
      "dependencyConstraints": [
        {
          "group": "com.google.cloud.functions",
          "module": "functions-framework-api",
          "version": {
            "requires": "1.0.4"
          }
        },
        {
          "group": "com.google.auth",
          "module": "google-auth-library-oauth2-http",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.google.cloud",
          "module": "google-cloud-core",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.google.cloud",
          "module": "google-cloud-pubsub",
          "version": {
            "requires": "1.122.2"
          }
        },
        {
          "group": "com.google.cloud",
          "module": "google-cloud-secretmanager",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "com.google.cloud",
          "module": "google-cloudevent-types",
          "version": {
            "requires": "0.3.0"
          }
        },
        {
          "group": "com.google.cloud",
          "module": "native-image-support",
          "version": {
            "requires": "0.14.1"
          }
        },
        {
          "group": "io.micronaut.gcp",
          "module": "micronaut-gcp-common",
          "version": {
            "requires": "4.8.0"
          }
        },
        {
          "group": "io.micronaut.gcp",
          "module": "micronaut-gcp-function",
          "version": {
            "requires": "4.8.0"
          }
        },
        {
          "group": "io.micronaut.gcp",
          "module": "micronaut-gcp-function-cloudevents",
          "version": {
            "requires": "4.8.0"
          }
        },
        {
          "group": "io.micronaut.gcp",
          "module": "micronaut-gcp-function-http",
          "version": {
            "requires": "4.8.0"
          }
        },
        {
          "group": "io.micronaut.gcp",
          "module": "micronaut-gcp-function-http-test",
          "version": {
            "requires": "4.8.0"
          }
        },
        {
          "group": "io.micronaut.gcp",
          "module": "micronaut-gcp-http-client",
          "version": {
            "requires": "4.8.0"
          }
        },
        {
          "group": "io.micronaut.gcp",
          "module": "micronaut-gcp-logging",
          "version": {
            "requires": "4.8.0"
          }
        },
        {
          "group": "io.micronaut.gcp",
          "module": "micronaut-gcp-pubsub",
          "version": {
            "requires": "4.8.0"
          }
        },
        {
          "group": "io.micronaut.gcp",
          "module": "micronaut-gcp-secret-manager",
          "version": {
            "requires": "4.8.0"
          }
        },
        {
          "group": "io.micronaut.gcp",
          "module": "micronaut-gcp-serde-cloudevents",
          "version": {
            "requires": "4.8.0"
          }
        },
        {
          "group": "io.micronaut.gcp",
          "module": "micronaut-gcp-tracing",
          "version": {
            "requires": "4.8.0"
          }
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "com.google.cloud.functions",
          "module": "functions-framework-api",
          "version": {
            "requires": "1.0.4"
          }
        },
        {
          "group": "com.google.auth",
          "module": "google-auth-library-oauth2-http",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.google.cloud",
          "module": "google-cloud-core",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.google.cloud",
          "module": "google-cloud-pubsub",
          "version": {
            "requires": "1.122.2"
          }
        },
        {
          "group": "com.google.cloud",
          "module": "google-cloud-secretmanager",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "com.google.cloud",
          "module": "google-cloudevent-types",
          "version": {
            "requires": "0.3.0"
          }
        },
        {
          "group": "com.google.cloud",
          "module": "native-image-support",
          "version": {
            "requires": "0.14.1"
          }
        },
        {
          "group": "io.micronaut.gcp",
          "module": "micronaut-gcp-common",
          "version": {
            "requires": "4.8.0"
          }
        },
        {
          "group": "io.micronaut.gcp",
          "module": "micronaut-gcp-function",
          "version": {
            "requires": "4.8.0"
          }
        },
        {
          "group": "io.micronaut.gcp",
          "module": "micronaut-gcp-function-cloudevents",
          "version": {
            "requires": "4.8.0"
          }
        },
        {
          "group": "io.micronaut.gcp",
          "module": "micronaut-gcp-function-http",
          "version": {
            "requires": "4.8.0"
          }
        },
        {
          "group": "io.micronaut.gcp",
          "module": "micronaut-gcp-function-http-test",
          "version": {
            "requires": "4.8.0"
          }
        },
        {
          "group": "io.micronaut.gcp",
          "module": "micronaut-gcp-http-client",
          "version": {
            "requires": "4.8.0"
          }
        },
        {
          "group": "io.micronaut.gcp",
          "module": "micronaut-gcp-logging",
          "version": {
            "requires": "4.8.0"
          }
        },
        {
          "group": "io.micronaut.gcp",
          "module": "micronaut-gcp-pubsub",
          "version": {
            "requires": "4.8.0"
          }
        },
        {
          "group": "io.micronaut.gcp",
          "module": "micronaut-gcp-secret-manager",
          "version": {
            "requires": "4.8.0"
          }
        },
        {
          "group": "io.micronaut.gcp",
          "module": "micronaut-gcp-serde-cloudevents",
          "version": {
            "requires": "4.8.0"
          }
        },
        {
          "group": "io.micronaut.gcp",
          "module": "micronaut-gcp-tracing",
          "version": {
            "requires": "4.8.0"
          }
        }
      ]
    },
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "micronaut-gcp-bom-4.8.0.toml",
          "url": "micronaut-gcp-bom-4.8.0.toml",
          "size": 2871,
          "sha512": "a175923393e50090d829ced5f74f27b3b7d5d2211eeff569397901285b65446e7dfde7cfabd9a9ece02a669d0203f5e3080f93481b99d8dbf5c35fa61d64bd04",
          "sha256": "b4754168341ada5ac9f72c707df78cbf698da6b6e812f3b88dd3793815c87219",
          "sha1": "a250572c4872d74714f22c42313a3bc1b438d406",
          "md5": "80e7178b6713972b2579d0d33c32f03a"
        }
      ]
    }
  ]
}
