{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-context-support",
    "version": "5.3.32",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "5.3.32"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "5.3.32"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.32"
          }
        }
      ],
      "files": [
        {
          "name": "spring-context-support-5.3.32.jar",
          "url": "spring-context-support-5.3.32.jar",
          "size": 187183,
          "sha512": "6ad0e0ee47e4e926a023c290537fd65e49d4ddd88c63aa1736bee3b8c006934a73c42895dfc429092c12d4c3965b5e86b779c89c27261f786bf2aa545cf24809",
          "sha256": "ac3b482d67f2b27bd090be483e889b9338c4323a2af235e65baca167232ddbe6",
          "sha1": "ce815bccda3d0147cf016d0b134704ea454cc483",
          "md5": "69bcc6e4a853f24b7f7c307261d64af8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "5.3.32"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "5.3.32"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.32"
          }
        }
      ],
      "files": [
        {
          "name": "spring-context-support-5.3.32.jar",
          "url": "spring-context-support-5.3.32.jar",
          "size": 187183,
          "sha512": "6ad0e0ee47e4e926a023c290537fd65e49d4ddd88c63aa1736bee3b8c006934a73c42895dfc429092c12d4c3965b5e86b779c89c27261f786bf2aa545cf24809",
          "sha256": "ac3b482d67f2b27bd090be483e889b9338c4323a2af235e65baca167232ddbe6",
          "sha1": "ce815bccda3d0147cf016d0b134704ea454cc483",
          "md5": "69bcc6e4a853f24b7f7c307261d64af8"
        }
      ]
    }
  ]
}
