{
  "formatVersion": "1.1",
  "component": {
    "group": "org.grails",
    "module": "grails-datastore-core",
    "version": "8.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy",
          "version": {
            "requires": "3.0.11"
          }
        },
        {
          "group": "javax.transaction",
          "module": "jta",
          "version": {
            "requires": "1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "org.slf4j",
          "module": "jcl-over-slf4j",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "javax.persistence",
          "module": "javax.persistence-api",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.31"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "5.3.31"
          },
          "excludes": [
            {
              "group": "org.springframework",
              "module": "spring-core"
            },
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-tx",
          "version": {
            "requires": "5.3.31"
          },
          "excludes": [
            {
              "group": "org.springframework",
              "module": "spring-core"
            },
            {
              "group": "org.springframework",
              "module": "spring-aop"
            },
            {
              "group": "org.springframework",
              "module": "spring-beans"
            },
            {
              "group": "commons-logging",
              "module": "commons-logging"
            },
            {
              "group": "org.springframework",
              "module": "spring-context"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "5.3.31"
          },
          "excludes": [
            {
              "group": "org.springframework",
              "module": "spring-expression"
            },
            {
              "group": "org.springframework",
              "module": "spring-core"
            },
            {
              "group": "org.springframework",
              "module": "spring-aop"
            },
            {
              "group": "org.springframework",
              "module": "spring-asm"
            },
            {
              "group": "org.springframework",
              "module": "spring-beans"
            },
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "grails-datastore-core-8.0.4.jar",
          "url": "grails-datastore-core-8.0.4.jar",
          "size": 593533,
          "sha512": "f2a5d7e734a9d85154af85219d24a845c9d9cf0db56c79b98e1dcb18d4ce0d1ae67092d1d679f1f47f7cf7882d9b30f825ee9b7eef93866318a53233ae380d74",
          "sha256": "0c286a1bec81b0054315755d7d209a668a62d9df098d0c91dbd457328552499c",
          "sha1": "a7921fb2bf6115d9c56fd7b17652b678e485e664",
          "md5": "6c5fc1896b65fea497e8613c092b75bf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.ben-manes.caffeine",
          "module": "caffeine",
          "version": {
            "requires": "2.9.3"
          }
        },
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.30.2-GA"
          }
        },
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy",
          "version": {
            "requires": "3.0.11"
          }
        },
        {
          "group": "javax.transaction",
          "module": "jta",
          "version": {
            "requires": "1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "org.slf4j",
          "module": "jcl-over-slf4j",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "javax.persistence",
          "module": "javax.persistence-api",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.31"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "5.3.31"
          },
          "excludes": [
            {
              "group": "org.springframework",
              "module": "spring-core"
            },
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-tx",
          "version": {
            "requires": "5.3.31"
          },
          "excludes": [
            {
              "group": "org.springframework",
              "module": "spring-core"
            },
            {
              "group": "org.springframework",
              "module": "spring-aop"
            },
            {
              "group": "org.springframework",
              "module": "spring-beans"
            },
            {
              "group": "commons-logging",
              "module": "commons-logging"
            },
            {
              "group": "org.springframework",
              "module": "spring-context"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "5.3.31"
          },
          "excludes": [
            {
              "group": "org.springframework",
              "module": "spring-expression"
            },
            {
              "group": "org.springframework",
              "module": "spring-core"
            },
            {
              "group": "org.springframework",
              "module": "spring-aop"
            },
            {
              "group": "org.springframework",
              "module": "spring-asm"
            },
            {
              "group": "org.springframework",
              "module": "spring-beans"
            },
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "grails-datastore-core-8.0.4.jar",
          "url": "grails-datastore-core-8.0.4.jar",
          "size": 593533,
          "sha512": "f2a5d7e734a9d85154af85219d24a845c9d9cf0db56c79b98e1dcb18d4ce0d1ae67092d1d679f1f47f7cf7882d9b30f825ee9b7eef93866318a53233ae380d74",
          "sha256": "0c286a1bec81b0054315755d7d209a668a62d9df098d0c91dbd457328552499c",
          "sha1": "a7921fb2bf6115d9c56fd7b17652b678e485e664",
          "md5": "6c5fc1896b65fea497e8613c092b75bf"
        }
      ]
    }
  ]
}
