{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fasterxml.jackson.dataformat",
    "module": "jackson-dataformat-yaml",
    "version": "2.15.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "maven": {
      "version": "3.8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.15.0"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.15.0"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.15.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-dataformat-yaml-2.15.0.jar",
          "url": "jackson-dataformat-yaml-2.15.0.jar",
          "size": 53493,
          "sha512": "8a9f97573e23768ca50a0db549d8c724a1c1147257d1342bf34c5bb18760f4014fe8324a0053d8a3456765eae898b85084e61bcace665906777e990ea8b0e6c6",
          "sha256": "4ee87850b1f3ff16ce812fbaf470e8ac070cc41ab1ce134481ba3adf3cb7ff31",
          "sha1": "7b72d36ce19685a8282d986b748e47cfc502d94a",
          "md5": "1eb963f315227a61a0d225905ddd0fb5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.15.0"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.15.0"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.15.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-dataformat-yaml-2.15.0.jar",
          "url": "jackson-dataformat-yaml-2.15.0.jar",
          "size": 53493,
          "sha512": "8a9f97573e23768ca50a0db549d8c724a1c1147257d1342bf34c5bb18760f4014fe8324a0053d8a3456765eae898b85084e61bcace665906777e990ea8b0e6c6",
          "sha256": "4ee87850b1f3ff16ce812fbaf470e8ac070cc41ab1ce134481ba3adf3cb7ff31",
          "sha1": "7b72d36ce19685a8282d986b748e47cfc502d94a",
          "md5": "1eb963f315227a61a0d225905ddd0fb5"
        }
      ]
    }
  ]
}
