{
  "formatVersion": "1.1",
  "component": {
    "group": "org.grails.plugins",
    "module": "gsp",
    "version": "6.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.grails",
          "module": "grails-web-gsp-taglib",
          "version": {
            "requires": "6.1.3"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "org.grails.plugins",
          "module": "sitemesh2",
          "version": {
            "requires": "6.1.3"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "commons-lang",
          "module": "commons-lang",
          "version": {
            "requires": "2.6"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-plugin-codecs",
          "version": {
            "requires": "6.1.1"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "gsp-6.1.3-plain.jar",
          "url": "gsp-6.1.3-plain.jar",
          "size": 329907,
          "sha512": "7511640995f4655c6285fb7c334976c15304f0752c8249e3c5434a3416878cbf46d310c3fd324453b35c505b50837c07053ac4b6b49fba6d1383c2326531177a",
          "sha256": "68835f3f758ec6e7417186308b3b63357c5650a5183c1394bafd5e6ab699fae7",
          "sha1": "0ebe6768337680a8eac6e1a8e451c6a066750754",
          "md5": "49f3f2f7bf740c680cfb5937767b9161"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.grails",
          "module": "grails-web-gsp-taglib",
          "version": {
            "requires": "6.1.3"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "org.grails.plugins",
          "module": "sitemesh2",
          "version": {
            "requires": "6.1.3"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "commons-lang",
          "module": "commons-lang",
          "version": {
            "requires": "2.6"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-plugin-codecs",
          "version": {
            "requires": "6.1.1"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-web-jsp",
          "version": {
            "requires": "6.1.3"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "gsp-6.1.3-plain.jar",
          "url": "gsp-6.1.3-plain.jar",
          "size": 329907,
          "sha512": "7511640995f4655c6285fb7c334976c15304f0752c8249e3c5434a3416878cbf46d310c3fd324453b35c505b50837c07053ac4b6b49fba6d1383c2326531177a",
          "sha256": "68835f3f758ec6e7417186308b3b63357c5650a5183c1394bafd5e6ab699fae7",
          "sha1": "0ebe6768337680a8eac6e1a8e451c6a066750754",
          "md5": "49f3f2f7bf740c680cfb5937767b9161"
        }
      ]
    }
  ]
}
