{
  "formatVersion": "1.1",
  "component": {
    "group": "org.grails.plugins",
    "module": "sitemesh2",
    "version": "6.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.grails",
          "module": "grails-plugin-codecs",
          "version": {
            "requires": "6.1.1"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-web-sitemesh",
          "version": {
            "requires": "6.1.3"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            },
            {
              "group": "org.grails",
              "module": "grails-web-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sitemesh2-6.1.3-plain.jar",
          "url": "sitemesh2-6.1.3-plain.jar",
          "size": 47099,
          "sha512": "af79ff9265b8ceb312cd4c8d4f9f8b65ac2f7753bfb628c213ecc4e65d400040712a2aaf1cc61dd61727dad669ef3be2cf34ce334116e383c55965b4a2b3697e",
          "sha256": "b2fbefe86f58a8c74e1e2c333f64ec968273415661c06c56e926a5bf51e3d1ea",
          "sha1": "5f43ef6ae81a75b077c79a13a78cd888f2ad9f2b",
          "md5": "c7d4fedcb44c0fc4d86007e08a86ca4d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.grails",
          "module": "grails-plugin-codecs",
          "version": {
            "requires": "6.1.1"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-web-sitemesh",
          "version": {
            "requires": "6.1.3"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            },
            {
              "group": "org.grails",
              "module": "grails-web-common"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-web-jsp",
          "version": {
            "requires": "6.1.3"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sitemesh2-6.1.3-plain.jar",
          "url": "sitemesh2-6.1.3-plain.jar",
          "size": 47099,
          "sha512": "af79ff9265b8ceb312cd4c8d4f9f8b65ac2f7753bfb628c213ecc4e65d400040712a2aaf1cc61dd61727dad669ef3be2cf34ce334116e383c55965b4a2b3697e",
          "sha256": "b2fbefe86f58a8c74e1e2c333f64ec968273415661c06c56e926a5bf51e3d1ea",
          "sha1": "5f43ef6ae81a75b077c79a13a78cd888f2ad9f2b",
          "md5": "c7d4fedcb44c0fc4d86007e08a86ca4d"
        }
      ]
    }
  ]
}
