{
  "formatVersion": "1.1",
  "component": {
    "group": "org.grails",
    "module": "grails-gorm-testing-support",
    "version": "3.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.codehaus.groovy",
          "module": "groovy",
          "version": {
            "requires": "3.0.11"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "org.grails",
          "module": "grails-plugin-domain-class",
          "version": {
            "requires": "6.0.0-RC1"
          }
        },
        {
          "group": "org.grails",
          "module": "grails-datastore-gorm-test",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "org.grails",
          "module": "grails-testing-support",
          "version": {
            "requires": "3.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "grails-gorm-testing-support-3.0.0.jar",
          "url": "grails-gorm-testing-support-3.0.0.jar",
          "size": 36678,
          "sha512": "a861a0da52d7706e1e4dc6389f2595f5356d0977128e0c35fbfa4e8b1721a2ac0e932a366c17150ccd70bd9065af37ffd5b5ca59adaab511845a4cc815fd5038",
          "sha256": "cec941f53d72b8ba0e7b76c7784f19ee614d7f7faae1057ea85aad83949a97dc",
          "sha1": "4841e5c3d5a404f92f6df0402a2dd9132c59485d",
          "md5": "56a18604309c5b9f696c42c89ce37f7c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.javaparser",
          "module": "javaparser-core",
          "version": {
            "requires": "3.15.14"
          }
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy",
          "version": {
            "requires": "3.0.11"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "org.grails",
          "module": "grails-plugin-domain-class",
          "version": {
            "requires": "6.0.0-RC1"
          }
        },
        {
          "group": "org.grails",
          "module": "grails-datastore-gorm-test",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "org.grails",
          "module": "grails-testing-support",
          "version": {
            "requires": "3.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "grails-gorm-testing-support-3.0.0.jar",
          "url": "grails-gorm-testing-support-3.0.0.jar",
          "size": 36678,
          "sha512": "a861a0da52d7706e1e4dc6389f2595f5356d0977128e0c35fbfa4e8b1721a2ac0e932a366c17150ccd70bd9065af37ffd5b5ca59adaab511845a4cc815fd5038",
          "sha256": "cec941f53d72b8ba0e7b76c7784f19ee614d7f7faae1057ea85aad83949a97dc",
          "sha1": "4841e5c3d5a404f92f6df0402a2dd9132c59485d",
          "md5": "56a18604309c5b9f696c42c89ce37f7c"
        }
      ]
    }
  ]
}
