{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-web",
    "version": "5.3.32",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "5.3.32"
          },
          "excludes": [
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            },
            {
              "group": "org.hamcrest",
              "module": "hamcrest-core"
            },
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.32"
          },
          "excludes": [
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            },
            {
              "group": "org.hamcrest",
              "module": "hamcrest-core"
            },
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-web-5.3.32.jar",
          "url": "spring-web-5.3.32.jar",
          "size": 1645150,
          "sha512": "ebfa40858c2bcc802799bb069201207f2207be0764e087122df0c105073caad9b00e53ee2b157b344e4cf136d26882f168d06c23a3c4a5dcdfa34a9cc091284d",
          "sha256": "6da6dbf369c092ada0cd17c67db51a199cc9b72cc72928d2201909af393b6650",
          "sha1": "fa6384f5c3ec1e14534a3e9293fc8274edb64649",
          "md5": "31bf81935cade306425a69af61c541ac"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "5.3.32"
          },
          "excludes": [
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            },
            {
              "group": "org.hamcrest",
              "module": "hamcrest-core"
            },
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.32"
          },
          "excludes": [
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            },
            {
              "group": "org.hamcrest",
              "module": "hamcrest-core"
            },
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-web-5.3.32.jar",
          "url": "spring-web-5.3.32.jar",
          "size": 1645150,
          "sha512": "ebfa40858c2bcc802799bb069201207f2207be0764e087122df0c105073caad9b00e53ee2b157b344e4cf136d26882f168d06c23a3c4a5dcdfa34a9cc091284d",
          "sha256": "6da6dbf369c092ada0cd17c67db51a199cc9b72cc72928d2201909af393b6650",
          "sha1": "fa6384f5c3ec1e14534a3e9293fc8274edb64649",
          "md5": "31bf81935cade306425a69af61c541ac"
        }
      ]
    }
  ]
}
