{
  "formatVersion": "1.1",
  "component": {
    "group": "io.micronaut.micrometer",
    "module": "micronaut-micrometer-bom",
    "version": "4.7.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.micrometer",
          "module": "micrometer-bom",
          "version": {
            "requires": "1.10.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "dependencyConstraints": [
        {
          "group": "io.dropwizard.metrics",
          "module": "metrics-core",
          "version": {
            "requires": "4.2.15"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-core",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "com.newrelic.telemetry",
          "module": "micrometer-registry-new-relic",
          "version": {
            "requires": "0.10.0"
          }
        },
        {
          "group": "io.micronaut.micrometer",
          "module": "micronaut-micrometer-annotation",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "io.micronaut.micrometer",
          "module": "micronaut-micrometer-core",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "io.micronaut.micrometer",
          "module": "micronaut-micrometer-registry-appoptics",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "io.micronaut.micrometer",
          "module": "micronaut-micrometer-registry-atlas",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "io.micronaut.micrometer",
          "module": "micronaut-micrometer-registry-azure-monitor",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "io.micronaut.micrometer",
          "module": "micronaut-micrometer-registry-cloudwatch",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "io.micronaut.micrometer",
          "module": "micronaut-micrometer-registry-datadog",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "io.micronaut.micrometer",
          "module": "micronaut-micrometer-registry-dynatrace",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "io.micronaut.micrometer",
          "module": "micronaut-micrometer-registry-elastic",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "io.micronaut.micrometer",
          "module": "micronaut-micrometer-registry-ganglia",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "io.micronaut.micrometer",
          "module": "micronaut-micrometer-registry-graphite",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "io.micronaut.micrometer",
          "module": "micronaut-micrometer-registry-humio",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "io.micronaut.micrometer",
          "module": "micronaut-micrometer-registry-influx",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "io.micronaut.micrometer",
          "module": "micronaut-micrometer-registry-jmx",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "io.micronaut.micrometer",
          "module": "micronaut-micrometer-registry-kairos",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "io.micronaut.micrometer",
          "module": "micronaut-micrometer-registry-new-relic",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "io.micronaut.micrometer",
          "module": "micronaut-micrometer-registry-new-relic-telemetry",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "io.micronaut.micrometer",
          "module": "micronaut-micrometer-registry-prometheus",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "io.micronaut.micrometer",
          "module": "micronaut-micrometer-registry-signalfx",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "io.micronaut.micrometer",
          "module": "micronaut-micrometer-registry-stackdriver",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "io.micronaut.micrometer",
          "module": "micronaut-micrometer-registry-statsd",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "io.micronaut.micrometer",
          "module": "micronaut-micrometer-registry-wavefront",
          "version": {
            "requires": "4.7.2"
          }
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.micrometer",
          "module": "micrometer-bom",
          "version": {
            "requires": "1.10.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "dependencyConstraints": [
        {
          "group": "io.dropwizard.metrics",
          "module": "metrics-core",
          "version": {
            "requires": "4.2.15"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-core",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "com.newrelic.telemetry",
          "module": "micrometer-registry-new-relic",
          "version": {
            "requires": "0.10.0"
          }
        },
        {
          "group": "io.micronaut.micrometer",
          "module": "micronaut-micrometer-annotation",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "io.micronaut.micrometer",
          "module": "micronaut-micrometer-core",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "io.micronaut.micrometer",
          "module": "micronaut-micrometer-registry-appoptics",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "io.micronaut.micrometer",
          "module": "micronaut-micrometer-registry-atlas",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "io.micronaut.micrometer",
          "module": "micronaut-micrometer-registry-azure-monitor",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "io.micronaut.micrometer",
          "module": "micronaut-micrometer-registry-cloudwatch",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "io.micronaut.micrometer",
          "module": "micronaut-micrometer-registry-datadog",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "io.micronaut.micrometer",
          "module": "micronaut-micrometer-registry-dynatrace",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "io.micronaut.micrometer",
          "module": "micronaut-micrometer-registry-elastic",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "io.micronaut.micrometer",
          "module": "micronaut-micrometer-registry-ganglia",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "io.micronaut.micrometer",
          "module": "micronaut-micrometer-registry-graphite",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "io.micronaut.micrometer",
          "module": "micronaut-micrometer-registry-humio",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "io.micronaut.micrometer",
          "module": "micronaut-micrometer-registry-influx",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "io.micronaut.micrometer",
          "module": "micronaut-micrometer-registry-jmx",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "io.micronaut.micrometer",
          "module": "micronaut-micrometer-registry-kairos",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "io.micronaut.micrometer",
          "module": "micronaut-micrometer-registry-new-relic",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "io.micronaut.micrometer",
          "module": "micronaut-micrometer-registry-new-relic-telemetry",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "io.micronaut.micrometer",
          "module": "micronaut-micrometer-registry-prometheus",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "io.micronaut.micrometer",
          "module": "micronaut-micrometer-registry-signalfx",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "io.micronaut.micrometer",
          "module": "micronaut-micrometer-registry-stackdriver",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "io.micronaut.micrometer",
          "module": "micronaut-micrometer-registry-statsd",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "io.micronaut.micrometer",
          "module": "micronaut-micrometer-registry-wavefront",
          "version": {
            "requires": "4.7.2"
          }
        }
      ]
    },
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "micronaut-micrometer-bom-4.7.2.toml",
          "url": "micronaut-micrometer-bom-4.7.2.toml",
          "size": 4350,
          "sha512": "59093b419999d06459c7d557dc2b94da405b48f6fd1420c6227480e25e29efe98ebc34ff1e1a3d5cc7e778155ab8606461fb69bd1c1ee41ed99baa90f2d5ea16",
          "sha256": "00762f8ea78fc3231e8ae30d3222f77b4e97feab248eebb5d62148a3cf87f260",
          "sha1": "2c0c694eb32e340474628c1d3f3ae7011a80c9c8",
          "md5": "1707ae39b1f6e4758aa36c895bbec55d"
        }
      ]
    }
  ]
}
