{
  "formatVersion": "1.1",
  "component": {
    "group": "io.micronaut.aws",
    "module": "micronaut-aws-bom",
    "version": "3.5.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.amazonaws",
          "module": "aws-java-sdk-bom",
          "version": {
            "requires": "1.12.267"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "software.amazon.awssdk",
          "module": "bom",
          "version": {
            "requires": "2.17.238"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "dependencyConstraints": [
        {
          "group": "com.amazon.alexa",
          "module": "ask-sdk-core",
          "version": {
            "requires": "2.43.7"
          }
        },
        {
          "group": "com.amazon.alexa",
          "module": "ask-sdk-lambda-support",
          "version": {
            "requires": "2.43.7"
          }
        },
        {
          "group": "com.amazonaws",
          "module": "aws-java-sdk-core",
          "version": {
            "requires": "1.12.267"
          }
        },
        {
          "group": "com.amazonaws",
          "module": "aws-lambda-java-core",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.amazonaws",
          "module": "aws-lambda-java-events",
          "version": {
            "requires": "3.11.0"
          }
        },
        {
          "group": "com.amazonaws.serverless",
          "module": "aws-serverless-java-container-core",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "software.amazon.awssdk",
          "module": "secretsmanager",
          "version": {
            "requires": "2.17.238"
          }
        },
        {
          "group": "org.slf4j",
          "module": "jcl-over-slf4j",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "io.micronaut.aws",
          "module": "micronaut-aws-alexa",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "io.micronaut.aws",
          "module": "micronaut-aws-alexa-httpserver",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "io.micronaut.aws",
          "module": "micronaut-aws-cdk",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "io.micronaut.aws",
          "module": "micronaut-aws-common",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "io.micronaut.aws",
          "module": "micronaut-aws-distributed-configuration",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "io.micronaut.aws",
          "module": "micronaut-aws-parameter-store",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "io.micronaut.aws",
          "module": "micronaut-aws-sdk-v1",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "io.micronaut.aws",
          "module": "micronaut-aws-sdk-v2",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "io.micronaut.aws",
          "module": "micronaut-aws-secretsmanager",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "io.micronaut.aws",
          "module": "micronaut-aws-service-discovery",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "io.micronaut.aws",
          "module": "micronaut-function-aws",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "io.micronaut.aws",
          "module": "micronaut-function-aws-alexa",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "io.micronaut.aws",
          "module": "micronaut-function-aws-api-proxy",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "io.micronaut.aws",
          "module": "micronaut-function-aws-api-proxy-test",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "io.micronaut.aws",
          "module": "micronaut-function-aws-custom-runtime",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "io.micronaut.aws",
          "module": "micronaut-function-aws-test",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "io.micronaut.aws",
          "module": "micronaut-function-client-aws",
          "version": {
            "requires": "3.5.3"
          }
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.amazonaws",
          "module": "aws-java-sdk-bom",
          "version": {
            "requires": "1.12.267"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "software.amazon.awssdk",
          "module": "bom",
          "version": {
            "requires": "2.17.238"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "dependencyConstraints": [
        {
          "group": "com.amazon.alexa",
          "module": "ask-sdk-core",
          "version": {
            "requires": "2.43.7"
          }
        },
        {
          "group": "com.amazon.alexa",
          "module": "ask-sdk-lambda-support",
          "version": {
            "requires": "2.43.7"
          }
        },
        {
          "group": "com.amazonaws",
          "module": "aws-java-sdk-core",
          "version": {
            "requires": "1.12.267"
          }
        },
        {
          "group": "com.amazonaws",
          "module": "aws-lambda-java-core",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.amazonaws",
          "module": "aws-lambda-java-events",
          "version": {
            "requires": "3.11.0"
          }
        },
        {
          "group": "com.amazonaws.serverless",
          "module": "aws-serverless-java-container-core",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "software.amazon.awssdk",
          "module": "secretsmanager",
          "version": {
            "requires": "2.17.238"
          }
        },
        {
          "group": "org.slf4j",
          "module": "jcl-over-slf4j",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "io.micronaut.aws",
          "module": "micronaut-aws-alexa",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "io.micronaut.aws",
          "module": "micronaut-aws-alexa-httpserver",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "io.micronaut.aws",
          "module": "micronaut-aws-cdk",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "io.micronaut.aws",
          "module": "micronaut-aws-common",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "io.micronaut.aws",
          "module": "micronaut-aws-distributed-configuration",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "io.micronaut.aws",
          "module": "micronaut-aws-parameter-store",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "io.micronaut.aws",
          "module": "micronaut-aws-sdk-v1",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "io.micronaut.aws",
          "module": "micronaut-aws-sdk-v2",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "io.micronaut.aws",
          "module": "micronaut-aws-secretsmanager",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "io.micronaut.aws",
          "module": "micronaut-aws-service-discovery",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "io.micronaut.aws",
          "module": "micronaut-function-aws",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "io.micronaut.aws",
          "module": "micronaut-function-aws-alexa",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "io.micronaut.aws",
          "module": "micronaut-function-aws-api-proxy",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "io.micronaut.aws",
          "module": "micronaut-function-aws-api-proxy-test",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "io.micronaut.aws",
          "module": "micronaut-function-aws-custom-runtime",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "io.micronaut.aws",
          "module": "micronaut-function-aws-test",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "io.micronaut.aws",
          "module": "micronaut-function-client-aws",
          "version": {
            "requires": "3.5.3"
          }
        }
      ]
    },
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "micronaut-aws-bom-3.5.3.toml",
          "url": "micronaut-aws-bom-3.5.3.toml",
          "size": 3479,
          "sha512": "755837399dba1290807f343dd4b5501e9553931a381c337fa03b9a4a02c4fbcd41cb1c29ec341aab5bef887d4f8f1f00daa28d6d469c16dddb07e9fb99a66542",
          "sha256": "b2b73fc677f620384b63e54f60bf621ad78e58800b8934ee7039eeea3211c8a7",
          "sha1": "3ceb7edff0f95dd0887f03656b1e0089153808c9",
          "md5": "662ff949208c75d695acd2d35309cfea"
        }
      ]
    }
  ]
}
