{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-log4j2",
    "version": "2.7.18",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-slf4j-impl",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-jul",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "org.slf4j",
          "module": "jul-to-slf4j",
          "version": {
            "requires": "1.7.36"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-log4j2-2.7.18.jar",
          "url": "spring-boot-starter-log4j2-2.7.18.jar",
          "size": 4775,
          "sha512": "536aa7c6d26b2a7e680a46fbb4b5834b9b0cd016b48a4ef1f7d8111fcc8534c9f6e8c200f55dc55cb11a42577e8015a13b83ecb64c0ceba922a0dadd995003c5",
          "sha256": "e02945881f338f6d7eb0ab5df89e3b3fc890baac9e46d139673be99be8c2d24b",
          "sha1": "568a987eee34e80ee4815bfce0fc8a2a7201789d",
          "md5": "3d4f8529433dd9d2fe877e1d525d1535"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-slf4j-impl",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-jul",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "org.slf4j",
          "module": "jul-to-slf4j",
          "version": {
            "requires": "1.7.36"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-log4j2-2.7.18.jar",
          "url": "spring-boot-starter-log4j2-2.7.18.jar",
          "size": 4775,
          "sha512": "536aa7c6d26b2a7e680a46fbb4b5834b9b0cd016b48a4ef1f7d8111fcc8534c9f6e8c200f55dc55cb11a42577e8015a13b83ecb64c0ceba922a0dadd995003c5",
          "sha256": "e02945881f338f6d7eb0ab5df89e3b3fc890baac9e46d139673be99be8c2d24b",
          "sha1": "568a987eee34e80ee4815bfce0fc8a2a7201789d",
          "md5": "3d4f8529433dd9d2fe877e1d525d1535"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-starter-log4j2-2.7.18.jar",
          "url": "spring-boot-starter-log4j2-2.7.18.jar",
          "size": 4775,
          "sha512": "536aa7c6d26b2a7e680a46fbb4b5834b9b0cd016b48a4ef1f7d8111fcc8534c9f6e8c200f55dc55cb11a42577e8015a13b83ecb64c0ceba922a0dadd995003c5",
          "sha256": "e02945881f338f6d7eb0ab5df89e3b3fc890baac9e46d139673be99be8c2d24b",
          "sha1": "568a987eee34e80ee4815bfce0fc8a2a7201789d",
          "md5": "3d4f8529433dd9d2fe877e1d525d1535"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-log4j2-maven-optional",
          "version": "2.7.18"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-log4j2-2.7.18.jar",
          "url": "spring-boot-starter-log4j2-2.7.18.jar",
          "size": 4775,
          "sha512": "536aa7c6d26b2a7e680a46fbb4b5834b9b0cd016b48a4ef1f7d8111fcc8534c9f6e8c200f55dc55cb11a42577e8015a13b83ecb64c0ceba922a0dadd995003c5",
          "sha256": "e02945881f338f6d7eb0ab5df89e3b3fc890baac9e46d139673be99be8c2d24b",
          "sha1": "568a987eee34e80ee4815bfce0fc8a2a7201789d",
          "md5": "3d4f8529433dd9d2fe877e1d525d1535"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-log4j2-maven-optional",
          "version": "2.7.18"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-log4j2-2.7.18-javadoc.jar",
          "url": "spring-boot-starter-log4j2-2.7.18-javadoc.jar",
          "size": 4748,
          "sha512": "f8f8d624f033fa45b7bc91cd803e5d62c3d2788a1ae99aa86f7f43e6d5306029c5445e1ed17a2f781cf3576395d6855f8535153d3d775551f388642a79d49743",
          "sha256": "27eca8853685537d8caefcd56d4e332b89a1f488caaff8dd4a7721e7428df578",
          "sha1": "5755d74454848daa618e6da9eca46284bfaee058",
          "md5": "714647dbf31eedf9969ae3fb46f3fbe4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-log4j2-2.7.18-sources.jar",
          "url": "spring-boot-starter-log4j2-2.7.18-sources.jar",
          "size": 4746,
          "sha512": "0dadfd8963c1315de4afda8dc74a7e88ef698a8c24db4c969a4f37507a4d145c99f0f7c5f9154c565db68970a3104e24766b0c1a211ee6af74ed5f4d5b4f3c59",
          "sha256": "988519e4a3755dca7d0c43865da80d3f7e20c9c53b50928de8bcbfc104ca0961",
          "sha1": "2fc5d3038d35f0b1d23053029c1f1c728f5b0a08",
          "md5": "67c5aa992a293599fae9d588f39dcfcb"
        }
      ]
    }
  ]
}
