{
  "formatVersion": "1.1",
  "component": {
    "group": "io.micronaut.security",
    "module": "micronaut-security-bom",
    "version": "3.9.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "java-api"
      },
      "dependencyConstraints": [
        {
          "group": "com.nimbusds",
          "module": "nimbus-jose-jwt",
          "version": {
            "requires": "9.25.6"
          }
        },
        {
          "group": "io.micronaut.security",
          "module": "micronaut-security",
          "version": {
            "requires": "3.9.4"
          }
        },
        {
          "group": "io.micronaut.security",
          "module": "micronaut-security-annotations",
          "version": {
            "requires": "3.9.4"
          }
        },
        {
          "group": "io.micronaut.security",
          "module": "micronaut-security-aot",
          "version": {
            "requires": "3.9.4"
          }
        },
        {
          "group": "io.micronaut.security",
          "module": "micronaut-security-jwt",
          "version": {
            "requires": "3.9.4"
          }
        },
        {
          "group": "io.micronaut.security",
          "module": "micronaut-security-ldap",
          "version": {
            "requires": "3.9.4"
          }
        },
        {
          "group": "io.micronaut.security",
          "module": "micronaut-security-oauth2",
          "version": {
            "requires": "3.9.4"
          }
        },
        {
          "group": "io.micronaut.security",
          "module": "micronaut-security-session",
          "version": {
            "requires": "3.9.4"
          }
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "com.nimbusds",
          "module": "nimbus-jose-jwt",
          "version": {
            "requires": "9.25.6"
          }
        },
        {
          "group": "io.micronaut.security",
          "module": "micronaut-security",
          "version": {
            "requires": "3.9.4"
          }
        },
        {
          "group": "io.micronaut.security",
          "module": "micronaut-security-annotations",
          "version": {
            "requires": "3.9.4"
          }
        },
        {
          "group": "io.micronaut.security",
          "module": "micronaut-security-aot",
          "version": {
            "requires": "3.9.4"
          }
        },
        {
          "group": "io.micronaut.security",
          "module": "micronaut-security-jwt",
          "version": {
            "requires": "3.9.4"
          }
        },
        {
          "group": "io.micronaut.security",
          "module": "micronaut-security-ldap",
          "version": {
            "requires": "3.9.4"
          }
        },
        {
          "group": "io.micronaut.security",
          "module": "micronaut-security-oauth2",
          "version": {
            "requires": "3.9.4"
          }
        },
        {
          "group": "io.micronaut.security",
          "module": "micronaut-security-session",
          "version": {
            "requires": "3.9.4"
          }
        }
      ]
    },
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "micronaut-security-bom-3.9.4.toml",
          "url": "micronaut-security-bom-3.9.4.toml",
          "size": 1361,
          "sha512": "02e94190d106ea8258e0aa3a55ec2347ff65bced3548106f0321551a673fd1d8ba5bf9a52c6b3bcf9d77ac99cea10e8e56b15a55ee14a1ae8b41415cd9091bb9",
          "sha256": "35c0c89a0eb3eb9a40938b43dc9fda76352cb1bdfbe19b3379eb58246d7bd8a0",
          "sha1": "af7596b519c9743ea7a89b429a281e932d813f5a",
          "md5": "a94a05492d5a824a014ffd874e4482bf"
        }
      ]
    }
  ]
}
