{
  "formatVersion": "1.1",
  "component": {
    "group": "org.grails",
    "module": "grails-shell",
    "version": "6.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.codehaus.groovy",
          "module": "groovy",
          "version": {
            "requires": "3.0.11"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            },
            {
              "group": "*",
              "module": "commons-cli"
            },
            {
              "group": "*",
              "module": "ant"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "jcl-over-slf4j",
          "version": {
            "requires": "1.7.36"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-bootstrap",
          "version": {
            "requires": "6.0.0"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-gradle-model",
          "version": {
            "requires": "6.0.0"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.apache.ant",
          "module": "ant",
          "version": {
            "requires": "1.10.13"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy-ant",
          "version": {
            "requires": "3.0.11"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy-json",
          "version": {
            "requires": "3.0.11"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy-jmx",
          "version": {
            "requires": "3.0.11"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.fusesource.jansi",
          "module": "jansi",
          "version": {
            "requires": "1.18"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "jline",
          "module": "jline",
          "version": {
            "requires": "2.14.6"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.gradle",
          "module": "gradle-tooling-api",
          "version": {
            "requires": "7.3-20210825160000+0000"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-cli",
          "version": {
            "requires": "2.7.12"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            },
            {
              "group": "org.codehaus.groovy",
              "module": "groovy"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "grails-shell-6.0.0.jar",
          "url": "grails-shell-6.0.0.jar",
          "size": 487175,
          "sha512": "9fcf004afe9bfae69267f3d69f2564ac15bd1c9726f0de131bc3eba9ee45bd17b89ec66a36008a97c57fe04d09fa895ecad44f43232f2c2b078c91fb3b936a2f",
          "sha256": "d681c28fd511f4aed246614fab65e7419f0b9b6f341346a0168882f017bfd9f3",
          "sha1": "d9ecfe35e3884a2929357338e2bacbf2b46c80d3",
          "md5": "6bd353fca327dd7c23d88899cc221572"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.maven",
          "module": "maven-resolver-provider",
          "version": {
            "requires": "3.8.3"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            },
            {
              "group": "com.google.guava",
              "module": "guava"
            }
          ]
        },
        {
          "group": "org.apache.maven.resolver",
          "module": "maven-resolver-connector-basic",
          "version": {
            "requires": "1.9.13"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.apache.maven.resolver",
          "module": "maven-resolver-impl",
          "version": {
            "requires": "1.9.13"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.apache.maven.resolver",
          "module": "maven-resolver-transport-file",
          "version": {
            "requires": "1.9.13"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.apache.maven.resolver",
          "module": "maven-resolver-transport-http",
          "version": {
            "requires": "1.9.13"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            },
            {
              "group": "org.slf4j",
              "module": "jcl-over-slf4j"
            },
            {
              "group": "commons-codec",
              "module": "commons-codec"
            }
          ]
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.15"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy",
          "version": {
            "requires": "3.0.11"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            },
            {
              "group": "*",
              "module": "commons-cli"
            },
            {
              "group": "*",
              "module": "ant"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "jcl-over-slf4j",
          "version": {
            "requires": "1.7.36"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-bootstrap",
          "version": {
            "requires": "6.0.0"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-gradle-model",
          "version": {
            "requires": "6.0.0"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.apache.ant",
          "module": "ant",
          "version": {
            "requires": "1.10.13"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy-ant",
          "version": {
            "requires": "3.0.11"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy-json",
          "version": {
            "requires": "3.0.11"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy-jmx",
          "version": {
            "requires": "3.0.11"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.fusesource.jansi",
          "module": "jansi",
          "version": {
            "requires": "1.18"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "jline",
          "module": "jline",
          "version": {
            "requires": "2.14.6"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.gradle",
          "module": "gradle-tooling-api",
          "version": {
            "requires": "7.3-20210825160000+0000"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-cli",
          "version": {
            "requires": "2.7.12"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            },
            {
              "group": "org.codehaus.groovy",
              "module": "groovy"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-simple",
          "version": {
            "requires": "1.7.36"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.codehaus.plexus",
          "module": "plexus-component-api",
          "version": {
            "requires": "1.0-alpha-33"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "grails-shell-6.0.0.jar",
          "url": "grails-shell-6.0.0.jar",
          "size": 487175,
          "sha512": "9fcf004afe9bfae69267f3d69f2564ac15bd1c9726f0de131bc3eba9ee45bd17b89ec66a36008a97c57fe04d09fa895ecad44f43232f2c2b078c91fb3b936a2f",
          "sha256": "d681c28fd511f4aed246614fab65e7419f0b9b6f341346a0168882f017bfd9f3",
          "sha1": "d9ecfe35e3884a2929357338e2bacbf2b46c80d3",
          "md5": "6bd353fca327dd7c23d88899cc221572"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "grails-shell-6.0.0-javadoc.jar",
          "url": "grails-shell-6.0.0-javadoc.jar",
          "size": 350436,
          "sha512": "3a3eb400db0e2699effa7cad76a06a409fa19c0c690778f8084d363642265f07ff334038e1a2a9a3f7b4a82ecde80b896ddac0409425cce8f88cfccc6b3b411a",
          "sha256": "4aa257743ba2707fd30dac2e6ff615475eb1a920afd7bfee6e4aa91e0d816fa7",
          "sha1": "2723e3808fda05185d4e6e432cd546db94343669",
          "md5": "a3c17f84580cc50e84c38a76f6cad9cc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "grails-shell-6.0.0-sources.jar",
          "url": "grails-shell-6.0.0-sources.jar",
          "size": 130666,
          "sha512": "1d92b537c6810aca06f403e0a5c207d9aa33ce1b7b9d739ecdaee49abfb3ebec44a95ee7a4e8255f2d87f7a2cd3a726a1941e02c3635228333bf5536f0a8e9ed",
          "sha256": "3d5de3be4881aa3747a0821f38f6ffa5959d78d87762abdf8ca98d2b6d29f6d7",
          "sha1": "aadeb7d9cb45ab2c2ce24536e87e5a899dbe86b4",
          "md5": "e074cef856e52d3b39e57bf178c7b8c8"
        }
      ]
    }
  ]
}
