{
  "formatVersion": "1.1",
  "component": {
    "group": "org.grails",
    "module": "grails-web-url-mappings",
    "version": "6.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "javax.servlet",
          "module": "javax.servlet-api",
          "version": {
            "requires": "4.0.1"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-test",
          "version": {
            "requires": "5.3.27"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy",
          "version": {
            "requires": "3.0.11"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            },
            {
              "group": "*",
              "module": "commons-cli"
            },
            {
              "group": "*",
              "module": "ant"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "jcl-over-slf4j",
          "version": {
            "requires": "1.7.36"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-web-common",
          "version": {
            "requires": "6.0.0"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-datastore-gorm-validation",
          "version": {
            "requires": "8.0.0"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            },
            {
              "group": "org.springframework",
              "module": "spring-web"
            },
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            },
            {
              "group": "org.javassist",
              "module": "javassist"
            },
            {
              "group": "java-persistence",
              "module": "persistence-api"
            },
            {
              "group": "org.springframework",
              "module": "spring-core"
            },
            {
              "group": "org.slf4j",
              "module": "jul-to-slf4j"
            },
            {
              "group": "org.springframework",
              "module": "spring-beans"
            },
            {
              "group": "org.grails",
              "module": "grails-async"
            },
            {
              "group": "org.grails",
              "module": "grails-bootstrap"
            },
            {
              "group": "org.slf4j",
              "module": "slf4j-api"
            },
            {
              "group": "org.slf4j",
              "module": "jcl-over-slf4j"
            },
            {
              "group": "commons-collections",
              "module": "commons-collections"
            },
            {
              "group": "org.grails",
              "module": "grails-core"
            },
            {
              "group": "javax.persistence",
              "module": "persistence-api"
            },
            {
              "group": "org.springframework",
              "module": "spring-tx"
            },
            {
              "group": "javassist",
              "module": "javassist"
            },
            {
              "group": "commons-lang",
              "module": "commons-lang"
            },
            {
              "group": "org.springframework",
              "module": "spring-context"
            }
          ]
        },
        {
          "group": "org.fusesource.jansi",
          "module": "jansi",
          "version": {
            "requires": "1.18"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "jline",
          "module": "jline",
          "version": {
            "requires": "2.14.6"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "grails-web-url-mappings-6.0.0.jar",
          "url": "grails-web-url-mappings-6.0.0.jar",
          "size": 188020,
          "sha512": "306ee050b570a5b0b910a3063854580cf8e566b42d7611cfb40b10149d6240a161ae5e954bff284b71b5e17f08936d52a171f7efdbd5997d4bea2fcefb431c32",
          "sha256": "d92313e31c8040c0c5c489c2a1db97079e4fdf3ca980a54ec97430b71a8b3dfa",
          "sha1": "c33094cb1cf37d2bdd655e9595cc693bf64ae3a5",
          "md5": "da486ee9963d9fa3b3f960fc29e3e54f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.ben-manes.caffeine",
          "module": "caffeine",
          "version": {
            "requires": "2.9.3"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "javax.servlet",
          "module": "javax.servlet-api",
          "version": {
            "requires": "4.0.1"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-test",
          "version": {
            "requires": "5.3.27"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy",
          "version": {
            "requires": "3.0.11"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            },
            {
              "group": "*",
              "module": "commons-cli"
            },
            {
              "group": "*",
              "module": "ant"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "jcl-over-slf4j",
          "version": {
            "requires": "1.7.36"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-web-common",
          "version": {
            "requires": "6.0.0"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-datastore-gorm-validation",
          "version": {
            "requires": "8.0.0"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            },
            {
              "group": "org.springframework",
              "module": "spring-web"
            },
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            },
            {
              "group": "org.javassist",
              "module": "javassist"
            },
            {
              "group": "java-persistence",
              "module": "persistence-api"
            },
            {
              "group": "org.springframework",
              "module": "spring-core"
            },
            {
              "group": "org.slf4j",
              "module": "jul-to-slf4j"
            },
            {
              "group": "org.springframework",
              "module": "spring-beans"
            },
            {
              "group": "org.grails",
              "module": "grails-async"
            },
            {
              "group": "org.grails",
              "module": "grails-bootstrap"
            },
            {
              "group": "org.slf4j",
              "module": "slf4j-api"
            },
            {
              "group": "org.slf4j",
              "module": "jcl-over-slf4j"
            },
            {
              "group": "commons-collections",
              "module": "commons-collections"
            },
            {
              "group": "org.grails",
              "module": "grails-core"
            },
            {
              "group": "javax.persistence",
              "module": "persistence-api"
            },
            {
              "group": "org.springframework",
              "module": "spring-tx"
            },
            {
              "group": "javassist",
              "module": "javassist"
            },
            {
              "group": "commons-lang",
              "module": "commons-lang"
            },
            {
              "group": "org.springframework",
              "module": "spring-context"
            }
          ]
        },
        {
          "group": "org.fusesource.jansi",
          "module": "jansi",
          "version": {
            "requires": "1.18"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "jline",
          "module": "jline",
          "version": {
            "requires": "2.14.6"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "grails-web-url-mappings-6.0.0.jar",
          "url": "grails-web-url-mappings-6.0.0.jar",
          "size": 188020,
          "sha512": "306ee050b570a5b0b910a3063854580cf8e566b42d7611cfb40b10149d6240a161ae5e954bff284b71b5e17f08936d52a171f7efdbd5997d4bea2fcefb431c32",
          "sha256": "d92313e31c8040c0c5c489c2a1db97079e4fdf3ca980a54ec97430b71a8b3dfa",
          "sha1": "c33094cb1cf37d2bdd655e9595cc693bf64ae3a5",
          "md5": "da486ee9963d9fa3b3f960fc29e3e54f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "grails-web-url-mappings-6.0.0-javadoc.jar",
          "url": "grails-web-url-mappings-6.0.0-javadoc.jar",
          "size": 462340,
          "sha512": "975aa359a25d27848dc53704af62627df06940118f5210bbed63fe4b3c9d4bcaaf8ee625535ac7ae6572d309a731e5994d9551b28b71cb93f96f45e9f23658fa",
          "sha256": "8acbb4a70d609eeaa711c26375692ba3410adfc03c93186d9dab311f561f777d",
          "sha1": "f695dc83f643643f51cba9b0caed6d33d89f7b33",
          "md5": "6a84c246bbf5f95b1c2821ee02e99685"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "grails-web-url-mappings-6.0.0-sources.jar",
          "url": "grails-web-url-mappings-6.0.0-sources.jar",
          "size": 96434,
          "sha512": "75d0526eb32e2244d78f19d206479d51d9d3aade25534d1fc44f49b6e56280e177447d41a8895d7ea539e42c9f69e0470e1973df79f5e7c4e8b0d787aaa98f12",
          "sha256": "c5debfa7048ab1e81b0c31ed9c8ea86ef48885af244f974764b767f0deabdd21",
          "sha1": "da514859276762e943c430ea7d8205853465d8dc",
          "md5": "59ec838cc1fe40ebd70553d3a56bea07"
        }
      ]
    }
  ]
}
