{
  "formatVersion": "1.1",
  "component": {
    "group": "org.grails",
    "module": "grails-plugin-url-mappings",
    "version": "6.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "javax.servlet",
          "module": "javax.servlet-api",
          "version": {
            "requires": "4.0.1"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-test",
          "version": {
            "requires": "5.3.31"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy",
          "version": {
            "requires": "3.0.11"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            },
            {
              "group": "*",
              "module": "commons-cli"
            },
            {
              "group": "*",
              "module": "ant"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "jcl-over-slf4j",
          "version": {
            "requires": "1.7.36"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-web",
          "version": {
            "requires": "6.1.2"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-plugin-controllers",
          "version": {
            "requires": "6.1.2"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.13.2"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "grails-plugin-url-mappings-6.1.2.jar",
          "url": "grails-plugin-url-mappings-6.1.2.jar",
          "size": 22232,
          "sha512": "6b50dc61fa90e97a5198b51d15726fbce5c57cc1f6cb02e8c4eec1c521e44d0b4d8fa1a5a16a1bc0e270833c34b737305d05dfacc2ba4641f79e766a160db15e",
          "sha256": "9b22279f9040fb887d97ceba3287bb0c66a53f887a68e9e91b30f87e9a7c9f91",
          "sha1": "32696e0871fa8c2e0b4fd25ccd0e1e3c18b49537",
          "md5": "be1389bc0edaa28b443076a5b02ac912"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "javax.servlet",
          "module": "javax.servlet-api",
          "version": {
            "requires": "4.0.1"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-test",
          "version": {
            "requires": "5.3.31"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy",
          "version": {
            "requires": "3.0.11"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            },
            {
              "group": "*",
              "module": "commons-cli"
            },
            {
              "group": "*",
              "module": "ant"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "jcl-over-slf4j",
          "version": {
            "requires": "1.7.36"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-web",
          "version": {
            "requires": "6.1.2"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-plugin-controllers",
          "version": {
            "requires": "6.1.2"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.13.2"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "grails-plugin-url-mappings-6.1.2.jar",
          "url": "grails-plugin-url-mappings-6.1.2.jar",
          "size": 22232,
          "sha512": "6b50dc61fa90e97a5198b51d15726fbce5c57cc1f6cb02e8c4eec1c521e44d0b4d8fa1a5a16a1bc0e270833c34b737305d05dfacc2ba4641f79e766a160db15e",
          "sha256": "9b22279f9040fb887d97ceba3287bb0c66a53f887a68e9e91b30f87e9a7c9f91",
          "sha1": "32696e0871fa8c2e0b4fd25ccd0e1e3c18b49537",
          "md5": "be1389bc0edaa28b443076a5b02ac912"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "grails-plugin-url-mappings-6.1.2-javadoc.jar",
          "url": "grails-plugin-url-mappings-6.1.2-javadoc.jar",
          "size": 308337,
          "sha512": "3690f2c1cc6936cbd2e8b98f8abd0612b6c213e45072257f8979a8ac00897c3c6bb447dedd9fe3916ae9a4129198504fd89652a66278b3da5553b98596812fcb",
          "sha256": "169cb7de103280d33cba42c80dc3fe28dddd2205de6b78649636e18951efbc80",
          "sha1": "39dc41165c5221dc44ef8e913a4f84c3538f0619",
          "md5": "56f34bb248e525aef478eb67445b680e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "grails-plugin-url-mappings-6.1.2-sources.jar",
          "url": "grails-plugin-url-mappings-6.1.2-sources.jar",
          "size": 4437,
          "sha512": "c4d55444f33b53ca7971c880c3244171e56f721615aa5134700791a249a678a7a8e945d41279ed1de9b6ce8e144520910d726b13d9f3b76542e24f667cffc41e",
          "sha256": "8a596c2f599ef34aafbc75954e8759c1f63ffb095c0f1c4ccef4dded129ba9b9",
          "sha1": "6ff595118a567969a70b547367955f8c236d7a28",
          "md5": "c7b931c9ba2bb0af86dbc645e69ab453"
        }
      ]
    }
  ]
}
