{
  "formatVersion": "1.1",
  "component": {
    "group": "io.micronaut.r2dbc",
    "module": "micronaut-r2dbc-bom",
    "version": "4.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.testcontainers",
          "module": "testcontainers-bom",
          "version": {
            "requires": "1.17.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "dependencyConstraints": [
        {
          "group": "io.r2dbc",
          "module": "r2dbc-h2",
          "version": {
            "requires": "0.8.5.RELEASE"
          }
        },
        {
          "group": "org.mariadb",
          "module": "r2dbc-mariadb",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "io.r2dbc",
          "module": "r2dbc-mssql",
          "version": {
            "requires": "0.9.0.RELEASE"
          }
        },
        {
          "group": "dev.miku",
          "module": "r2dbc-mysql",
          "version": {
            "requires": "0.8.2.RELEASE"
          }
        },
        {
          "group": "com.oracle.database.r2dbc",
          "module": "oracle-r2dbc",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.r2dbc",
          "module": "r2dbc-pool",
          "version": {
            "requires": "0.9.2.RELEASE"
          }
        },
        {
          "group": "org.postgresql",
          "module": "r2dbc-postgresql",
          "version": {
            "requires": "0.9.2.RELEASE"
          }
        },
        {
          "group": "io.r2dbc",
          "module": "r2dbc-spi",
          "version": {
            "requires": "1.0.0.RELEASE"
          }
        },
        {
          "group": "io.micronaut.r2dbc",
          "module": "micronaut-r2dbc-core",
          "version": {
            "requires": "4.0.0"
          }
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.testcontainers",
          "module": "testcontainers-bom",
          "version": {
            "requires": "1.17.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "dependencyConstraints": [
        {
          "group": "io.r2dbc",
          "module": "r2dbc-h2",
          "version": {
            "requires": "0.8.5.RELEASE"
          }
        },
        {
          "group": "org.mariadb",
          "module": "r2dbc-mariadb",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "io.r2dbc",
          "module": "r2dbc-mssql",
          "version": {
            "requires": "0.9.0.RELEASE"
          }
        },
        {
          "group": "dev.miku",
          "module": "r2dbc-mysql",
          "version": {
            "requires": "0.8.2.RELEASE"
          }
        },
        {
          "group": "com.oracle.database.r2dbc",
          "module": "oracle-r2dbc",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.r2dbc",
          "module": "r2dbc-pool",
          "version": {
            "requires": "0.9.2.RELEASE"
          }
        },
        {
          "group": "org.postgresql",
          "module": "r2dbc-postgresql",
          "version": {
            "requires": "0.9.2.RELEASE"
          }
        },
        {
          "group": "io.r2dbc",
          "module": "r2dbc-spi",
          "version": {
            "requires": "1.0.0.RELEASE"
          }
        },
        {
          "group": "io.micronaut.r2dbc",
          "module": "micronaut-r2dbc-core",
          "version": {
            "requires": "4.0.0"
          }
        }
      ]
    },
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "micronaut-r2dbc-bom-4.0.0.toml",
          "url": "micronaut-r2dbc-bom-4.0.0.toml",
          "size": 1380,
          "sha512": "3b9cbce40a2717e6a52aebfbcf22160906346f745393a3f9a67700d06f4cafdfdc84fd871d4373efecd0641c72e42c844a291e6cd39614ec95f26392006ca963",
          "sha256": "4b2b413fcd73e049465598f124f237015de72ba4b6100eac5d145ab9bb6b6436",
          "sha1": "c73b2d7b0798c99c1c779639360ccb07ba0f58f1",
          "md5": "23cec13b49bbfad9f4190dc37db6d8fe"
        }
      ]
    }
  ]
}
