{
  "formatVersion": "1.1",
  "component": {
    "group": "org.grails",
    "module": "grails-web-common",
    "version": "6.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "javax.servlet",
          "module": "javax.servlet-api",
          "version": {
            "requires": "4.0.1"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-test",
          "version": {
            "requires": "5.3.31"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy",
          "version": {
            "requires": "3.0.11"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            },
            {
              "group": "*",
              "module": "commons-cli"
            },
            {
              "group": "*",
              "module": "ant"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "jcl-over-slf4j",
          "version": {
            "requires": "1.7.36"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-core",
          "version": {
            "requires": "6.1.2"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            },
            {
              "group": "org.grails",
              "module": "grails-spring"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-databinding",
          "version": {
            "requires": "6.1.2"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-encoder",
          "version": {
            "requires": "6.1.2"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-gsp",
          "version": {
            "requires": "6.1.3"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            },
            {
              "group": "org.grails",
              "module": "grails-encoder"
            },
            {
              "group": "org.grails",
              "module": "grails-core"
            }
          ]
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy-templates",
          "version": {
            "requires": "3.0.11"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-webmvc",
          "version": {
            "requires": "5.3.31"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-context-support",
          "version": {
            "requires": "5.3.31"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "grails-web-common-6.1.2.jar",
          "url": "grails-web-common-6.1.2.jar",
          "size": 182637,
          "sha512": "70f9d69c3482a5c6544cabe5538c8a247368514f42c266c5b36ea3dc128ab630793a96a315a6d39f600d6c6364b8b91946225c5c7731fde39c45c32c19914150",
          "sha256": "81e806c2a61f8c82da5f0045a471bab4328fe0b3d8b90c5902eb4fe6ad32d618",
          "sha1": "0eba63311f413239c81d9053da1fe145587a8635",
          "md5": "962097161f87b2461f7acc16339dc5dc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.ben-manes.caffeine",
          "module": "caffeine",
          "version": {
            "requires": "2.9.3"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "javax.servlet",
          "module": "javax.servlet-api",
          "version": {
            "requires": "4.0.1"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-test",
          "version": {
            "requires": "5.3.31"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy",
          "version": {
            "requires": "3.0.11"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            },
            {
              "group": "*",
              "module": "commons-cli"
            },
            {
              "group": "*",
              "module": "ant"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "jcl-over-slf4j",
          "version": {
            "requires": "1.7.36"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-core",
          "version": {
            "requires": "6.1.2"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            },
            {
              "group": "org.grails",
              "module": "grails-spring"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-databinding",
          "version": {
            "requires": "6.1.2"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-encoder",
          "version": {
            "requires": "6.1.2"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-gsp",
          "version": {
            "requires": "6.1.3"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            },
            {
              "group": "org.grails",
              "module": "grails-encoder"
            },
            {
              "group": "org.grails",
              "module": "grails-core"
            }
          ]
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy-templates",
          "version": {
            "requires": "3.0.11"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-webmvc",
          "version": {
            "requires": "5.3.31"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-context-support",
          "version": {
            "requires": "5.3.31"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "grails-web-common-6.1.2.jar",
          "url": "grails-web-common-6.1.2.jar",
          "size": 182637,
          "sha512": "70f9d69c3482a5c6544cabe5538c8a247368514f42c266c5b36ea3dc128ab630793a96a315a6d39f600d6c6364b8b91946225c5c7731fde39c45c32c19914150",
          "sha256": "81e806c2a61f8c82da5f0045a471bab4328fe0b3d8b90c5902eb4fe6ad32d618",
          "sha1": "0eba63311f413239c81d9053da1fe145587a8635",
          "md5": "962097161f87b2461f7acc16339dc5dc"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "grails-web-common-6.1.2-javadoc.jar",
          "url": "grails-web-common-6.1.2-javadoc.jar",
          "size": 639488,
          "sha512": "cef24541b1b84b2701ebf0ace4af54bb46a8af560b44bdd087e508d610ab66f3c6aa2f5b9e267ae5c751e2d8217f69ca0e0b42c79c0b249aa2d231e03757e75c",
          "sha256": "4342ec4b5f32fee5636da35294b8d2470e107797e9dea5255f2712f65fc955fd",
          "sha1": "93af4f5075f4339296d808bf320120e5a5f70a45",
          "md5": "57710f48cbff14cd0c96b0fb4eb75a39"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "grails-web-common-6.1.2-sources.jar",
          "url": "grails-web-common-6.1.2-sources.jar",
          "size": 128631,
          "sha512": "8bca49495f7204df975d5a65bfd686ae7349b78486c0b17622421e928624c020010cf25ffd554b38e3d29f12354a2c7ba32ed7747d1f7ea38f02273d47acec36",
          "sha256": "af026b67391496a73c71e3f3b4a44409cc5051eba66448645c03992081c41b3f",
          "sha1": "09eb55b798adf41df59eaac7ff2f77c5732d3316",
          "md5": "588913d9283ec1c22219b215139a0d78"
        }
      ]
    }
  ]
}
