{
  "formatVersion": "1.1",
  "component": {
    "group": "io.micronaut.views",
    "module": "micronaut-views-bom",
    "version": "3.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "java-api"
      },
      "dependencyConstraints": [
        {
          "group": "org.freemarker",
          "module": "freemarker",
          "version": {
            "requires": "2.3.31"
          }
        },
        {
          "group": "com.github.jknack",
          "module": "handlebars",
          "version": {
            "requires": "4.3.1"
          }
        },
        {
          "group": "gg.jte",
          "module": "jte",
          "version": {
            "requires": "2.2.4"
          }
        },
        {
          "group": "gg.jte",
          "module": "jte-kotlin",
          "version": {
            "requires": "2.2.4"
          }
        },
        {
          "group": "com.fizzed",
          "module": "rocker-runtime",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.google.template",
          "module": "soy",
          "version": {
            "requires": "2022-03-02"
          }
        },
        {
          "group": "org.thymeleaf",
          "module": "thymeleaf",
          "version": {
            "requires": "3.1.1.RELEASE"
          }
        },
        {
          "group": "org.apache.velocity",
          "module": "velocity-engine-core",
          "version": {
            "requires": "2.3"
          }
        },
        {
          "group": "io.micronaut.views",
          "module": "micronaut-views-core",
          "version": {
            "requires": "3.8.0"
          }
        },
        {
          "group": "io.micronaut.views",
          "module": "micronaut-views-freemarker",
          "version": {
            "requires": "3.8.0"
          }
        },
        {
          "group": "io.micronaut.views",
          "module": "micronaut-views-handlebars",
          "version": {
            "requires": "3.8.0"
          }
        },
        {
          "group": "io.micronaut.views",
          "module": "micronaut-views-jte",
          "version": {
            "requires": "3.8.0"
          }
        },
        {
          "group": "io.micronaut.views",
          "module": "micronaut-views-pebble",
          "version": {
            "requires": "3.8.0"
          }
        },
        {
          "group": "io.micronaut.views",
          "module": "micronaut-views-rocker",
          "version": {
            "requires": "3.8.0"
          }
        },
        {
          "group": "io.micronaut.views",
          "module": "micronaut-views-soy",
          "version": {
            "requires": "3.8.0"
          }
        },
        {
          "group": "io.micronaut.views",
          "module": "micronaut-views-thymeleaf",
          "version": {
            "requires": "3.8.0"
          }
        },
        {
          "group": "io.micronaut.views",
          "module": "micronaut-views-velocity",
          "version": {
            "requires": "3.8.0"
          }
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "org.freemarker",
          "module": "freemarker",
          "version": {
            "requires": "2.3.31"
          }
        },
        {
          "group": "com.github.jknack",
          "module": "handlebars",
          "version": {
            "requires": "4.3.1"
          }
        },
        {
          "group": "gg.jte",
          "module": "jte",
          "version": {
            "requires": "2.2.4"
          }
        },
        {
          "group": "gg.jte",
          "module": "jte-kotlin",
          "version": {
            "requires": "2.2.4"
          }
        },
        {
          "group": "com.fizzed",
          "module": "rocker-runtime",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.google.template",
          "module": "soy",
          "version": {
            "requires": "2022-03-02"
          }
        },
        {
          "group": "org.thymeleaf",
          "module": "thymeleaf",
          "version": {
            "requires": "3.1.1.RELEASE"
          }
        },
        {
          "group": "org.apache.velocity",
          "module": "velocity-engine-core",
          "version": {
            "requires": "2.3"
          }
        },
        {
          "group": "io.micronaut.views",
          "module": "micronaut-views-core",
          "version": {
            "requires": "3.8.0"
          }
        },
        {
          "group": "io.micronaut.views",
          "module": "micronaut-views-freemarker",
          "version": {
            "requires": "3.8.0"
          }
        },
        {
          "group": "io.micronaut.views",
          "module": "micronaut-views-handlebars",
          "version": {
            "requires": "3.8.0"
          }
        },
        {
          "group": "io.micronaut.views",
          "module": "micronaut-views-jte",
          "version": {
            "requires": "3.8.0"
          }
        },
        {
          "group": "io.micronaut.views",
          "module": "micronaut-views-pebble",
          "version": {
            "requires": "3.8.0"
          }
        },
        {
          "group": "io.micronaut.views",
          "module": "micronaut-views-rocker",
          "version": {
            "requires": "3.8.0"
          }
        },
        {
          "group": "io.micronaut.views",
          "module": "micronaut-views-soy",
          "version": {
            "requires": "3.8.0"
          }
        },
        {
          "group": "io.micronaut.views",
          "module": "micronaut-views-thymeleaf",
          "version": {
            "requires": "3.8.0"
          }
        },
        {
          "group": "io.micronaut.views",
          "module": "micronaut-views-velocity",
          "version": {
            "requires": "3.8.0"
          }
        }
      ]
    },
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "micronaut-views-bom-3.8.0.toml",
          "url": "micronaut-views-bom-3.8.0.toml",
          "size": 2226,
          "sha512": "ec4ea8f02f56e2011544b8a99ce35e4e3db18203ff39475263faada1d4077b40a0f6a1d2bf633e1fe5dbe6c2a9d121c2d7194a0794468dba33d6b35cb96bd3f4",
          "sha256": "70ffa02eefd234e24f940af482278e99947703a331bb3e1fa7123edcf048a67c",
          "sha1": "1ae1c3c502fdab3a1f993d4e05f0fbeca65576a7",
          "md5": "c7eada44a084922ebe5886f27b8640ba"
        }
      ]
    }
  ]
}
