{
  "formatVersion": "1.1",
  "component": {
    "group": "org.grails",
    "module": "grails-shell",
    "version": "6.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.codehaus.groovy",
          "module": "groovy",
          "version": {
            "requires": "3.0.11"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            },
            {
              "group": "*",
              "module": "commons-cli"
            },
            {
              "group": "*",
              "module": "ant"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "jcl-over-slf4j",
          "version": {
            "requires": "1.7.36"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-bootstrap",
          "version": {
            "requires": "6.1.2"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-gradle-model",
          "version": {
            "requires": "6.1.2"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.apache.ant",
          "module": "ant",
          "version": {
            "requires": "1.10.14"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy-ant",
          "version": {
            "requires": "3.0.11"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy-json",
          "version": {
            "requires": "3.0.11"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy-jmx",
          "version": {
            "requires": "3.0.11"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.fusesource.jansi",
          "module": "jansi",
          "version": {
            "requires": "1.18"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "jline",
          "module": "jline",
          "version": {
            "requires": "2.14.6"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.gradle",
          "module": "gradle-tooling-api",
          "version": {
            "requires": "7.3-20210825160000+0000"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-cli",
          "version": {
            "requires": "2.7.18"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            },
            {
              "group": "org.codehaus.groovy",
              "module": "groovy"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "grails-shell-6.1.2.jar",
          "url": "grails-shell-6.1.2.jar",
          "size": 487209,
          "sha512": "ad0598b4653616404f51c4a55b0504bd2e6ac87281e1e465537f1cbec20da7804198e18d773674106aa00b3b394611c818ddd7416035efa2df6833dbcd136720",
          "sha256": "ab16b53db5c1de6a7b1e231a1e9f77fc92eef6eadcb48f9e050ee30eedc5c155",
          "sha1": "6d5681a807e5d0b4fd014edc43c99976e8aacd05",
          "md5": "48ff8daf699e36e50a1d93a0206a62c2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.maven",
          "module": "maven-resolver-provider",
          "version": {
            "requires": "3.9.6"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            },
            {
              "group": "com.google.guava",
              "module": "guava"
            }
          ]
        },
        {
          "group": "org.apache.maven.resolver",
          "module": "maven-resolver-connector-basic",
          "version": {
            "requires": "1.9.18"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.apache.maven.resolver",
          "module": "maven-resolver-impl",
          "version": {
            "requires": "1.9.18"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.apache.maven.resolver",
          "module": "maven-resolver-transport-file",
          "version": {
            "requires": "1.9.18"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.apache.maven.resolver",
          "module": "maven-resolver-transport-http",
          "version": {
            "requires": "1.9.18"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            },
            {
              "group": "org.slf4j",
              "module": "jcl-over-slf4j"
            },
            {
              "group": "commons-codec",
              "module": "commons-codec"
            }
          ]
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.16.0"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy",
          "version": {
            "requires": "3.0.11"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            },
            {
              "group": "*",
              "module": "commons-cli"
            },
            {
              "group": "*",
              "module": "ant"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "jcl-over-slf4j",
          "version": {
            "requires": "1.7.36"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-bootstrap",
          "version": {
            "requires": "6.1.2"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-gradle-model",
          "version": {
            "requires": "6.1.2"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.apache.ant",
          "module": "ant",
          "version": {
            "requires": "1.10.14"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy-ant",
          "version": {
            "requires": "3.0.11"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy-json",
          "version": {
            "requires": "3.0.11"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy-jmx",
          "version": {
            "requires": "3.0.11"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.fusesource.jansi",
          "module": "jansi",
          "version": {
            "requires": "1.18"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "jline",
          "module": "jline",
          "version": {
            "requires": "2.14.6"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.gradle",
          "module": "gradle-tooling-api",
          "version": {
            "requires": "7.3-20210825160000+0000"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-cli",
          "version": {
            "requires": "2.7.18"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            },
            {
              "group": "org.codehaus.groovy",
              "module": "groovy"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-simple",
          "version": {
            "requires": "1.7.36"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.codehaus.plexus",
          "module": "plexus-component-api",
          "version": {
            "requires": "1.0-alpha-33"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "grails-shell-6.1.2.jar",
          "url": "grails-shell-6.1.2.jar",
          "size": 487209,
          "sha512": "ad0598b4653616404f51c4a55b0504bd2e6ac87281e1e465537f1cbec20da7804198e18d773674106aa00b3b394611c818ddd7416035efa2df6833dbcd136720",
          "sha256": "ab16b53db5c1de6a7b1e231a1e9f77fc92eef6eadcb48f9e050ee30eedc5c155",
          "sha1": "6d5681a807e5d0b4fd014edc43c99976e8aacd05",
          "md5": "48ff8daf699e36e50a1d93a0206a62c2"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "grails-shell-6.1.2-javadoc.jar",
          "url": "grails-shell-6.1.2-javadoc.jar",
          "size": 350411,
          "sha512": "1af42e0fcaafd6c2c7211afd58fcb237d87cb1a15b8540a06d757c813d94b41db658e151d50209f4566393be4546e00999abb68c6a32aa43e25e89b431c5e374",
          "sha256": "1c853b7d395e10eafc183e0d7818edd6e2b4e0dbb09eeec65a1e057af3dbe6e0",
          "sha1": "c75c09a58f02655247ea05ae7e5b879f1b1c106f",
          "md5": "f6aafd5669cc64a952118af82d9b26f8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "grails-shell-6.1.2-sources.jar",
          "url": "grails-shell-6.1.2-sources.jar",
          "size": 130691,
          "sha512": "91b191b7c3e4a660cf84565d4eeb5378b0178323926a1c83f5b47134adbb6f3d2c1a2e7c190e6e958f906ed94fb4f802129439716b5738a9414961acd577d5f6",
          "sha256": "7806739dad22161669782006485281eea7f8a4a6e57f651af146996ba35184ff",
          "sha1": "4b6b27110029f560e374fa19b9470579bfcae118",
          "md5": "59ba722519aa9bec130763dda826ae27"
        }
      ]
    }
  ]
}
