{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-test",
    "version": "5.3.34",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.34"
          },
          "excludes": [
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            },
            {
              "group": "xmlpull",
              "module": "xmlpull"
            },
            {
              "group": "org.slf4j",
              "module": "jcl-over-slf4j"
            },
            {
              "group": "org.hamcrest",
              "module": "hamcrest-core"
            },
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-test-5.3.34.jar",
          "url": "spring-test-5.3.34.jar",
          "size": 792399,
          "sha512": "20f6164fa8a4947b474b4c6bce6e5becae11334e940388fa0bf0edbf9146a30e8039575fc82aaa5c9187aa61048856a58d89fdce042429a76a32d46d95968b12",
          "sha256": "51033eb1f525a070ada6f539624df465d20261aa21bffd2cba0018180c616441",
          "sha1": "a26a8ae7403e6ef3fa233b4d6bc15e2661e8b0f2",
          "md5": "b6d1bab5c646bd9be13be3b0ad6319f2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.34"
          },
          "excludes": [
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            },
            {
              "group": "xmlpull",
              "module": "xmlpull"
            },
            {
              "group": "org.slf4j",
              "module": "jcl-over-slf4j"
            },
            {
              "group": "org.hamcrest",
              "module": "hamcrest-core"
            },
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-test-5.3.34.jar",
          "url": "spring-test-5.3.34.jar",
          "size": 792399,
          "sha512": "20f6164fa8a4947b474b4c6bce6e5becae11334e940388fa0bf0edbf9146a30e8039575fc82aaa5c9187aa61048856a58d89fdce042429a76a32d46d95968b12",
          "sha256": "51033eb1f525a070ada6f539624df465d20261aa21bffd2cba0018180c616441",
          "sha1": "a26a8ae7403e6ef3fa233b4d6bc15e2661e8b0f2",
          "md5": "b6d1bab5c646bd9be13be3b0ad6319f2"
        }
      ]
    }
  ]
}
