{
  "formatVersion": "1.1",
  "component": {
    "group": "io.micronaut.gcp",
    "module": "micronaut-gcp-bom",
    "version": "4.11.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "java-api"
      },
      "dependencyConstraints": [
        {
          "group": "com.google.cloud.functions",
          "module": "functions-framework-api",
          "version": {
            "requires": "1.0.4"
          }
        },
        {
          "group": "com.google.auth",
          "module": "google-auth-library-oauth2-http",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "com.google.cloud",
          "module": "google-cloud-core",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "com.google.cloud",
          "module": "google-cloud-pubsub",
          "version": {
            "requires": "1.123.17"
          }
        },
        {
          "group": "com.google.cloud",
          "module": "google-cloud-secretmanager",
          "version": {
            "requires": "2.18.0"
          }
        },
        {
          "group": "com.google.cloud",
          "module": "google-cloudevent-types",
          "version": {
            "requires": "0.3.0"
          }
        },
        {
          "group": "com.google.cloud",
          "module": "native-image-support",
          "version": {
            "requires": "0.14.1"
          }
        },
        {
          "group": "io.micronaut.gcp",
          "module": "micronaut-gcp-common",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "io.micronaut.gcp",
          "module": "micronaut-gcp-function",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "io.micronaut.gcp",
          "module": "micronaut-gcp-function-cloudevents",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "io.micronaut.gcp",
          "module": "micronaut-gcp-function-http",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "io.micronaut.gcp",
          "module": "micronaut-gcp-function-http-test",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "io.micronaut.gcp",
          "module": "micronaut-gcp-http-client",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "io.micronaut.gcp",
          "module": "micronaut-gcp-logging",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "io.micronaut.gcp",
          "module": "micronaut-gcp-pubsub",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "io.micronaut.gcp",
          "module": "micronaut-gcp-secret-manager",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "io.micronaut.gcp",
          "module": "micronaut-gcp-serde-cloudevents",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "io.micronaut.gcp",
          "module": "micronaut-gcp-tracing",
          "version": {
            "requires": "4.11.0"
          }
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "com.google.cloud.functions",
          "module": "functions-framework-api",
          "version": {
            "requires": "1.0.4"
          }
        },
        {
          "group": "com.google.auth",
          "module": "google-auth-library-oauth2-http",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "com.google.cloud",
          "module": "google-cloud-core",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "com.google.cloud",
          "module": "google-cloud-pubsub",
          "version": {
            "requires": "1.123.17"
          }
        },
        {
          "group": "com.google.cloud",
          "module": "google-cloud-secretmanager",
          "version": {
            "requires": "2.18.0"
          }
        },
        {
          "group": "com.google.cloud",
          "module": "google-cloudevent-types",
          "version": {
            "requires": "0.3.0"
          }
        },
        {
          "group": "com.google.cloud",
          "module": "native-image-support",
          "version": {
            "requires": "0.14.1"
          }
        },
        {
          "group": "io.micronaut.gcp",
          "module": "micronaut-gcp-common",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "io.micronaut.gcp",
          "module": "micronaut-gcp-function",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "io.micronaut.gcp",
          "module": "micronaut-gcp-function-cloudevents",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "io.micronaut.gcp",
          "module": "micronaut-gcp-function-http",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "io.micronaut.gcp",
          "module": "micronaut-gcp-function-http-test",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "io.micronaut.gcp",
          "module": "micronaut-gcp-http-client",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "io.micronaut.gcp",
          "module": "micronaut-gcp-logging",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "io.micronaut.gcp",
          "module": "micronaut-gcp-pubsub",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "io.micronaut.gcp",
          "module": "micronaut-gcp-secret-manager",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "io.micronaut.gcp",
          "module": "micronaut-gcp-serde-cloudevents",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "io.micronaut.gcp",
          "module": "micronaut-gcp-tracing",
          "version": {
            "requires": "4.11.0"
          }
        }
      ]
    },
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "micronaut-gcp-bom-4.11.0.toml",
          "url": "micronaut-gcp-bom-4.11.0.toml",
          "size": 2875,
          "sha512": "2844aaf0a985383d26a25f51332e6fd0bf42efbef9763107987515976ab106f541c8238377dfdc8f2fa2dd6d7db90d1220276319e83386c7e76ccae9ddad69d3",
          "sha256": "811fcf556e17455f6408e00c921b9a2dfc3eae69e9d27ce2a89e6838d722599a",
          "sha1": "43e3fef552b1d6958308c255b53097bd0ba2a8d3",
          "md5": "53037315d35de0749bdb6ce28e49969a"
        }
      ]
    }
  ]
}
