{
  "formatVersion": "1.1",
  "component": {
    "group": "io.micronaut.chatbots",
    "module": "micronaut-chatbots-bom",
    "version": "1.0.0-M1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "java-api"
      },
      "dependencyConstraints": [
        {
          "group": "io.micronaut.chatbots",
          "module": "micronaut-chatbots-basecamp-api",
          "version": {
            "requires": "1.0.0-M1"
          }
        },
        {
          "group": "io.micronaut.chatbots",
          "module": "micronaut-chatbots-basecamp-azure-function",
          "version": {
            "requires": "1.0.0-M1"
          }
        },
        {
          "group": "io.micronaut.chatbots",
          "module": "micronaut-chatbots-basecamp-core",
          "version": {
            "requires": "1.0.0-M1"
          }
        },
        {
          "group": "io.micronaut.chatbots",
          "module": "micronaut-chatbots-basecamp-gcp-function",
          "version": {
            "requires": "1.0.0-M1"
          }
        },
        {
          "group": "io.micronaut.chatbots",
          "module": "micronaut-chatbots-basecamp-http",
          "version": {
            "requires": "1.0.0-M1"
          }
        },
        {
          "group": "io.micronaut.chatbots",
          "module": "micronaut-chatbots-basecamp-lambda",
          "version": {
            "requires": "1.0.0-M1"
          }
        },
        {
          "group": "io.micronaut.chatbots",
          "module": "micronaut-chatbots-core",
          "version": {
            "requires": "1.0.0-M1"
          }
        },
        {
          "group": "io.micronaut.chatbots",
          "module": "micronaut-chatbots-google-api",
          "version": {
            "requires": "1.0.0-M1"
          }
        },
        {
          "group": "io.micronaut.chatbots",
          "module": "micronaut-chatbots-http",
          "version": {
            "requires": "1.0.0-M1"
          }
        },
        {
          "group": "io.micronaut.chatbots",
          "module": "micronaut-chatbots-lambda",
          "version": {
            "requires": "1.0.0-M1"
          }
        },
        {
          "group": "io.micronaut.chatbots",
          "module": "micronaut-chatbots-telegram-api",
          "version": {
            "requires": "1.0.0-M1"
          }
        },
        {
          "group": "io.micronaut.chatbots",
          "module": "micronaut-chatbots-telegram-azure-function",
          "version": {
            "requires": "1.0.0-M1"
          }
        },
        {
          "group": "io.micronaut.chatbots",
          "module": "micronaut-chatbots-telegram-core",
          "version": {
            "requires": "1.0.0-M1"
          }
        },
        {
          "group": "io.micronaut.chatbots",
          "module": "micronaut-chatbots-telegram-gcp-function",
          "version": {
            "requires": "1.0.0-M1"
          }
        },
        {
          "group": "io.micronaut.chatbots",
          "module": "micronaut-chatbots-telegram-http",
          "version": {
            "requires": "1.0.0-M1"
          }
        },
        {
          "group": "io.micronaut.chatbots",
          "module": "micronaut-chatbots-telegram-lambda",
          "version": {
            "requires": "1.0.0-M1"
          }
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "io.micronaut.chatbots",
          "module": "micronaut-chatbots-basecamp-api",
          "version": {
            "requires": "1.0.0-M1"
          }
        },
        {
          "group": "io.micronaut.chatbots",
          "module": "micronaut-chatbots-basecamp-azure-function",
          "version": {
            "requires": "1.0.0-M1"
          }
        },
        {
          "group": "io.micronaut.chatbots",
          "module": "micronaut-chatbots-basecamp-core",
          "version": {
            "requires": "1.0.0-M1"
          }
        },
        {
          "group": "io.micronaut.chatbots",
          "module": "micronaut-chatbots-basecamp-gcp-function",
          "version": {
            "requires": "1.0.0-M1"
          }
        },
        {
          "group": "io.micronaut.chatbots",
          "module": "micronaut-chatbots-basecamp-http",
          "version": {
            "requires": "1.0.0-M1"
          }
        },
        {
          "group": "io.micronaut.chatbots",
          "module": "micronaut-chatbots-basecamp-lambda",
          "version": {
            "requires": "1.0.0-M1"
          }
        },
        {
          "group": "io.micronaut.chatbots",
          "module": "micronaut-chatbots-core",
          "version": {
            "requires": "1.0.0-M1"
          }
        },
        {
          "group": "io.micronaut.chatbots",
          "module": "micronaut-chatbots-google-api",
          "version": {
            "requires": "1.0.0-M1"
          }
        },
        {
          "group": "io.micronaut.chatbots",
          "module": "micronaut-chatbots-http",
          "version": {
            "requires": "1.0.0-M1"
          }
        },
        {
          "group": "io.micronaut.chatbots",
          "module": "micronaut-chatbots-lambda",
          "version": {
            "requires": "1.0.0-M1"
          }
        },
        {
          "group": "io.micronaut.chatbots",
          "module": "micronaut-chatbots-telegram-api",
          "version": {
            "requires": "1.0.0-M1"
          }
        },
        {
          "group": "io.micronaut.chatbots",
          "module": "micronaut-chatbots-telegram-azure-function",
          "version": {
            "requires": "1.0.0-M1"
          }
        },
        {
          "group": "io.micronaut.chatbots",
          "module": "micronaut-chatbots-telegram-core",
          "version": {
            "requires": "1.0.0-M1"
          }
        },
        {
          "group": "io.micronaut.chatbots",
          "module": "micronaut-chatbots-telegram-gcp-function",
          "version": {
            "requires": "1.0.0-M1"
          }
        },
        {
          "group": "io.micronaut.chatbots",
          "module": "micronaut-chatbots-telegram-http",
          "version": {
            "requires": "1.0.0-M1"
          }
        },
        {
          "group": "io.micronaut.chatbots",
          "module": "micronaut-chatbots-telegram-lambda",
          "version": {
            "requires": "1.0.0-M1"
          }
        }
      ]
    },
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "micronaut-chatbots-bom-1.0.0-M1.toml",
          "url": "micronaut-chatbots-bom-1.0.0-M1.toml",
          "size": 2711,
          "sha512": "b046cc00024c41a2f2ef252b960b4724392838154cf176cea58bea013b998e1de2acc74ef7785ef736bdd55d998175a32781f2ccf4c1b19379a052f235f356ce",
          "sha256": "dc833697d5e8fe4df14e7d92dd4ccd983d2e949c768794d9eed1e69f47ce98a7",
          "sha1": "da79ab01dd7987e617e7ca3b5a19503d0e3b982f",
          "md5": "c03ae4ef4d4a1e0bcc121875b39e6d89"
        }
      ]
    }
  ]
}
