{
  "formatVersion": "1.1",
  "component": {
    "group": "org.grails",
    "module": "grails-web",
    "version": "6.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "javax.servlet",
          "module": "javax.servlet-api",
          "version": {
            "requires": "4.0.1"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-test",
          "version": {
            "requires": "5.3.27"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy",
          "version": {
            "requires": "3.0.11"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            },
            {
              "group": "*",
              "module": "commons-cli"
            },
            {
              "group": "*",
              "module": "ant"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "jcl-over-slf4j",
          "version": {
            "requires": "1.7.36"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-web-common",
          "version": {
            "requires": "6.0.0"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-web-databinding",
          "version": {
            "requires": "6.0.0"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-web-fileupload",
          "version": {
            "requires": "6.0.0"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-web-url-mappings",
          "version": {
            "requires": "6.0.0"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-web-mvc",
          "version": {
            "requires": "6.0.0"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-web-gsp",
          "version": {
            "requires": "6.0.0"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            },
            {
              "group": "org.grails",
              "module": "grails-encoder"
            },
            {
              "group": "org.grails",
              "module": "grails-core"
            },
            {
              "group": "org.grails",
              "module": "grails-web-common"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-web-sitemesh",
          "version": {
            "requires": "6.0.0"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            },
            {
              "group": "org.grails",
              "module": "grails-encoder"
            },
            {
              "group": "org.grails",
              "module": "grails-core"
            },
            {
              "group": "org.grails",
              "module": "grails-web-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "grails-web-6.0.0.jar",
          "url": "grails-web-6.0.0.jar",
          "size": 23488,
          "sha512": "03a9ca9a4cc655578403e72a4d7d84633d48f9b553514fe9d2780974c66cda1814efc88441c384226f1e6d4c6ccd230f0d65c3f6fb31b4045fae99090fc38952",
          "sha256": "17fdc1df43742697ff20a655bbef14ab4af496fc2837678bdd924dfd8c95f8c3",
          "sha1": "25e2e03e4746ede3dced932ed17bcf05889737f8",
          "md5": "b460bf94cc97b4aecee1558b4bad8417"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "javax.servlet",
          "module": "javax.servlet-api",
          "version": {
            "requires": "4.0.1"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-test",
          "version": {
            "requires": "5.3.27"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy",
          "version": {
            "requires": "3.0.11"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            },
            {
              "group": "*",
              "module": "commons-cli"
            },
            {
              "group": "*",
              "module": "ant"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "jcl-over-slf4j",
          "version": {
            "requires": "1.7.36"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-web-common",
          "version": {
            "requires": "6.0.0"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-web-databinding",
          "version": {
            "requires": "6.0.0"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-web-fileupload",
          "version": {
            "requires": "6.0.0"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-web-url-mappings",
          "version": {
            "requires": "6.0.0"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-web-mvc",
          "version": {
            "requires": "6.0.0"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-web-gsp",
          "version": {
            "requires": "6.0.0"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            },
            {
              "group": "org.grails",
              "module": "grails-encoder"
            },
            {
              "group": "org.grails",
              "module": "grails-core"
            },
            {
              "group": "org.grails",
              "module": "grails-web-common"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-web-sitemesh",
          "version": {
            "requires": "6.0.0"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            },
            {
              "group": "org.grails",
              "module": "grails-encoder"
            },
            {
              "group": "org.grails",
              "module": "grails-core"
            },
            {
              "group": "org.grails",
              "module": "grails-web-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "grails-web-6.0.0.jar",
          "url": "grails-web-6.0.0.jar",
          "size": 23488,
          "sha512": "03a9ca9a4cc655578403e72a4d7d84633d48f9b553514fe9d2780974c66cda1814efc88441c384226f1e6d4c6ccd230f0d65c3f6fb31b4045fae99090fc38952",
          "sha256": "17fdc1df43742697ff20a655bbef14ab4af496fc2837678bdd924dfd8c95f8c3",
          "sha1": "25e2e03e4746ede3dced932ed17bcf05889737f8",
          "md5": "b460bf94cc97b4aecee1558b4bad8417"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "grails-web-6.0.0-javadoc.jar",
          "url": "grails-web-6.0.0-javadoc.jar",
          "size": 359993,
          "sha512": "4367a3de441b4ba4491c39cc5bec5ff18875be2f48cbf119feddd919c6eb4342cee83d56f9a7895b3cfe0099c33306e0e302e140702b79adc84dc186a19b8dd6",
          "sha256": "3c7c07306e38930337ca7e9a4876f6a69855c6312529327a712132e67ae2d970",
          "sha1": "26b3bf5c1f7e7cad019403b36dd0cc5c1c202d88",
          "md5": "2da859eadde8ccab40914e24d00b7648"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "grails-web-6.0.0-sources.jar",
          "url": "grails-web-6.0.0-sources.jar",
          "size": 16789,
          "sha512": "78c8c4bb690b0458d66f3de4cad512e8c99cd8627a582b61cf307204214a97c27699b093695e8e7b8a7b5a4d7150ba4f03763a5e1403ef4b234cfb2369e23f16",
          "sha256": "7aeb9f1a523ec9a7205957dfefc1e7bfcfb7edba4a64d1ece5246ec4e81612eb",
          "sha1": "4109a2726822c674bc9c841657d906911b21f5e1",
          "md5": "b42ee4e5c4301f16df51a9cd5fa96251"
        }
      ]
    }
  ]
}
