{
  "formatVersion": "1.1",
  "component": {
    "group": "io.micronaut.gcp",
    "module": "micronaut-gcp-bom",
    "version": "4.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "java-api"
      },
      "dependencyConstraints": [
        {
          "group": "com.google.cloud.functions",
          "module": "functions-framework-api",
          "version": {
            "requires": "1.0.4"
          }
        },
        {
          "group": "com.google.auth",
          "module": "google-auth-library-oauth2-http",
          "version": {
            "requires": "1.5.3"
          }
        },
        {
          "group": "com.google.cloud",
          "module": "google-cloud-core",
          "version": {
            "requires": "2.5.6"
          }
        },
        {
          "group": "com.google.cloud",
          "module": "google-cloud-pubsub",
          "version": {
            "requires": "1.116.0"
          }
        },
        {
          "group": "com.google.cloud",
          "module": "google-cloud-secretmanager",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "com.google.cloud",
          "module": "native-image-support",
          "version": {
            "requires": "0.12.11"
          }
        },
        {
          "group": "io.micronaut.gcp",
          "module": "micronaut-gcp-common",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "io.micronaut.gcp",
          "module": "micronaut-gcp-function",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "io.micronaut.gcp",
          "module": "micronaut-gcp-function-http",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "io.micronaut.gcp",
          "module": "micronaut-gcp-function-http-test",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "io.micronaut.gcp",
          "module": "micronaut-gcp-http-client",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "io.micronaut.gcp",
          "module": "micronaut-gcp-logging",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "io.micronaut.gcp",
          "module": "micronaut-gcp-pubsub",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "io.micronaut.gcp",
          "module": "micronaut-gcp-secret-manager",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "io.micronaut.gcp",
          "module": "micronaut-gcp-tracing",
          "version": {
            "requires": "4.2.1"
          }
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "com.google.cloud.functions",
          "module": "functions-framework-api",
          "version": {
            "requires": "1.0.4"
          }
        },
        {
          "group": "com.google.auth",
          "module": "google-auth-library-oauth2-http",
          "version": {
            "requires": "1.5.3"
          }
        },
        {
          "group": "com.google.cloud",
          "module": "google-cloud-core",
          "version": {
            "requires": "2.5.6"
          }
        },
        {
          "group": "com.google.cloud",
          "module": "google-cloud-pubsub",
          "version": {
            "requires": "1.116.0"
          }
        },
        {
          "group": "com.google.cloud",
          "module": "google-cloud-secretmanager",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "com.google.cloud",
          "module": "native-image-support",
          "version": {
            "requires": "0.12.11"
          }
        },
        {
          "group": "io.micronaut.gcp",
          "module": "micronaut-gcp-common",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "io.micronaut.gcp",
          "module": "micronaut-gcp-function",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "io.micronaut.gcp",
          "module": "micronaut-gcp-function-http",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "io.micronaut.gcp",
          "module": "micronaut-gcp-function-http-test",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "io.micronaut.gcp",
          "module": "micronaut-gcp-http-client",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "io.micronaut.gcp",
          "module": "micronaut-gcp-logging",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "io.micronaut.gcp",
          "module": "micronaut-gcp-pubsub",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "io.micronaut.gcp",
          "module": "micronaut-gcp-secret-manager",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "io.micronaut.gcp",
          "module": "micronaut-gcp-tracing",
          "version": {
            "requires": "4.2.1"
          }
        }
      ]
    },
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "micronaut-gcp-bom-4.2.1.toml",
          "url": "micronaut-gcp-bom-4.2.1.toml",
          "size": 2426,
          "sha512": "f29ef6c99f4faf6677ff97f2c8e7cc14dae017c53b6221f1722fffad6beb9833fa1958e99539f6bd942ea21d9db2ee74b8b86a4a6896914fd5832478508cb575",
          "sha256": "632b9ea3e079ae868a341a1a84336eb12b7b70a66e1249f69b9554b98db12e63",
          "sha1": "9d1ec07d36aeceae18a31007d552ea4a92f0ef66",
          "md5": "645f07310ee395adff2e6310e7f0792d"
        }
      ]
    }
  ]
}
