{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jodd",
    "module": "jodd-log",
    "version": "5.1.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4",
      "buildId": "kye6ez6gwvh3behforagjqfhyq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "[1.7,1.8)"
          }
        },
        {
          "group": "commons-logging",
          "module": "commons-logging",
          "version": {
            "requires": "[1.2,1.3)"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "[1.2,1.3)"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-api",
          "version": {
            "requires": "[2.8,2.9)"
          }
        }
      ],
      "files": [
        {
          "name": "jodd-log-5.1.5.jar",
          "url": "jodd-log-5.1.5.jar",
          "size": 20311,
          "sha512": "d94000fd594bcf8a75e5c887733e226efbd2ccba1055601cc452f28d24ae5698753375a16b49040004e55f132e16a1bf34c3e1c18b07d36a63f6497f353648ea",
          "sha256": "49d2d8d59c9e12c6b8475cd50bd8f821e1ec55085f400046fbc3a53a54449192",
          "sha1": "c86deb1dc93bbaf9db6ab086852a76b9372eb8a7",
          "md5": "e025fdbade24bc75acbd5d0f1fae9bb1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "[1.7,1.8)"
          }
        },
        {
          "group": "commons-logging",
          "module": "commons-logging",
          "version": {
            "requires": "[1.2,1.3)"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "[1.2,1.3)"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-api",
          "version": {
            "requires": "[2.8,2.9)"
          }
        }
      ],
      "files": [
        {
          "name": "jodd-log-5.1.5.jar",
          "url": "jodd-log-5.1.5.jar",
          "size": 20311,
          "sha512": "d94000fd594bcf8a75e5c887733e226efbd2ccba1055601cc452f28d24ae5698753375a16b49040004e55f132e16a1bf34c3e1c18b07d36a63f6497f353648ea",
          "sha256": "49d2d8d59c9e12c6b8475cd50bd8f821e1ec55085f400046fbc3a53a54449192",
          "sha1": "c86deb1dc93bbaf9db6ab086852a76b9372eb8a7",
          "md5": "e025fdbade24bc75acbd5d0f1fae9bb1"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "jodd-log-5.1.5-javadoc.jar",
          "url": "jodd-log-5.1.5-javadoc.jar",
          "size": 65393,
          "sha512": "7761c467602069ccae20907f99414d1e6a9be5a2001d9efe790d615b2fd76c98d9203da03511c44630d98f22727954a832e5e613ef634905bfc12b6aac3a07d4",
          "sha256": "9b4012d557e04429b1a709bc9cc8c0a50888dcc79c8e40684c945651f2bd649a",
          "sha1": "286af42a33f6281102938569e31a8cbf484ac7e5",
          "md5": "fc7b6f8075abc8ece442d95e04da1984"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "jodd-log-5.1.5-sources.jar",
          "url": "jodd-log-5.1.5-sources.jar",
          "size": 18145,
          "sha512": "bf1e02875dd9cabbad3b67c60160029af2afa956876f9164037878560e6a9c35f08990123b5d88440d361c15e00eeba4266e3bd6fed66460513dd673fdc0362c",
          "sha256": "1a362e58a19f067bc2e344d56e0ef32e1c63fa5e1c33a2e841dd3de560abc57b",
          "sha1": "f80c37d9a3d808892cf880923a1424ab44de745f",
          "md5": "7c12795cb79b7d9ac6d83c42e8743b23"
        }
      ]
    }
  ]
}
