{
  "formatVersion": "1.1",
  "component": {
    "group": "io.micronaut.serde",
    "module": "micronaut-serde-bom",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "java-api"
      },
      "dependencyConstraints": [
        {
          "group": "org.mongodb",
          "module": "bson",
          "version": {
            "requires": "4.6.0"
          }
        },
        {
          "group": "jakarta.json",
          "module": "jakarta.json-api",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "jakarta.json.bind",
          "module": "jakarta.json.bind-api",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "io.micronaut.serde",
          "module": "micronaut-serde-api",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "io.micronaut.serde",
          "module": "micronaut-serde-bson",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "io.micronaut.serde",
          "module": "micronaut-serde-jackson",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "io.micronaut.serde",
          "module": "micronaut-serde-jsonp",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "io.micronaut.serde",
          "module": "micronaut-serde-processor",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "io.micronaut.serde",
          "module": "micronaut-serde-support",
          "version": {
            "requires": "1.1.0"
          }
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "org.mongodb",
          "module": "bson",
          "version": {
            "requires": "4.6.0"
          }
        },
        {
          "group": "jakarta.json",
          "module": "jakarta.json-api",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "jakarta.json.bind",
          "module": "jakarta.json.bind-api",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "io.micronaut.serde",
          "module": "micronaut-serde-api",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "io.micronaut.serde",
          "module": "micronaut-serde-bson",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "io.micronaut.serde",
          "module": "micronaut-serde-jackson",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "io.micronaut.serde",
          "module": "micronaut-serde-jsonp",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "io.micronaut.serde",
          "module": "micronaut-serde-processor",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "io.micronaut.serde",
          "module": "micronaut-serde-support",
          "version": {
            "requires": "1.1.0"
          }
        }
      ]
    },
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "micronaut-serde-bom-1.1.0.toml",
          "url": "micronaut-serde-bom-1.1.0.toml",
          "size": 1397,
          "sha512": "de53b503ba7a254cdf8c2fbbb0d244a99d9bdb9e24b0b89999d656ca97415e887eaeb66e67503baa89646b473a186e3b186c7f3a3e951c44b7faca42975b63f4",
          "sha256": "d67e68a70cbe793dea24d1c8590a6428c8ded4788853514550f0b6c06055e63d",
          "sha1": "a8cfc7074decff2a5356128d2c53853af9494ad8",
          "md5": "8b205e5b8d6b3c58c897f85e54756945"
        }
      ]
    }
  ]
}
