{
  "formatVersion": "1.1",
  "component": {
    "group": "org.grails",
    "module": "grails-web",
    "version": "6.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "javax.servlet",
          "module": "javax.servlet-api",
          "version": {
            "requires": "4.0.1"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-test",
          "version": {
            "requires": "5.3.31"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy",
          "version": {
            "requires": "3.0.11"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            },
            {
              "group": "*",
              "module": "commons-cli"
            },
            {
              "group": "*",
              "module": "ant"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "jcl-over-slf4j",
          "version": {
            "requires": "1.7.36"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-web-common",
          "version": {
            "requires": "6.1.2"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-web-databinding",
          "version": {
            "requires": "6.1.2"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-web-fileupload",
          "version": {
            "requires": "6.1.2"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-web-url-mappings",
          "version": {
            "requires": "6.1.2"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-web-mvc",
          "version": {
            "requires": "6.1.2"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-web-gsp",
          "version": {
            "requires": "6.1.3"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            },
            {
              "group": "org.grails",
              "module": "grails-encoder"
            },
            {
              "group": "org.grails",
              "module": "grails-core"
            },
            {
              "group": "org.grails",
              "module": "grails-web-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "grails-web-6.1.2.jar",
          "url": "grails-web-6.1.2.jar",
          "size": 23489,
          "sha512": "2b041c00544c2f0db12d646785a2f66854e6e6d2672a19ebe7a73d75173cf39eb969ce3204595c4083a7912b2f5f4f5f3e356d475a41e7a601054dae51ca83b4",
          "sha256": "5a0ad6f6c7a901b86688122baf4200d2eea37351fc3f3ad33fecb28ebb7ad0bc",
          "sha1": "c2ba464b7ed3c578c288c165dbbd82fd11b185a1",
          "md5": "7e784ac811c46da1563ab08c21f4ef12"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "javax.servlet",
          "module": "javax.servlet-api",
          "version": {
            "requires": "4.0.1"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-test",
          "version": {
            "requires": "5.3.31"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy",
          "version": {
            "requires": "3.0.11"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            },
            {
              "group": "*",
              "module": "commons-cli"
            },
            {
              "group": "*",
              "module": "ant"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "jcl-over-slf4j",
          "version": {
            "requires": "1.7.36"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-web-common",
          "version": {
            "requires": "6.1.2"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-web-databinding",
          "version": {
            "requires": "6.1.2"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-web-fileupload",
          "version": {
            "requires": "6.1.2"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-web-url-mappings",
          "version": {
            "requires": "6.1.2"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-web-mvc",
          "version": {
            "requires": "6.1.2"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-web-gsp",
          "version": {
            "requires": "6.1.3"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            },
            {
              "group": "org.grails",
              "module": "grails-encoder"
            },
            {
              "group": "org.grails",
              "module": "grails-core"
            },
            {
              "group": "org.grails",
              "module": "grails-web-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "grails-web-6.1.2.jar",
          "url": "grails-web-6.1.2.jar",
          "size": 23489,
          "sha512": "2b041c00544c2f0db12d646785a2f66854e6e6d2672a19ebe7a73d75173cf39eb969ce3204595c4083a7912b2f5f4f5f3e356d475a41e7a601054dae51ca83b4",
          "sha256": "5a0ad6f6c7a901b86688122baf4200d2eea37351fc3f3ad33fecb28ebb7ad0bc",
          "sha1": "c2ba464b7ed3c578c288c165dbbd82fd11b185a1",
          "md5": "7e784ac811c46da1563ab08c21f4ef12"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "grails-web-6.1.2-javadoc.jar",
          "url": "grails-web-6.1.2-javadoc.jar",
          "size": 359966,
          "sha512": "3561ede14c13df5c726b9d65cc84fd7f23de8522c2fa03375caac4d64451f8c8d6056bc99946e29767dd38af31256e262a42a8bb9060262f26801029e3371adf",
          "sha256": "bbe9d5bdff3d4c1858534f4cf8ca6858d8d06b2f0783ce1adea312aaa4f4e761",
          "sha1": "e89f05900a26e769c003745ce8e7c54c450c9e99",
          "md5": "065ee9aa3e5854fe0b61356c005f39ee"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "grails-web-6.1.2-sources.jar",
          "url": "grails-web-6.1.2-sources.jar",
          "size": 16789,
          "sha512": "580840f1ae389e3eae596ab36c9ebba318d78df6aeb2eb3ec04f0db8f2aa75d9dec15cac3efe78243e50abede4a791f46fc23ad17eb72de3af8aa9120471e0cf",
          "sha256": "e6dabb658d85c7be719009f58b7462a2b3d11089f1beec592810dbf9d56b628b",
          "sha1": "7b0ef3adb624c6040c13b6d5e219b6523e79954c",
          "md5": "09dc7c9cb5efa904c8259984d30fccca"
        }
      ]
    }
  ]
}
