{
  "formatVersion": "1.1",
  "component": {
    "group": "io.micronaut.aws",
    "module": "micronaut-aws-bom",
    "version": "3.10.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.amazonaws",
          "module": "aws-java-sdk-bom",
          "version": {
            "requires": "1.12.414"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "software.amazon.awssdk",
          "module": "bom",
          "version": {
            "requires": "2.19.14"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "dependencyConstraints": [
        {
          "group": "com.amazon.alexa",
          "module": "ask-sdk",
          "version": {
            "requires": "2.44.0"
          }
        },
        {
          "group": "com.amazon.alexa",
          "module": "ask-sdk-core",
          "version": {
            "requires": "2.44.0"
          }
        },
        {
          "group": "com.amazon.alexa",
          "module": "ask-sdk-lambda-support",
          "version": {
            "requires": "2.44.0"
          }
        },
        {
          "group": "com.amazonaws",
          "module": "aws-java-sdk-core",
          "version": {
            "requires": "1.12.414"
          }
        },
        {
          "group": "com.amazonaws",
          "module": "aws-lambda-java-core",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "com.amazonaws",
          "module": "aws-lambda-java-events",
          "version": {
            "requires": "3.11.0"
          }
        },
        {
          "group": "com.amazonaws.serverless",
          "module": "aws-serverless-java-container-core",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "software.amazon.awssdk",
          "module": "secretsmanager",
          "version": {
            "requires": "2.19.14"
          }
        },
        {
          "group": "org.slf4j",
          "module": "jcl-over-slf4j",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "io.micronaut.aws",
          "module": "micronaut-aws-alexa",
          "version": {
            "requires": "3.10.10"
          }
        },
        {
          "group": "io.micronaut.aws",
          "module": "micronaut-aws-alexa-httpserver",
          "version": {
            "requires": "3.10.10"
          }
        },
        {
          "group": "io.micronaut.aws",
          "module": "micronaut-aws-apigateway",
          "version": {
            "requires": "3.10.10"
          }
        },
        {
          "group": "io.micronaut.aws",
          "module": "micronaut-aws-cdk",
          "version": {
            "requires": "3.10.10"
          }
        },
        {
          "group": "io.micronaut.aws",
          "module": "micronaut-aws-cloudwatch-logging",
          "version": {
            "requires": "3.10.10"
          }
        },
        {
          "group": "io.micronaut.aws",
          "module": "micronaut-aws-common",
          "version": {
            "requires": "3.10.10"
          }
        },
        {
          "group": "io.micronaut.aws",
          "module": "micronaut-aws-distributed-configuration",
          "version": {
            "requires": "3.10.10"
          }
        },
        {
          "group": "io.micronaut.aws",
          "module": "micronaut-aws-parameter-store",
          "version": {
            "requires": "3.10.10"
          }
        },
        {
          "group": "io.micronaut.aws",
          "module": "micronaut-aws-sdk-v1",
          "version": {
            "requires": "3.10.10"
          }
        },
        {
          "group": "io.micronaut.aws",
          "module": "micronaut-aws-sdk-v2",
          "version": {
            "requires": "3.10.10"
          }
        },
        {
          "group": "io.micronaut.aws",
          "module": "micronaut-aws-secretsmanager",
          "version": {
            "requires": "3.10.10"
          }
        },
        {
          "group": "io.micronaut.aws",
          "module": "micronaut-aws-service-discovery",
          "version": {
            "requires": "3.10.10"
          }
        },
        {
          "group": "io.micronaut.aws",
          "module": "micronaut-aws-ua",
          "version": {
            "requires": "3.10.10"
          }
        },
        {
          "group": "io.micronaut.aws",
          "module": "micronaut-function-aws",
          "version": {
            "requires": "3.10.10"
          }
        },
        {
          "group": "io.micronaut.aws",
          "module": "micronaut-function-aws-alexa",
          "version": {
            "requires": "3.10.10"
          }
        },
        {
          "group": "io.micronaut.aws",
          "module": "micronaut-function-aws-api-proxy",
          "version": {
            "requires": "3.10.10"
          }
        },
        {
          "group": "io.micronaut.aws",
          "module": "micronaut-function-aws-api-proxy-test",
          "version": {
            "requires": "3.10.10"
          }
        },
        {
          "group": "io.micronaut.aws",
          "module": "micronaut-function-aws-custom-runtime",
          "version": {
            "requires": "3.10.10"
          }
        },
        {
          "group": "io.micronaut.aws",
          "module": "micronaut-function-aws-test",
          "version": {
            "requires": "3.10.10"
          }
        },
        {
          "group": "io.micronaut.aws",
          "module": "micronaut-function-client-aws",
          "version": {
            "requires": "3.10.10"
          }
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.amazonaws",
          "module": "aws-java-sdk-bom",
          "version": {
            "requires": "1.12.414"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "software.amazon.awssdk",
          "module": "bom",
          "version": {
            "requires": "2.19.14"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "dependencyConstraints": [
        {
          "group": "com.amazon.alexa",
          "module": "ask-sdk",
          "version": {
            "requires": "2.44.0"
          }
        },
        {
          "group": "com.amazon.alexa",
          "module": "ask-sdk-core",
          "version": {
            "requires": "2.44.0"
          }
        },
        {
          "group": "com.amazon.alexa",
          "module": "ask-sdk-lambda-support",
          "version": {
            "requires": "2.44.0"
          }
        },
        {
          "group": "com.amazonaws",
          "module": "aws-java-sdk-core",
          "version": {
            "requires": "1.12.414"
          }
        },
        {
          "group": "com.amazonaws",
          "module": "aws-lambda-java-core",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "com.amazonaws",
          "module": "aws-lambda-java-events",
          "version": {
            "requires": "3.11.0"
          }
        },
        {
          "group": "com.amazonaws.serverless",
          "module": "aws-serverless-java-container-core",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "software.amazon.awssdk",
          "module": "secretsmanager",
          "version": {
            "requires": "2.19.14"
          }
        },
        {
          "group": "org.slf4j",
          "module": "jcl-over-slf4j",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "io.micronaut.aws",
          "module": "micronaut-aws-alexa",
          "version": {
            "requires": "3.10.10"
          }
        },
        {
          "group": "io.micronaut.aws",
          "module": "micronaut-aws-alexa-httpserver",
          "version": {
            "requires": "3.10.10"
          }
        },
        {
          "group": "io.micronaut.aws",
          "module": "micronaut-aws-apigateway",
          "version": {
            "requires": "3.10.10"
          }
        },
        {
          "group": "io.micronaut.aws",
          "module": "micronaut-aws-cdk",
          "version": {
            "requires": "3.10.10"
          }
        },
        {
          "group": "io.micronaut.aws",
          "module": "micronaut-aws-cloudwatch-logging",
          "version": {
            "requires": "3.10.10"
          }
        },
        {
          "group": "io.micronaut.aws",
          "module": "micronaut-aws-common",
          "version": {
            "requires": "3.10.10"
          }
        },
        {
          "group": "io.micronaut.aws",
          "module": "micronaut-aws-distributed-configuration",
          "version": {
            "requires": "3.10.10"
          }
        },
        {
          "group": "io.micronaut.aws",
          "module": "micronaut-aws-parameter-store",
          "version": {
            "requires": "3.10.10"
          }
        },
        {
          "group": "io.micronaut.aws",
          "module": "micronaut-aws-sdk-v1",
          "version": {
            "requires": "3.10.10"
          }
        },
        {
          "group": "io.micronaut.aws",
          "module": "micronaut-aws-sdk-v2",
          "version": {
            "requires": "3.10.10"
          }
        },
        {
          "group": "io.micronaut.aws",
          "module": "micronaut-aws-secretsmanager",
          "version": {
            "requires": "3.10.10"
          }
        },
        {
          "group": "io.micronaut.aws",
          "module": "micronaut-aws-service-discovery",
          "version": {
            "requires": "3.10.10"
          }
        },
        {
          "group": "io.micronaut.aws",
          "module": "micronaut-aws-ua",
          "version": {
            "requires": "3.10.10"
          }
        },
        {
          "group": "io.micronaut.aws",
          "module": "micronaut-function-aws",
          "version": {
            "requires": "3.10.10"
          }
        },
        {
          "group": "io.micronaut.aws",
          "module": "micronaut-function-aws-alexa",
          "version": {
            "requires": "3.10.10"
          }
        },
        {
          "group": "io.micronaut.aws",
          "module": "micronaut-function-aws-api-proxy",
          "version": {
            "requires": "3.10.10"
          }
        },
        {
          "group": "io.micronaut.aws",
          "module": "micronaut-function-aws-api-proxy-test",
          "version": {
            "requires": "3.10.10"
          }
        },
        {
          "group": "io.micronaut.aws",
          "module": "micronaut-function-aws-custom-runtime",
          "version": {
            "requires": "3.10.10"
          }
        },
        {
          "group": "io.micronaut.aws",
          "module": "micronaut-function-aws-test",
          "version": {
            "requires": "3.10.10"
          }
        },
        {
          "group": "io.micronaut.aws",
          "module": "micronaut-function-client-aws",
          "version": {
            "requires": "3.10.10"
          }
        }
      ]
    },
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "micronaut-aws-bom-3.10.10.toml",
          "url": "micronaut-aws-bom-3.10.10.toml",
          "size": 3944,
          "sha512": "e57451280a36ad6aeb67f5c529efa98219c54120a66815149a40e3fb3ba0be791d8c279b9028c03eb28f52c078e080113da181c22bb610d6bab7c06d9966ed29",
          "sha256": "dd30aade87dd5e77be4edff0ece46263c4df56d5cdeccf042bad8575f137a831",
          "sha1": "15057683223fc05fb60ea49419cd97cdb9a0057f",
          "md5": "6d3b924060bae5b091b6218f1f67ca0f"
        }
      ]
    }
  ]
}
