{
  "formatVersion": "1.1",
  "component": {
    "group": "org.grails",
    "module": "grails-datastore-gorm-validation",
    "version": "8.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy",
          "version": {
            "requires": "3.0.11"
          }
        },
        {
          "group": "org.grails",
          "module": "grails-datastore-core",
          "version": {
            "requires": "8.0.4"
          }
        },
        {
          "group": "commons-validator",
          "module": "commons-validator",
          "version": {
            "requires": "1.8.0"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            },
            {
              "group": "commons-digester",
              "module": "commons-digester"
            },
            {
              "group": "commons-logging",
              "module": "commons-logging"
            },
            {
              "group": "commons-beanutils",
              "module": "commons-beanutils"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "grails-datastore-gorm-validation-8.0.4.jar",
          "url": "grails-datastore-gorm-validation-8.0.4.jar",
          "size": 98188,
          "sha512": "89eac03d1c380c428d060260eefd6958e96b7008ea992281ba0bcdeba96b282fa215bef5a00ee7038c68c51aa4575a20e1d3c67376a2546f6c4f4db16b98637a",
          "sha256": "1d521a80585bf3994425f6f574fd3a575efe70d68fbdf64ff045adfacace0b5d",
          "sha1": "71392564cdfee0f56b0e8147e37aa0ad08de7bb9",
          "md5": "8dac3b3d25a6daa24fa2637bf12ab915"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy",
          "version": {
            "requires": "3.0.11"
          }
        },
        {
          "group": "org.grails",
          "module": "grails-datastore-core",
          "version": {
            "requires": "8.0.4"
          }
        },
        {
          "group": "commons-validator",
          "module": "commons-validator",
          "version": {
            "requires": "1.8.0"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            },
            {
              "group": "commons-digester",
              "module": "commons-digester"
            },
            {
              "group": "commons-logging",
              "module": "commons-logging"
            },
            {
              "group": "commons-beanutils",
              "module": "commons-beanutils"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "grails-datastore-gorm-validation-8.0.4.jar",
          "url": "grails-datastore-gorm-validation-8.0.4.jar",
          "size": 98188,
          "sha512": "89eac03d1c380c428d060260eefd6958e96b7008ea992281ba0bcdeba96b282fa215bef5a00ee7038c68c51aa4575a20e1d3c67376a2546f6c4f4db16b98637a",
          "sha256": "1d521a80585bf3994425f6f574fd3a575efe70d68fbdf64ff045adfacace0b5d",
          "sha1": "71392564cdfee0f56b0e8147e37aa0ad08de7bb9",
          "md5": "8dac3b3d25a6daa24fa2637bf12ab915"
        }
      ]
    }
  ]
}
