{
  "formatVersion": "1.1",
  "component": {
    "group": "io.micronaut.oraclecloud",
    "module": "micronaut-oraclecloud-bom",
    "version": "2.1.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "java-api"
      },
      "dependencyConstraints": [
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-circuitbreaker",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-common",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-audit",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-containerengine",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-core",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-database",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-dns",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-email",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-filestorage",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-identity",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-loadbalancer",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-objectstorage",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-addons-resteasy-client-configurator",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-addons-sasl",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-resourcesearch",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-addons-apache",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-keymanagement",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-announcementsservice",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-healthchecks",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-waas",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-streaming",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-resourcemanager",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-monitoring",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-ons",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-autoscaling",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-budget",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-workrequests",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-limits",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-functions",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-events",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-dts",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-oce",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-oda",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-analytics",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-integration",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-osmanagement",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-marketplace",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-apigateway",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-applicationmigration",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-datacatalog",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-dataflow",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-datascience",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-nosql",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-secrets",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-vault",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-bds",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-encryption",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-cims",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-datasafe",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-mysql",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-dataintegration",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-ocvp",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-usageapi",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-blockchain",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-loggingingestion",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-logging",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-loganalytics",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-managementdashboard",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-sch",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-loggingsearch",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-managementagent",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-cloudguard",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-opsi",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-computeinstanceagent",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-optimizer",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-tenantmanagercontrolplane",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-rover",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-databasemanagement",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-artifacts",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-apmsynthetics",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-goldengate",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-apmcontrolplane",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-apmtraces",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-networkloadbalancer",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-vulnerabilityscanning",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-databasemigration",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-servicecatalog",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-ailanguage",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-operatoraccesscontrol",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-bastion",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-genericartifactscontent",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-jms",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-devops",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-aianomalydetection",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-datalabelingservice",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-datalabelingservicedataplane",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-apmconfig",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-waf",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-certificates",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-certificatesmanagement",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-usage",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-databasetools",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-servicemanagerproxy",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-appmgmtcontrol",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-ospgateway",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-identitydataplane",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.fnproject.fn",
          "module": "api",
          "version": {
            "requires": "1.0.131"
          }
        },
        {
          "group": "com.fnproject.fn",
          "module": "runtime",
          "version": {
            "requires": "1.0.131"
          }
        },
        {
          "group": "com.fnproject.fn",
          "module": "testing-junit4",
          "version": {
            "requires": "1.0.131"
          }
        },
        {
          "group": "io.micronaut.oraclecloud",
          "module": "micronaut-oraclecloud-atp",
          "version": {
            "requires": "2.1.5"
          }
        },
        {
          "group": "io.micronaut.oraclecloud",
          "module": "micronaut-oraclecloud-common",
          "version": {
            "requires": "2.1.5"
          }
        },
        {
          "group": "io.micronaut.oraclecloud",
          "module": "micronaut-oraclecloud-function",
          "version": {
            "requires": "2.1.5"
          }
        },
        {
          "group": "io.micronaut.oraclecloud",
          "module": "micronaut-oraclecloud-function-http",
          "version": {
            "requires": "2.1.5"
          }
        },
        {
          "group": "io.micronaut.oraclecloud",
          "module": "micronaut-oraclecloud-function-http-test",
          "version": {
            "requires": "2.1.5"
          }
        },
        {
          "group": "io.micronaut.oraclecloud",
          "module": "micronaut-oraclecloud-micrometer",
          "version": {
            "requires": "2.1.5"
          }
        },
        {
          "group": "io.micronaut.oraclecloud",
          "module": "micronaut-oraclecloud-sdk",
          "version": {
            "requires": "2.1.5"
          }
        },
        {
          "group": "io.micronaut.oraclecloud",
          "module": "micronaut-oraclecloud-sdk-reactor",
          "version": {
            "requires": "2.1.5"
          }
        },
        {
          "group": "io.micronaut.oraclecloud",
          "module": "micronaut-oraclecloud-sdk-rxjava2",
          "version": {
            "requires": "2.1.5"
          }
        },
        {
          "group": "io.micronaut.oraclecloud",
          "module": "micronaut-oraclecloud-vault",
          "version": {
            "requires": "2.1.5"
          }
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-circuitbreaker",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-common",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-audit",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-containerengine",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-core",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-database",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-dns",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-email",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-filestorage",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-identity",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-loadbalancer",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-objectstorage",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-addons-resteasy-client-configurator",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-addons-sasl",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-resourcesearch",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-addons-apache",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-keymanagement",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-announcementsservice",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-healthchecks",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-waas",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-streaming",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-resourcemanager",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-monitoring",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-ons",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-autoscaling",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-budget",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-workrequests",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-limits",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-functions",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-events",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-dts",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-oce",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-oda",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-analytics",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-integration",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-osmanagement",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-marketplace",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-apigateway",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-applicationmigration",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-datacatalog",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-dataflow",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-datascience",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-nosql",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-secrets",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-vault",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-bds",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-encryption",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-cims",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-datasafe",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-mysql",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-dataintegration",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-ocvp",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-usageapi",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-blockchain",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-loggingingestion",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-logging",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-loganalytics",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-managementdashboard",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-sch",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-loggingsearch",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-managementagent",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-cloudguard",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-opsi",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-computeinstanceagent",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-optimizer",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-tenantmanagercontrolplane",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-rover",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-databasemanagement",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-artifacts",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-apmsynthetics",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-goldengate",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-apmcontrolplane",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-apmtraces",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-networkloadbalancer",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-vulnerabilityscanning",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-databasemigration",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-servicecatalog",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-ailanguage",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-operatoraccesscontrol",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-bastion",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-genericartifactscontent",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-jms",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-devops",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-aianomalydetection",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-datalabelingservice",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-datalabelingservicedataplane",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-apmconfig",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-waf",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-certificates",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-certificatesmanagement",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-usage",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-databasetools",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-servicemanagerproxy",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-appmgmtcontrol",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-ospgateway",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.oracle.oci.sdk",
          "module": "oci-java-sdk-identitydataplane",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.fnproject.fn",
          "module": "api",
          "version": {
            "requires": "1.0.131"
          }
        },
        {
          "group": "com.fnproject.fn",
          "module": "runtime",
          "version": {
            "requires": "1.0.131"
          }
        },
        {
          "group": "com.fnproject.fn",
          "module": "testing-junit4",
          "version": {
            "requires": "1.0.131"
          }
        },
        {
          "group": "io.micronaut.oraclecloud",
          "module": "micronaut-oraclecloud-atp",
          "version": {
            "requires": "2.1.5"
          }
        },
        {
          "group": "io.micronaut.oraclecloud",
          "module": "micronaut-oraclecloud-common",
          "version": {
            "requires": "2.1.5"
          }
        },
        {
          "group": "io.micronaut.oraclecloud",
          "module": "micronaut-oraclecloud-function",
          "version": {
            "requires": "2.1.5"
          }
        },
        {
          "group": "io.micronaut.oraclecloud",
          "module": "micronaut-oraclecloud-function-http",
          "version": {
            "requires": "2.1.5"
          }
        },
        {
          "group": "io.micronaut.oraclecloud",
          "module": "micronaut-oraclecloud-function-http-test",
          "version": {
            "requires": "2.1.5"
          }
        },
        {
          "group": "io.micronaut.oraclecloud",
          "module": "micronaut-oraclecloud-micrometer",
          "version": {
            "requires": "2.1.5"
          }
        },
        {
          "group": "io.micronaut.oraclecloud",
          "module": "micronaut-oraclecloud-sdk",
          "version": {
            "requires": "2.1.5"
          }
        },
        {
          "group": "io.micronaut.oraclecloud",
          "module": "micronaut-oraclecloud-sdk-reactor",
          "version": {
            "requires": "2.1.5"
          }
        },
        {
          "group": "io.micronaut.oraclecloud",
          "module": "micronaut-oraclecloud-sdk-rxjava2",
          "version": {
            "requires": "2.1.5"
          }
        },
        {
          "group": "io.micronaut.oraclecloud",
          "module": "micronaut-oraclecloud-vault",
          "version": {
            "requires": "2.1.5"
          }
        }
      ]
    },
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "micronaut-oraclecloud-bom-2.1.5.toml",
          "url": "micronaut-oraclecloud-bom-2.1.5.toml",
          "size": 1857,
          "sha512": "03546309fe6a9ca561185a725f3371595ef91efb474a84c44fc7126c69855c6275070aa687fecce07dd6f1960fe80ed489f07f933a2a13d0b830f7ee9e7fe518",
          "sha256": "ff3b96f345a4b2941fb1fa9c26aaf0a545831ccd8c43ac3ee9209c42d0c41a01",
          "sha1": "26de3083a5306a75b34dbcd1ad11f9c7c3eb35bc",
          "md5": "ae8b33baec7e8a84a76e8e4ae30c5803"
        }
      ]
    }
  ]
}
