{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fasterxml.jackson.core",
    "module": "jackson-databind",
    "version": "2.15.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "maven": {
      "version": "3.8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.15.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.15.0"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.15.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-databind-2.15.0.jar",
          "url": "jackson-databind-2.15.0.jar",
          "size": 1619579,
          "sha512": "2e71b6bda082a09f1c85c783896d13dc68dc818f1cb02e773a1569890b0daef8ea6ab4d863f465681fe07525eb9773d37ff2bd7eff6ba4f05b736d50c471e124",
          "sha256": "c5a5d5ae71ac8e8d5b8da606841e2251c806355939cb5d51c4cdc6b644a0dc",
          "sha1": "d41caa3a4e9f85382702a059a65c512f85ac230",
          "md5": "2cfab8609aef4ef886ec2c8f4167bb24"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.15.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.15.0"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.15.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-databind-2.15.0.jar",
          "url": "jackson-databind-2.15.0.jar",
          "size": 1619579,
          "sha512": "2e71b6bda082a09f1c85c783896d13dc68dc818f1cb02e773a1569890b0daef8ea6ab4d863f465681fe07525eb9773d37ff2bd7eff6ba4f05b736d50c471e124",
          "sha256": "c5a5d5ae71ac8e8d5b8da606841e2251c806355939cb5d51c4cdc6b644a0dc",
          "sha1": "d41caa3a4e9f85382702a059a65c512f85ac230",
          "md5": "2cfab8609aef4ef886ec2c8f4167bb24"
        }
      ]
    }
  ]
}
