{
  "formatVersion": "1.1",
  "component": {
    "group": "org.grails",
    "module": "grails-plugin-url-mappings",
    "version": "6.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "javax.servlet",
          "module": "javax.servlet-api",
          "version": {
            "requires": "4.0.1"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-test",
          "version": {
            "requires": "5.3.27"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy",
          "version": {
            "requires": "3.0.11"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            },
            {
              "group": "*",
              "module": "commons-cli"
            },
            {
              "group": "*",
              "module": "ant"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "jcl-over-slf4j",
          "version": {
            "requires": "1.7.36"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-web",
          "version": {
            "requires": "6.0.0"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-plugin-controllers",
          "version": {
            "requires": "6.0.0"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.13.2"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "grails-plugin-url-mappings-6.0.0.jar",
          "url": "grails-plugin-url-mappings-6.0.0.jar",
          "size": 22230,
          "sha512": "69269a8c58a1d678d723a6c42fc1c9ede12136eeae0eabd02833c98aa4912b9adb1b6380d7e3b95a99a5ab71b5c73486276c26118ae2063e72455307b2b24f3c",
          "sha256": "64cff65d664369ff8e02257438a736fd0c07e1cefcca3e942f182fa4de35097b",
          "sha1": "8191e0d48941d48bdf05f3687fd4f373f3074936",
          "md5": "796490af2c39fd988db7f09601e73d1e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "javax.servlet",
          "module": "javax.servlet-api",
          "version": {
            "requires": "4.0.1"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-test",
          "version": {
            "requires": "5.3.27"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy",
          "version": {
            "requires": "3.0.11"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            },
            {
              "group": "*",
              "module": "commons-cli"
            },
            {
              "group": "*",
              "module": "ant"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "jcl-over-slf4j",
          "version": {
            "requires": "1.7.36"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-web",
          "version": {
            "requires": "6.0.0"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-plugin-controllers",
          "version": {
            "requires": "6.0.0"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.13.2"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "grails-plugin-url-mappings-6.0.0.jar",
          "url": "grails-plugin-url-mappings-6.0.0.jar",
          "size": 22230,
          "sha512": "69269a8c58a1d678d723a6c42fc1c9ede12136eeae0eabd02833c98aa4912b9adb1b6380d7e3b95a99a5ab71b5c73486276c26118ae2063e72455307b2b24f3c",
          "sha256": "64cff65d664369ff8e02257438a736fd0c07e1cefcca3e942f182fa4de35097b",
          "sha1": "8191e0d48941d48bdf05f3687fd4f373f3074936",
          "md5": "796490af2c39fd988db7f09601e73d1e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "grails-plugin-url-mappings-6.0.0-javadoc.jar",
          "url": "grails-plugin-url-mappings-6.0.0-javadoc.jar",
          "size": 308352,
          "sha512": "1da231c1bd8559e2dc6ea440805a2c165f9409bb3901a1dcbb433042e5ad7c8bc54d398fa2a4a7a067f901052f4824a325a153eab2f406100515b03876ca3e0e",
          "sha256": "e45e68ab0d8d66e7c920eb3335b550283895bd7531312ae05b13541e8d32ff76",
          "sha1": "a3fd4bc02a27a5f05a37bdafa9f627806cb993d0",
          "md5": "cdbcf3db928b7dd0d423adac7101896d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "grails-plugin-url-mappings-6.0.0-sources.jar",
          "url": "grails-plugin-url-mappings-6.0.0-sources.jar",
          "size": 4437,
          "sha512": "900c73c31a93ea9136b5ab4e23609cc046bee1187d750f7d33dc6813fd07a1712cbbf5cf1941957a90252492ed4ebcb88771b5cf6ae463f85477bd84274ef404",
          "sha256": "0c398beb69ab0c96c426a68e46824867ca3e27dd3e4976e7270902186d29b07e",
          "sha1": "dad995dc61be6e95848160a4f8512b40edd578d3",
          "md5": "afa14b80c6fdb9c7d32d6264dae2e3ff"
        }
      ]
    }
  ]
}
