{
  "formatVersion": "1.1",
  "component": {
    "group": "org.grails",
    "module": "grails-web-common",
    "version": "6.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "javax.servlet",
          "module": "javax.servlet-api",
          "version": {
            "requires": "4.0.1"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-test",
          "version": {
            "requires": "5.3.27"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy",
          "version": {
            "requires": "3.0.11"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            },
            {
              "group": "*",
              "module": "commons-cli"
            },
            {
              "group": "*",
              "module": "ant"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "jcl-over-slf4j",
          "version": {
            "requires": "1.7.36"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-core",
          "version": {
            "requires": "6.0.0"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            },
            {
              "group": "org.grails",
              "module": "grails-spring"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-databinding",
          "version": {
            "requires": "6.0.0"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-encoder",
          "version": {
            "requires": "6.0.0"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-gsp",
          "version": {
            "requires": "6.0.0"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            },
            {
              "group": "org.grails",
              "module": "grails-encoder"
            },
            {
              "group": "org.grails",
              "module": "grails-core"
            }
          ]
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy-templates",
          "version": {
            "requires": "3.0.11"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-webmvc",
          "version": {
            "requires": "5.3.27"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-context-support",
          "version": {
            "requires": "5.3.27"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "grails-web-common-6.0.0.jar",
          "url": "grails-web-common-6.0.0.jar",
          "size": 182532,
          "sha512": "51a5a899a55d573bf816fd4d39943c05c9145ac06d9e9b5e4fd77dcb3ea1e8aa63f66b65b0190dd88a9d1661aaf6dddb84e1589d25fff66adde5602ec5cce064",
          "sha256": "7ee8c11d4217cd1d94acd703fa4ff2b7aea5f12a57c16500e34b2e3ac86a8844",
          "sha1": "34f04f39ebb3e3428d7e2897d87a5270bd1f278a",
          "md5": "11f3cd887b01f8d15f9ae14b7d77406e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.ben-manes.caffeine",
          "module": "caffeine",
          "version": {
            "requires": "2.9.3"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "javax.servlet",
          "module": "javax.servlet-api",
          "version": {
            "requires": "4.0.1"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-test",
          "version": {
            "requires": "5.3.27"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy",
          "version": {
            "requires": "3.0.11"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            },
            {
              "group": "*",
              "module": "commons-cli"
            },
            {
              "group": "*",
              "module": "ant"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "jcl-over-slf4j",
          "version": {
            "requires": "1.7.36"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-core",
          "version": {
            "requires": "6.0.0"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            },
            {
              "group": "org.grails",
              "module": "grails-spring"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-databinding",
          "version": {
            "requires": "6.0.0"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-encoder",
          "version": {
            "requires": "6.0.0"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-gsp",
          "version": {
            "requires": "6.0.0"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            },
            {
              "group": "org.grails",
              "module": "grails-encoder"
            },
            {
              "group": "org.grails",
              "module": "grails-core"
            }
          ]
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy-templates",
          "version": {
            "requires": "3.0.11"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-webmvc",
          "version": {
            "requires": "5.3.27"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-context-support",
          "version": {
            "requires": "5.3.27"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "grails-web-common-6.0.0.jar",
          "url": "grails-web-common-6.0.0.jar",
          "size": 182532,
          "sha512": "51a5a899a55d573bf816fd4d39943c05c9145ac06d9e9b5e4fd77dcb3ea1e8aa63f66b65b0190dd88a9d1661aaf6dddb84e1589d25fff66adde5602ec5cce064",
          "sha256": "7ee8c11d4217cd1d94acd703fa4ff2b7aea5f12a57c16500e34b2e3ac86a8844",
          "sha1": "34f04f39ebb3e3428d7e2897d87a5270bd1f278a",
          "md5": "11f3cd887b01f8d15f9ae14b7d77406e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "grails-web-common-6.0.0-javadoc.jar",
          "url": "grails-web-common-6.0.0-javadoc.jar",
          "size": 639569,
          "sha512": "1a9c00b8f6ae03570be30d944d52c4cf1ba6c9f156f6633a2e1a39347c85c4f46827e197b3b22eefd4ee26868ba0d8aa068f197bb33ee47351e3be02e6629c8c",
          "sha256": "2ba580a069bfc71575cb8a430f42fc8568a3bbbd3051a63290fbc9fded3086d8",
          "sha1": "5e055c2ed942ee080d4aff0bc24748baef32fef3",
          "md5": "7b961c2046035f375dd8706aaa7556bb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "grails-web-common-6.0.0-sources.jar",
          "url": "grails-web-common-6.0.0-sources.jar",
          "size": 128545,
          "sha512": "e4054f0877e429a3486b198790ad6c1b0eb6949d22bad5528d9aa620f4e9ea28516da1169175f32fa8a8d03dff256a2447d70a7f8dfad9f84361131b92216d29",
          "sha256": "969001ba4960141e521648b23d168531524518d6276c9f1e8acc03e2e061b0c2",
          "sha1": "c74417cc4cfc7fef611a457a8cd80ebf86f0f863",
          "md5": "a80fa8a25b51304db37dad4c6de5c689"
        }
      ]
    }
  ]
}
