{
  "formatVersion": "1.1",
  "component": {
    "group": "org.junit.jupiter",
    "module": "junit-jupiter-params",
    "version": "5.9.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.junit",
          "module": "junit-bom",
          "version": {
            "requires": "5.9.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.9.2"
          }
        },
        {
          "group": "org.apiguardian",
          "module": "apiguardian-api",
          "version": {
            "requires": "1.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "junit-jupiter-params-5.9.2.jar",
          "url": "junit-jupiter-params-5.9.2.jar",
          "size": 579825,
          "sha512": "6fd6fb739f9ab7d7d188a96e56c26979ab720f0dd7d9f12bf732bb3b1689ba4f5c327e86b4cfae5e468027ca11019dfcbfff60c0ec924c8bc69389bff03de98c",
          "sha256": "bde91900a5ce5d6663bb44bc708494b35daefcd73e1bb7afa61a4affe38ea97d",
          "sha1": "bc2765afb7b85b583c710dd259a11c6b8c39e912",
          "md5": "24a999489143e8d1b958c42b37c082b6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.junit",
          "module": "junit-bom",
          "version": {
            "requires": "5.9.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.9.2"
          }
        }
      ],
      "files": [
        {
          "name": "junit-jupiter-params-5.9.2.jar",
          "url": "junit-jupiter-params-5.9.2.jar",
          "size": 579825,
          "sha512": "6fd6fb739f9ab7d7d188a96e56c26979ab720f0dd7d9f12bf732bb3b1689ba4f5c327e86b4cfae5e468027ca11019dfcbfff60c0ec924c8bc69389bff03de98c",
          "sha256": "bde91900a5ce5d6663bb44bc708494b35daefcd73e1bb7afa61a4affe38ea97d",
          "sha1": "bc2765afb7b85b583c710dd259a11c6b8c39e912",
          "md5": "24a999489143e8d1b958c42b37c082b6"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "junit-jupiter-params-5.9.2-javadoc.jar",
          "url": "junit-jupiter-params-5.9.2-javadoc.jar",
          "size": 263863,
          "sha512": "4f8b7eca11794cf23c3fa496c3349a7e8262d6eb8bf239fe4ff82a142c8eed16fc0d8d8a0dd7ced0ca9439b85eebccaba9733e68046fbb75e562d65fb77ecd9b",
          "sha256": "2136a667376cc440f8efca9d016b7e182e4e3dbe09aad1ea346f5bcb6bcafb9c",
          "sha1": "467c8f081b1b735d5e93c450a267d9ff65f4dbf0",
          "md5": "cc01a9afa3cf9da5afe594ca6ce415cc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "junit-jupiter-params-5.9.2-sources.jar",
          "url": "junit-jupiter-params-5.9.2-sources.jar",
          "size": 73684,
          "sha512": "e21c83307110ab2821b2c41f6c7413a970b02ae690e16bffae1321dc4c06d7009e6be0c2b0bb7cae60d0772e4dc69b7c9bd7fe82414afe083665b6a9d82d4649",
          "sha256": "b679bb967510ad4e26b78297148b0e16a3cee9e83cab1ac794f13dc4fd7c5e3e",
          "sha1": "6dc22e4af51cac3e98fe10e0807fee878c79bb59",
          "md5": "9643d27f61bd49dc3095655739fa3493"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "junit-jupiter-params-5.9.2.jar",
          "url": "junit-jupiter-params-5.9.2.jar",
          "size": 579825,
          "sha512": "6fd6fb739f9ab7d7d188a96e56c26979ab720f0dd7d9f12bf732bb3b1689ba4f5c327e86b4cfae5e468027ca11019dfcbfff60c0ec924c8bc69389bff03de98c",
          "sha256": "bde91900a5ce5d6663bb44bc708494b35daefcd73e1bb7afa61a4affe38ea97d",
          "sha1": "bc2765afb7b85b583c710dd259a11c6b8c39e912",
          "md5": "24a999489143e8d1b958c42b37c082b6"
        }
      ]
    }
  ]
}
