{
  "formatVersion": "1.1",
  "component": {
    "group": "io.micronaut.gcp",
    "module": "micronaut-gcp-bom",
    "version": "4.8.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "java-api"
      },
      "dependencyConstraints": [
        {
          "group": "com.google.cloud.functions",
          "module": "functions-framework-api",
          "version": {
            "requires": "1.0.4"
          }
        },
        {
          "group": "com.google.auth",
          "module": "google-auth-library-oauth2-http",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.google.cloud",
          "module": "google-cloud-core",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.google.cloud",
          "module": "google-cloud-pubsub",
          "version": {
            "requires": "1.122.2"
          }
        },
        {
          "group": "com.google.cloud",
          "module": "google-cloud-secretmanager",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "com.google.cloud",
          "module": "google-cloudevent-types",
          "version": {
            "requires": "0.3.0"
          }
        },
        {
          "group": "com.google.cloud",
          "module": "native-image-support",
          "version": {
            "requires": "0.14.1"
          }
        },
        {
          "group": "io.micronaut.gcp",
          "module": "micronaut-gcp-common",
          "version": {
            "requires": "4.8.1"
          }
        },
        {
          "group": "io.micronaut.gcp",
          "module": "micronaut-gcp-function",
          "version": {
            "requires": "4.8.1"
          }
        },
        {
          "group": "io.micronaut.gcp",
          "module": "micronaut-gcp-function-cloudevents",
          "version": {
            "requires": "4.8.1"
          }
        },
        {
          "group": "io.micronaut.gcp",
          "module": "micronaut-gcp-function-http",
          "version": {
            "requires": "4.8.1"
          }
        },
        {
          "group": "io.micronaut.gcp",
          "module": "micronaut-gcp-function-http-test",
          "version": {
            "requires": "4.8.1"
          }
        },
        {
          "group": "io.micronaut.gcp",
          "module": "micronaut-gcp-http-client",
          "version": {
            "requires": "4.8.1"
          }
        },
        {
          "group": "io.micronaut.gcp",
          "module": "micronaut-gcp-logging",
          "version": {
            "requires": "4.8.1"
          }
        },
        {
          "group": "io.micronaut.gcp",
          "module": "micronaut-gcp-pubsub",
          "version": {
            "requires": "4.8.1"
          }
        },
        {
          "group": "io.micronaut.gcp",
          "module": "micronaut-gcp-secret-manager",
          "version": {
            "requires": "4.8.1"
          }
        },
        {
          "group": "io.micronaut.gcp",
          "module": "micronaut-gcp-serde-cloudevents",
          "version": {
            "requires": "4.8.1"
          }
        },
        {
          "group": "io.micronaut.gcp",
          "module": "micronaut-gcp-tracing",
          "version": {
            "requires": "4.8.1"
          }
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "com.google.cloud.functions",
          "module": "functions-framework-api",
          "version": {
            "requires": "1.0.4"
          }
        },
        {
          "group": "com.google.auth",
          "module": "google-auth-library-oauth2-http",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "com.google.cloud",
          "module": "google-cloud-core",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.google.cloud",
          "module": "google-cloud-pubsub",
          "version": {
            "requires": "1.122.2"
          }
        },
        {
          "group": "com.google.cloud",
          "module": "google-cloud-secretmanager",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "com.google.cloud",
          "module": "google-cloudevent-types",
          "version": {
            "requires": "0.3.0"
          }
        },
        {
          "group": "com.google.cloud",
          "module": "native-image-support",
          "version": {
            "requires": "0.14.1"
          }
        },
        {
          "group": "io.micronaut.gcp",
          "module": "micronaut-gcp-common",
          "version": {
            "requires": "4.8.1"
          }
        },
        {
          "group": "io.micronaut.gcp",
          "module": "micronaut-gcp-function",
          "version": {
            "requires": "4.8.1"
          }
        },
        {
          "group": "io.micronaut.gcp",
          "module": "micronaut-gcp-function-cloudevents",
          "version": {
            "requires": "4.8.1"
          }
        },
        {
          "group": "io.micronaut.gcp",
          "module": "micronaut-gcp-function-http",
          "version": {
            "requires": "4.8.1"
          }
        },
        {
          "group": "io.micronaut.gcp",
          "module": "micronaut-gcp-function-http-test",
          "version": {
            "requires": "4.8.1"
          }
        },
        {
          "group": "io.micronaut.gcp",
          "module": "micronaut-gcp-http-client",
          "version": {
            "requires": "4.8.1"
          }
        },
        {
          "group": "io.micronaut.gcp",
          "module": "micronaut-gcp-logging",
          "version": {
            "requires": "4.8.1"
          }
        },
        {
          "group": "io.micronaut.gcp",
          "module": "micronaut-gcp-pubsub",
          "version": {
            "requires": "4.8.1"
          }
        },
        {
          "group": "io.micronaut.gcp",
          "module": "micronaut-gcp-secret-manager",
          "version": {
            "requires": "4.8.1"
          }
        },
        {
          "group": "io.micronaut.gcp",
          "module": "micronaut-gcp-serde-cloudevents",
          "version": {
            "requires": "4.8.1"
          }
        },
        {
          "group": "io.micronaut.gcp",
          "module": "micronaut-gcp-tracing",
          "version": {
            "requires": "4.8.1"
          }
        }
      ]
    },
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "micronaut-gcp-bom-4.8.1.toml",
          "url": "micronaut-gcp-bom-4.8.1.toml",
          "size": 2871,
          "sha512": "afec4569e643533fd91b59d49e9f4e96250575c1ac18b9bc5a8ed8334c7607dac22268a945e301912b1927de33c6ce11520c0f43c31fe0d08be9e2b99f24fbc6",
          "sha256": "e3fbd99c40a906796e856ecfc9aa2ce8302ee1b237cf22b1a237614e2b77cad7",
          "sha1": "f5e57a2503fda8433bfa86f1e16984dd17cfb793",
          "md5": "8d011c862d86cd868bdd38b2b2148dbc"
        }
      ]
    }
  ]
}
