{
  "formatVersion": "1.1",
  "component": {
    "group": "org.apache.groovy",
    "module": "groovy-xml",
    "version": "4.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "groovydocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "groovydoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "groovy-xml-4.0.4-groovydoc.jar",
          "url": "groovy-xml-4.0.4-groovydoc.jar",
          "size": 259215,
          "sha512": "46d739b2f06b36eb5ecbab9d01651a999908ca1ace10ea97081478073384ea289681f3c7a2f679fef1d5421f84d712161b7b7f516e270ab206c3bbfa4345386d",
          "sha256": "bdcbffe279aa6df8a05edb2facaffa0ca5769e4b924adb0bda3dad9e03efab64",
          "sha1": "61b5536f5bea62a2e6b948b388bc0f8e0aa8de2d",
          "md5": "a6cebf450c00c4d1e209d83e984d55a2"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "groovy-xml-4.0.4-javadoc.jar",
          "url": "groovy-xml-4.0.4-javadoc.jar",
          "size": 319920,
          "sha512": "0ad351f2db0c8c5ccf36378b3e446c5fc2a7bbc565d066876dfec30c8cd257a3c3a703a43d1c34330e470bbd6da4d30627e8b910f9de34596da5b1cdbde62cf2",
          "sha256": "cb914b20b636a6ed06c19e00e42c2119b57e83b7c0c4df1821fc8b794d68f443",
          "sha1": "2e49a2a7cfe40cde66e7c1a8b32c6f4e646fd704",
          "md5": "2fc35ede61a73dd81474b2628e5d935c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "groovy-xml-4.0.4-sources.jar",
          "url": "groovy-xml-4.0.4-sources.jar",
          "size": 98897,
          "sha512": "52dc85f40d33b1c0063a8fbd160e482f6224960c1168b469b0c7f5ec77eaf101170b3436db897a5f5bedaa052f7a4b89f9d09bcbcdb580bdedfbd1308082b94f",
          "sha256": "723ca05b84b6523b35ec1c97d1e9654355cb54f6168054bd695cfafb8c5d3435",
          "sha1": "63f9a96e2bc40caaab9bd8b2f3fe079c0d7ac802",
          "md5": "ef7f7b2257ae30bbe8389b52c7b0269d"
        }
      ]
    },
    {
      "name": "groovyApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.groovy",
          "module": "groovy-bom",
          "version": {
            "requires": "4.0.4"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy",
          "version": {
            "requires": "4.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "groovy-xml-4.0.4.jar",
          "url": "groovy-xml-4.0.4.jar",
          "size": 230235,
          "sha512": "daa608243c99f40cc766ea479fe778611c3aa8ba6c18817ff6e3967afe59065edb71bb7bc63979f62e87ced1cacbc45515abcb028c6cd24a7264eff0fd59adc4",
          "sha256": "dec020d761bceb89510a38aba70cdcc26caa0726fdf17bd5f33f8496f9e77915",
          "sha1": "d475fd1b2d0f8dd6fd87a2ffa651f54a6146df34",
          "md5": "695453607a5da6b9a12bd3e6525ba8d5"
        }
      ],
      "capabilities": [
        {
          "group": "org.apache.groovy",
          "name": "groovy-xml",
          "version": "4.0.4"
        },
        {
          "group": "org.codehaus.groovy",
          "name": "groovy-xml",
          "version": "4.0.4"
        }
      ]
    },
    {
      "name": "groovyRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.groovy",
          "module": "groovy-bom",
          "version": {
            "requires": "4.0.4"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy",
          "version": {
            "requires": "4.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "groovy-xml-4.0.4.jar",
          "url": "groovy-xml-4.0.4.jar",
          "size": 230235,
          "sha512": "daa608243c99f40cc766ea479fe778611c3aa8ba6c18817ff6e3967afe59065edb71bb7bc63979f62e87ced1cacbc45515abcb028c6cd24a7264eff0fd59adc4",
          "sha256": "dec020d761bceb89510a38aba70cdcc26caa0726fdf17bd5f33f8496f9e77915",
          "sha1": "d475fd1b2d0f8dd6fd87a2ffa651f54a6146df34",
          "md5": "695453607a5da6b9a12bd3e6525ba8d5"
        }
      ],
      "capabilities": [
        {
          "group": "org.apache.groovy",
          "name": "groovy-xml",
          "version": "4.0.4"
        },
        {
          "group": "org.codehaus.groovy",
          "name": "groovy-xml",
          "version": "4.0.4"
        }
      ]
    }
  ]
}
