{
  "formatVersion": "1.1",
  "component": {
    "group": "org.grails",
    "module": "grails-datastore-gorm-test",
    "version": "8.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy",
          "version": {
            "requires": "3.0.11"
          }
        },
        {
          "group": "org.grails",
          "module": "grails-datastore-gorm",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "org.grails",
          "module": "grails-datastore-core",
          "version": {
            "requires": "8.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "grails-datastore-gorm-test-8.0.0.jar",
          "url": "grails-datastore-gorm-test-8.0.0.jar",
          "size": 323772,
          "sha512": "3ddfd8fe2bc625d625da719de25611d761e244d04a34a56c2c39a86529d0d5a375c2c2b2088a06a8364270d6d052a06c67e2c90d4ce9c80355f94fc3e01dc558",
          "sha256": "4588f85429461c9eb856b51a682cefbb5ae6185a0bccfed7f17981a185d169c8",
          "sha1": "223f866e904a9f0ba743e8ebc4c05973d600c32c",
          "md5": "1d6ece9ee82e1c148aca68e3f954bfeb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.ben-manes.caffeine",
          "module": "caffeine",
          "version": {
            "requires": "2.9.3"
          }
        },
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy",
          "version": {
            "requires": "3.0.11"
          }
        },
        {
          "group": "org.grails",
          "module": "grails-datastore-gorm",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "org.grails",
          "module": "grails-datastore-core",
          "version": {
            "requires": "8.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "grails-datastore-gorm-test-8.0.0.jar",
          "url": "grails-datastore-gorm-test-8.0.0.jar",
          "size": 323772,
          "sha512": "3ddfd8fe2bc625d625da719de25611d761e244d04a34a56c2c39a86529d0d5a375c2c2b2088a06a8364270d6d052a06c67e2c90d4ce9c80355f94fc3e01dc558",
          "sha256": "4588f85429461c9eb856b51a682cefbb5ae6185a0bccfed7f17981a185d169c8",
          "sha1": "223f866e904a9f0ba743e8ebc4c05973d600c32c",
          "md5": "1d6ece9ee82e1c148aca68e3f954bfeb"
        }
      ]
    }
  ]
}
