{
  "formatVersion": "1.1",
  "component": {
    "group": "org.grails",
    "module": "grails-datastore-web",
    "version": "8.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy",
          "version": {
            "requires": "3.0.11"
          }
        },
        {
          "group": "org.grails",
          "module": "grails-datastore-core",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "5.3.27"
          },
          "excludes": [
            {
              "group": "org.springframework",
              "module": "spring-core"
            },
            {
              "group": "org.springframework",
              "module": "spring-aop"
            },
            {
              "group": "org.springframework",
              "module": "spring-beans"
            },
            {
              "group": "commons-logging",
              "module": "commons-logging"
            },
            {
              "group": "org.springframework",
              "module": "spring-context"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "5.3.27"
          },
          "excludes": [
            {
              "group": "org.springframework",
              "module": "spring-expression"
            },
            {
              "group": "org.springframework",
              "module": "spring-core"
            },
            {
              "group": "org.springframework",
              "module": "spring-aop"
            },
            {
              "group": "org.springframework",
              "module": "spring-asm"
            },
            {
              "group": "org.springframework",
              "module": "spring-beans"
            },
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "grails-datastore-web-8.0.0.jar",
          "url": "grails-datastore-web-8.0.0.jar",
          "size": 10041,
          "sha512": "69dd24fc6afa68baff7acae01d47c71779935f7ade7c35405dd76d73557877b14b384aa7ef43cd07fdac236c81f646657922b1e3f50f58e69582e3528a4a3733",
          "sha256": "f3eb3ef58af632adbd554e15d376473c921bdf8d7a38addc760c35982f2c5ab3",
          "sha1": "e58f8545ca207ae67cebeda30636b79374e43c3a",
          "md5": "621b738825160c50e98bf4cfaea593fe"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy",
          "version": {
            "requires": "3.0.11"
          }
        },
        {
          "group": "org.grails",
          "module": "grails-datastore-core",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "5.3.27"
          },
          "excludes": [
            {
              "group": "org.springframework",
              "module": "spring-core"
            },
            {
              "group": "org.springframework",
              "module": "spring-aop"
            },
            {
              "group": "org.springframework",
              "module": "spring-beans"
            },
            {
              "group": "commons-logging",
              "module": "commons-logging"
            },
            {
              "group": "org.springframework",
              "module": "spring-context"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "5.3.27"
          },
          "excludes": [
            {
              "group": "org.springframework",
              "module": "spring-expression"
            },
            {
              "group": "org.springframework",
              "module": "spring-core"
            },
            {
              "group": "org.springframework",
              "module": "spring-aop"
            },
            {
              "group": "org.springframework",
              "module": "spring-asm"
            },
            {
              "group": "org.springframework",
              "module": "spring-beans"
            },
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "grails-datastore-web-8.0.0.jar",
          "url": "grails-datastore-web-8.0.0.jar",
          "size": 10041,
          "sha512": "69dd24fc6afa68baff7acae01d47c71779935f7ade7c35405dd76d73557877b14b384aa7ef43cd07fdac236c81f646657922b1e3f50f58e69582e3528a4a3733",
          "sha256": "f3eb3ef58af632adbd554e15d376473c921bdf8d7a38addc760c35982f2c5ab3",
          "sha1": "e58f8545ca207ae67cebeda30636b79374e43c3a",
          "md5": "621b738825160c50e98bf4cfaea593fe"
        }
      ]
    }
  ]
}
