{
  "formatVersion": "1.1",
  "component": {
    "group": "org.grails",
    "module": "grails-datastore-gorm-support",
    "version": "8.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy",
          "version": {
            "requires": "3.0.11"
          }
        },
        {
          "group": "org.grails",
          "module": "grails-datastore-gorm",
          "version": {
            "requires": "8.0.4"
          }
        },
        {
          "group": "org.grails",
          "module": "grails-core",
          "version": {
            "requires": "6.1.1"
          },
          "excludes": [
            {
              "group": "org.springframework",
              "module": "spring-web"
            },
            {
              "group": "aopalliance",
              "module": "aopalliance"
            },
            {
              "group": "org.springframework",
              "module": "spring-aspects"
            },
            {
              "group": "org.springframework",
              "module": "spring-expression"
            },
            {
              "group": "org.hibernate.javax.persistence",
              "module": "hibernate-jpa-2.1-api"
            },
            {
              "group": "com.googlecode.concurrentlinkedhashmap",
              "module": "concurrentlinkedhashmap-lru"
            },
            {
              "group": "commons-io",
              "module": "commons-io"
            },
            {
              "group": "commons-validator",
              "module": "commons-validator"
            },
            {
              "group": "org.aspectj",
              "module": "aspectjrt"
            },
            {
              "group": "xalan",
              "module": "serializer"
            },
            {
              "group": "org.springframework",
              "module": "spring-beans"
            },
            {
              "group": "commons-logging",
              "module": "commons-logging"
            },
            {
              "group": "org.grails",
              "module": "grails-bootstrap"
            },
            {
              "group": "asm",
              "module": "asm"
            },
            {
              "group": "cglib",
              "module": "cglib"
            },
            {
              "group": "org.aspectj",
              "module": "aspectjweaver"
            },
            {
              "group": "oro",
              "module": "oro"
            },
            {
              "group": "cglib",
              "module": "cglib-nodep"
            },
            {
              "group": "org.springframework",
              "module": "spring-aop"
            },
            {
              "group": "org.grails",
              "module": "grails-spring"
            },
            {
              "group": "commons-lang",
              "module": "commons-lang"
            },
            {
              "group": "org.springframework",
              "module": "spring-context"
            },
            {
              "group": "org.springframework",
              "module": "spring-context-support"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-bootstrap",
          "version": {
            "requires": "6.1.1"
          },
          "excludes": [
            {
              "group": "org.apache.ant",
              "module": "ant-junit"
            },
            {
              "group": "org.fusesource.jansi",
              "module": "jansi"
            },
            {
              "group": "org.apache.ivy",
              "module": "ivy"
            },
            {
              "group": "org.apache.ant",
              "module": "ant-trax"
            },
            {
              "group": "org.codehaus.groovy",
              "module": "groovy-ant"
            },
            {
              "group": "org.codehaus.groovy",
              "module": "groovy-xml"
            },
            {
              "group": "org.apache.ant",
              "module": "ant"
            },
            {
              "group": "net.java.dev.jna",
              "module": "jna"
            },
            {
              "group": "org.apache.ant",
              "module": "ant-launcher"
            },
            {
              "group": "org.codehaus.gant",
              "module": "gant_groovy1.8"
            },
            {
              "group": "jline",
              "module": "jline"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "grails-datastore-gorm-support-8.0.4.jar",
          "url": "grails-datastore-gorm-support-8.0.4.jar",
          "size": 13058,
          "sha512": "396fa77b32244159b606ef4917eee2e4ac036d9626fa9bfa029bdfe3746aaca111fcbd763f17ddd7c5a1c5dba8664bcdd91b7f91f86c2e2a79582d76abb01470",
          "sha256": "31d5cebaa8e6ab81e0ae17d4316fa9bdd61c9e71cc22037887b10253774fa673",
          "sha1": "896735165e0d05941464af21b795c781e91ff168",
          "md5": "b78ad15fa2aedac8090ad54406b60ad7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy",
          "version": {
            "requires": "3.0.11"
          }
        },
        {
          "group": "org.grails",
          "module": "grails-datastore-gorm",
          "version": {
            "requires": "8.0.4"
          }
        },
        {
          "group": "org.grails",
          "module": "grails-core",
          "version": {
            "requires": "6.1.1"
          },
          "excludes": [
            {
              "group": "org.springframework",
              "module": "spring-web"
            },
            {
              "group": "aopalliance",
              "module": "aopalliance"
            },
            {
              "group": "org.springframework",
              "module": "spring-aspects"
            },
            {
              "group": "org.springframework",
              "module": "spring-expression"
            },
            {
              "group": "org.hibernate.javax.persistence",
              "module": "hibernate-jpa-2.1-api"
            },
            {
              "group": "com.googlecode.concurrentlinkedhashmap",
              "module": "concurrentlinkedhashmap-lru"
            },
            {
              "group": "commons-io",
              "module": "commons-io"
            },
            {
              "group": "commons-validator",
              "module": "commons-validator"
            },
            {
              "group": "org.aspectj",
              "module": "aspectjrt"
            },
            {
              "group": "xalan",
              "module": "serializer"
            },
            {
              "group": "org.springframework",
              "module": "spring-beans"
            },
            {
              "group": "commons-logging",
              "module": "commons-logging"
            },
            {
              "group": "org.grails",
              "module": "grails-bootstrap"
            },
            {
              "group": "asm",
              "module": "asm"
            },
            {
              "group": "cglib",
              "module": "cglib"
            },
            {
              "group": "org.aspectj",
              "module": "aspectjweaver"
            },
            {
              "group": "oro",
              "module": "oro"
            },
            {
              "group": "cglib",
              "module": "cglib-nodep"
            },
            {
              "group": "org.springframework",
              "module": "spring-aop"
            },
            {
              "group": "org.grails",
              "module": "grails-spring"
            },
            {
              "group": "commons-lang",
              "module": "commons-lang"
            },
            {
              "group": "org.springframework",
              "module": "spring-context"
            },
            {
              "group": "org.springframework",
              "module": "spring-context-support"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-bootstrap",
          "version": {
            "requires": "6.1.1"
          },
          "excludes": [
            {
              "group": "org.apache.ant",
              "module": "ant-junit"
            },
            {
              "group": "org.fusesource.jansi",
              "module": "jansi"
            },
            {
              "group": "org.apache.ivy",
              "module": "ivy"
            },
            {
              "group": "org.apache.ant",
              "module": "ant-trax"
            },
            {
              "group": "org.codehaus.groovy",
              "module": "groovy-ant"
            },
            {
              "group": "org.codehaus.groovy",
              "module": "groovy-xml"
            },
            {
              "group": "org.apache.ant",
              "module": "ant"
            },
            {
              "group": "net.java.dev.jna",
              "module": "jna"
            },
            {
              "group": "org.apache.ant",
              "module": "ant-launcher"
            },
            {
              "group": "org.codehaus.gant",
              "module": "gant_groovy1.8"
            },
            {
              "group": "jline",
              "module": "jline"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "grails-datastore-gorm-support-8.0.4.jar",
          "url": "grails-datastore-gorm-support-8.0.4.jar",
          "size": 13058,
          "sha512": "396fa77b32244159b606ef4917eee2e4ac036d9626fa9bfa029bdfe3746aaca111fcbd763f17ddd7c5a1c5dba8664bcdd91b7f91f86c2e2a79582d76abb01470",
          "sha256": "31d5cebaa8e6ab81e0ae17d4316fa9bdd61c9e71cc22037887b10253774fa673",
          "sha1": "896735165e0d05941464af21b795c781e91ff168",
          "md5": "b78ad15fa2aedac8090ad54406b60ad7"
        }
      ]
    }
  ]
}
