{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-tomcat",
    "version": "2.7.18",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-core",
          "version": {
            "requires": "9.0.83"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-el",
          "version": {
            "requires": "9.0.83"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-websocket",
          "version": {
            "requires": "9.0.83"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-tomcat-2.7.18.jar",
          "url": "spring-boot-starter-tomcat-2.7.18.jar",
          "size": 4797,
          "sha512": "6fb711f39e435c113e2547f894e1875b8cb936e33daca75d92f164b903124979917418e810b1d523932f374b0a1a1614f6078d135780e3b8a305a381608ea604",
          "sha256": "e4a44478556749137f28001c35d897efff31f39161606589cc355dcbf797c6f0",
          "sha1": "c56e50e006448e75a8bde595dbc754ba294389af",
          "md5": "c2080ad5020671b7884b9564006bd09c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-core",
          "version": {
            "requires": "9.0.83"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-el",
          "version": {
            "requires": "9.0.83"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-websocket",
          "version": {
            "requires": "9.0.83"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-tomcat-2.7.18.jar",
          "url": "spring-boot-starter-tomcat-2.7.18.jar",
          "size": 4797,
          "sha512": "6fb711f39e435c113e2547f894e1875b8cb936e33daca75d92f164b903124979917418e810b1d523932f374b0a1a1614f6078d135780e3b8a305a381608ea604",
          "sha256": "e4a44478556749137f28001c35d897efff31f39161606589cc355dcbf797c6f0",
          "sha1": "c56e50e006448e75a8bde595dbc754ba294389af",
          "md5": "c2080ad5020671b7884b9564006bd09c"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-starter-tomcat-2.7.18.jar",
          "url": "spring-boot-starter-tomcat-2.7.18.jar",
          "size": 4797,
          "sha512": "6fb711f39e435c113e2547f894e1875b8cb936e33daca75d92f164b903124979917418e810b1d523932f374b0a1a1614f6078d135780e3b8a305a381608ea604",
          "sha256": "e4a44478556749137f28001c35d897efff31f39161606589cc355dcbf797c6f0",
          "sha1": "c56e50e006448e75a8bde595dbc754ba294389af",
          "md5": "c2080ad5020671b7884b9564006bd09c"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-tomcat-maven-optional",
          "version": "2.7.18"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-tomcat-2.7.18.jar",
          "url": "spring-boot-starter-tomcat-2.7.18.jar",
          "size": 4797,
          "sha512": "6fb711f39e435c113e2547f894e1875b8cb936e33daca75d92f164b903124979917418e810b1d523932f374b0a1a1614f6078d135780e3b8a305a381608ea604",
          "sha256": "e4a44478556749137f28001c35d897efff31f39161606589cc355dcbf797c6f0",
          "sha1": "c56e50e006448e75a8bde595dbc754ba294389af",
          "md5": "c2080ad5020671b7884b9564006bd09c"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-tomcat-maven-optional",
          "version": "2.7.18"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-tomcat-2.7.18-javadoc.jar",
          "url": "spring-boot-starter-tomcat-2.7.18-javadoc.jar",
          "size": 4745,
          "sha512": "7a8d34e2912e6cd02e6d426503614e9f8d8e9512a4044c5f1a2d063c19b05da987dfb8146dddb87c06b876fe5c941cf9c72a6dea7c5cdbca707e46c32ff1b5d4",
          "sha256": "6cdba54878e1f0eee95d62b4731c49181afac1b8e1a69603b920d7e7647d5cce",
          "sha1": "68f4d8f516338008162e5528a743b7519d0a8df9",
          "md5": "bb54090a87ff9a322bb3936bc131fd8c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-tomcat-2.7.18-sources.jar",
          "url": "spring-boot-starter-tomcat-2.7.18-sources.jar",
          "size": 4744,
          "sha512": "585ea6edcf398cbf3832783709299c8dd7b2a152abc2ea1189a0b3ddf6b75df972eea4eb7c14450bbbf8de74357018a780f2e83470c93a921bfac653e0a8f972",
          "sha256": "b8d0705494a8cb47af2185364d6312db594c4ea3d4f83107de9923a77f716b0c",
          "sha1": "25742c8adb2548cd8b31de3298ab74e94f904a77",
          "md5": "deff2d3330129f2c734ce3363b1d446d"
        }
      ]
    }
  ]
}
