{
  "formatVersion": "1.1",
  "component": {
    "group": "io.micronaut.micrometer",
    "module": "micronaut-micrometer-bom",
    "version": "4.8.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.micrometer",
          "module": "micrometer-bom",
          "version": {
            "requires": "1.10.5"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "dependencyConstraints": [
        {
          "group": "io.dropwizard.metrics",
          "module": "metrics-core",
          "version": {
            "requires": "4.2.18"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-core",
          "version": {
            "requires": "1.10.5"
          }
        },
        {
          "group": "com.newrelic.telemetry",
          "module": "micrometer-registry-new-relic",
          "version": {
            "requires": "0.10.0"
          }
        },
        {
          "group": "io.micronaut.micrometer",
          "module": "micronaut-micrometer-annotation",
          "version": {
            "requires": "4.8.3"
          }
        },
        {
          "group": "io.micronaut.micrometer",
          "module": "micronaut-micrometer-core",
          "version": {
            "requires": "4.8.3"
          }
        },
        {
          "group": "io.micronaut.micrometer",
          "module": "micronaut-micrometer-registry-appoptics",
          "version": {
            "requires": "4.8.3"
          }
        },
        {
          "group": "io.micronaut.micrometer",
          "module": "micronaut-micrometer-registry-atlas",
          "version": {
            "requires": "4.8.3"
          }
        },
        {
          "group": "io.micronaut.micrometer",
          "module": "micronaut-micrometer-registry-azure-monitor",
          "version": {
            "requires": "4.8.3"
          }
        },
        {
          "group": "io.micronaut.micrometer",
          "module": "micronaut-micrometer-registry-cloudwatch",
          "version": {
            "requires": "4.8.3"
          }
        },
        {
          "group": "io.micronaut.micrometer",
          "module": "micronaut-micrometer-registry-datadog",
          "version": {
            "requires": "4.8.3"
          }
        },
        {
          "group": "io.micronaut.micrometer",
          "module": "micronaut-micrometer-registry-dynatrace",
          "version": {
            "requires": "4.8.3"
          }
        },
        {
          "group": "io.micronaut.micrometer",
          "module": "micronaut-micrometer-registry-elastic",
          "version": {
            "requires": "4.8.3"
          }
        },
        {
          "group": "io.micronaut.micrometer",
          "module": "micronaut-micrometer-registry-ganglia",
          "version": {
            "requires": "4.8.3"
          }
        },
        {
          "group": "io.micronaut.micrometer",
          "module": "micronaut-micrometer-registry-graphite",
          "version": {
            "requires": "4.8.3"
          }
        },
        {
          "group": "io.micronaut.micrometer",
          "module": "micronaut-micrometer-registry-humio",
          "version": {
            "requires": "4.8.3"
          }
        },
        {
          "group": "io.micronaut.micrometer",
          "module": "micronaut-micrometer-registry-influx",
          "version": {
            "requires": "4.8.3"
          }
        },
        {
          "group": "io.micronaut.micrometer",
          "module": "micronaut-micrometer-registry-jmx",
          "version": {
            "requires": "4.8.3"
          }
        },
        {
          "group": "io.micronaut.micrometer",
          "module": "micronaut-micrometer-registry-kairos",
          "version": {
            "requires": "4.8.3"
          }
        },
        {
          "group": "io.micronaut.micrometer",
          "module": "micronaut-micrometer-registry-new-relic",
          "version": {
            "requires": "4.8.3"
          }
        },
        {
          "group": "io.micronaut.micrometer",
          "module": "micronaut-micrometer-registry-new-relic-telemetry",
          "version": {
            "requires": "4.8.3"
          }
        },
        {
          "group": "io.micronaut.micrometer",
          "module": "micronaut-micrometer-registry-prometheus",
          "version": {
            "requires": "4.8.3"
          }
        },
        {
          "group": "io.micronaut.micrometer",
          "module": "micronaut-micrometer-registry-signalfx",
          "version": {
            "requires": "4.8.3"
          }
        },
        {
          "group": "io.micronaut.micrometer",
          "module": "micronaut-micrometer-registry-stackdriver",
          "version": {
            "requires": "4.8.3"
          }
        },
        {
          "group": "io.micronaut.micrometer",
          "module": "micronaut-micrometer-registry-statsd",
          "version": {
            "requires": "4.8.3"
          }
        },
        {
          "group": "io.micronaut.micrometer",
          "module": "micronaut-micrometer-registry-wavefront",
          "version": {
            "requires": "4.8.3"
          }
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.micrometer",
          "module": "micrometer-bom",
          "version": {
            "requires": "1.10.5"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "dependencyConstraints": [
        {
          "group": "io.dropwizard.metrics",
          "module": "metrics-core",
          "version": {
            "requires": "4.2.18"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-core",
          "version": {
            "requires": "1.10.5"
          }
        },
        {
          "group": "com.newrelic.telemetry",
          "module": "micrometer-registry-new-relic",
          "version": {
            "requires": "0.10.0"
          }
        },
        {
          "group": "io.micronaut.micrometer",
          "module": "micronaut-micrometer-annotation",
          "version": {
            "requires": "4.8.3"
          }
        },
        {
          "group": "io.micronaut.micrometer",
          "module": "micronaut-micrometer-core",
          "version": {
            "requires": "4.8.3"
          }
        },
        {
          "group": "io.micronaut.micrometer",
          "module": "micronaut-micrometer-registry-appoptics",
          "version": {
            "requires": "4.8.3"
          }
        },
        {
          "group": "io.micronaut.micrometer",
          "module": "micronaut-micrometer-registry-atlas",
          "version": {
            "requires": "4.8.3"
          }
        },
        {
          "group": "io.micronaut.micrometer",
          "module": "micronaut-micrometer-registry-azure-monitor",
          "version": {
            "requires": "4.8.3"
          }
        },
        {
          "group": "io.micronaut.micrometer",
          "module": "micronaut-micrometer-registry-cloudwatch",
          "version": {
            "requires": "4.8.3"
          }
        },
        {
          "group": "io.micronaut.micrometer",
          "module": "micronaut-micrometer-registry-datadog",
          "version": {
            "requires": "4.8.3"
          }
        },
        {
          "group": "io.micronaut.micrometer",
          "module": "micronaut-micrometer-registry-dynatrace",
          "version": {
            "requires": "4.8.3"
          }
        },
        {
          "group": "io.micronaut.micrometer",
          "module": "micronaut-micrometer-registry-elastic",
          "version": {
            "requires": "4.8.3"
          }
        },
        {
          "group": "io.micronaut.micrometer",
          "module": "micronaut-micrometer-registry-ganglia",
          "version": {
            "requires": "4.8.3"
          }
        },
        {
          "group": "io.micronaut.micrometer",
          "module": "micronaut-micrometer-registry-graphite",
          "version": {
            "requires": "4.8.3"
          }
        },
        {
          "group": "io.micronaut.micrometer",
          "module": "micronaut-micrometer-registry-humio",
          "version": {
            "requires": "4.8.3"
          }
        },
        {
          "group": "io.micronaut.micrometer",
          "module": "micronaut-micrometer-registry-influx",
          "version": {
            "requires": "4.8.3"
          }
        },
        {
          "group": "io.micronaut.micrometer",
          "module": "micronaut-micrometer-registry-jmx",
          "version": {
            "requires": "4.8.3"
          }
        },
        {
          "group": "io.micronaut.micrometer",
          "module": "micronaut-micrometer-registry-kairos",
          "version": {
            "requires": "4.8.3"
          }
        },
        {
          "group": "io.micronaut.micrometer",
          "module": "micronaut-micrometer-registry-new-relic",
          "version": {
            "requires": "4.8.3"
          }
        },
        {
          "group": "io.micronaut.micrometer",
          "module": "micronaut-micrometer-registry-new-relic-telemetry",
          "version": {
            "requires": "4.8.3"
          }
        },
        {
          "group": "io.micronaut.micrometer",
          "module": "micronaut-micrometer-registry-prometheus",
          "version": {
            "requires": "4.8.3"
          }
        },
        {
          "group": "io.micronaut.micrometer",
          "module": "micronaut-micrometer-registry-signalfx",
          "version": {
            "requires": "4.8.3"
          }
        },
        {
          "group": "io.micronaut.micrometer",
          "module": "micronaut-micrometer-registry-stackdriver",
          "version": {
            "requires": "4.8.3"
          }
        },
        {
          "group": "io.micronaut.micrometer",
          "module": "micronaut-micrometer-registry-statsd",
          "version": {
            "requires": "4.8.3"
          }
        },
        {
          "group": "io.micronaut.micrometer",
          "module": "micronaut-micrometer-registry-wavefront",
          "version": {
            "requires": "4.8.3"
          }
        }
      ]
    },
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "micronaut-micrometer-bom-4.8.3.toml",
          "url": "micronaut-micrometer-bom-4.8.3.toml",
          "size": 4350,
          "sha512": "b4784899afa111b3ee01a933c9161d99f84e7f98faeee5bb902929918c0db7ae4a69330c802800034d87c7e3d3bddaf85a6549c75aec0f23951b2e29bef0d32b",
          "sha256": "0a5ef09caf62f904642dc22b724aec73f0d8338252ba6ea6c30d02ca3ae57864",
          "sha1": "a88c92ffe3605fd283c50eedd235f1d51d32a912",
          "md5": "5cb7cbd7e6c085e43b34d39a85579f5b"
        }
      ]
    }
  ]
}
