{
  "formatVersion": "1.1",
  "component": {
    "group": "io.micronaut.kafka",
    "module": "micronaut-kafka-bom",
    "version": "4.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "java-api"
      },
      "dependencyConstraints": [
        {
          "group": "org.apache.kafka",
          "module": "kafka-clients",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "org.apache.kafka",
          "module": "kafka-streams",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "io.micronaut.kafka",
          "module": "micronaut-kafka",
          "version": {
            "requires": "4.5.0"
          }
        },
        {
          "group": "io.micronaut.kafka",
          "module": "micronaut-kafka-streams",
          "version": {
            "requires": "4.5.0"
          }
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "org.apache.kafka",
          "module": "kafka-clients",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "org.apache.kafka",
          "module": "kafka-streams",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "io.micronaut.kafka",
          "module": "micronaut-kafka",
          "version": {
            "requires": "4.5.0"
          }
        },
        {
          "group": "io.micronaut.kafka",
          "module": "micronaut-kafka-streams",
          "version": {
            "requires": "4.5.0"
          }
        }
      ]
    },
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "micronaut-kafka-bom-4.5.0.toml",
          "url": "micronaut-kafka-bom-4.5.0.toml",
          "size": 840,
          "sha512": "ae562097997b01ff54e60d6c2262b1082a3c846ab94ce7cf34654fcb3aa63486be115ccb314629334eaaa632b92352f2dbc5cf8d72f4b3d3a0fe03abbf791145",
          "sha256": "5b3317917c3029649846857ddc448fe6d5f80be6cd0f3ed2131c5160ba55e18f",
          "sha1": "6e337c75803d86d3586db9b1dfad916dc1cc69e7",
          "md5": "3b9af55df9691464e4ba8efa405dd495"
        }
      ]
    }
  ]
}
