{
  "formatVersion": "1.1",
  "component": {
    "group": "org.checkerframework",
    "module": "checker-qual",
    "version": "3.19.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3-rc-1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "checker-qual-3.19.0.jar",
          "url": "checker-qual-3.19.0.jar",
          "size": 222143,
          "sha512": "2406c3188c5d7eed0530adddd6c8782686ecae665e27e8cd5cb84c8da88532eedad4d93fadafdf98fc37ba6f5114669ee458e62682a1eab7c2c8570f41fdcc12",
          "sha256": "a827c49183f3a632277d27a0a4673686cb341507447b9d570261094bd748aa68",
          "sha1": "838b42bb6f7f73315167b359d24649845cef1c48",
          "md5": "a70912824bb142a53d6cb50a349dab1a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "checker-qual-3.19.0.jar",
          "url": "checker-qual-3.19.0.jar",
          "size": 222143,
          "sha512": "2406c3188c5d7eed0530adddd6c8782686ecae665e27e8cd5cb84c8da88532eedad4d93fadafdf98fc37ba6f5114669ee458e62682a1eab7c2c8570f41fdcc12",
          "sha256": "a827c49183f3a632277d27a0a4673686cb341507447b9d570261094bd748aa68",
          "sha1": "838b42bb6f7f73315167b359d24649845cef1c48",
          "md5": "a70912824bb142a53d6cb50a349dab1a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "checker-qual-3.19.0-javadoc.jar",
          "url": "checker-qual-3.19.0-javadoc.jar",
          "size": 957747,
          "sha512": "bc70c834215d95e6f55eb63233d427e00824529657306040a6121927b0e669ee3fcdb39236401fdb83511d2154fc07b1ee17b86ee25c7ef5777da568978c8229",
          "sha256": "79ff5d921f641d0a79d40d34a899af579f9e8401e46caf31872066a76f1a192e",
          "sha1": "6b6f45e333efdc088c6a5c751cf6c96c988f0b86",
          "md5": "85bc418cc45d89af68d37abf0c6bd4f2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "checker-qual-3.19.0-sources.jar",
          "url": "checker-qual-3.19.0-sources.jar",
          "size": 252163,
          "sha512": "8b3e396f56955a8b740e25efe0efb57104e7d204899fc27c822844d59a5e6ffe6ef19394e87d2f45a760524ddee91fc1e831562aafa730616a6413a9a5379527",
          "sha256": "1f226e2901162475caa0151530496dd010701abd41497ebcf6a77b557bdc363b",
          "sha1": "5b703df399e82ae3efcf57b50c2304598abbc40f",
          "md5": "1f0048c112036a477793f48a21d802e3"
        }
      ]
    }
  ]
}
