{
  "formatVersion": "1.1",
  "component": {
    "group": "io.micronaut.views",
    "module": "micronaut-views-bom",
    "version": "3.8.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "java-api"
      },
      "dependencyConstraints": [
        {
          "group": "org.freemarker",
          "module": "freemarker",
          "version": {
            "requires": "2.3.31"
          }
        },
        {
          "group": "com.github.jknack",
          "module": "handlebars",
          "version": {
            "requires": "4.3.1"
          }
        },
        {
          "group": "gg.jte",
          "module": "jte",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "gg.jte",
          "module": "jte-kotlin",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "com.fizzed",
          "module": "rocker-runtime",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.google.template",
          "module": "soy",
          "version": {
            "requires": "2022-03-02"
          }
        },
        {
          "group": "org.thymeleaf",
          "module": "thymeleaf",
          "version": {
            "requires": "3.1.1.RELEASE"
          }
        },
        {
          "group": "org.apache.velocity",
          "module": "velocity-engine-core",
          "version": {
            "requires": "2.3"
          }
        },
        {
          "group": "io.micronaut.views",
          "module": "micronaut-views-core",
          "version": {
            "requires": "3.8.2"
          }
        },
        {
          "group": "io.micronaut.views",
          "module": "micronaut-views-freemarker",
          "version": {
            "requires": "3.8.2"
          }
        },
        {
          "group": "io.micronaut.views",
          "module": "micronaut-views-handlebars",
          "version": {
            "requires": "3.8.2"
          }
        },
        {
          "group": "io.micronaut.views",
          "module": "micronaut-views-jte",
          "version": {
            "requires": "3.8.2"
          }
        },
        {
          "group": "io.micronaut.views",
          "module": "micronaut-views-pebble",
          "version": {
            "requires": "3.8.2"
          }
        },
        {
          "group": "io.micronaut.views",
          "module": "micronaut-views-rocker",
          "version": {
            "requires": "3.8.2"
          }
        },
        {
          "group": "io.micronaut.views",
          "module": "micronaut-views-soy",
          "version": {
            "requires": "3.8.2"
          }
        },
        {
          "group": "io.micronaut.views",
          "module": "micronaut-views-thymeleaf",
          "version": {
            "requires": "3.8.2"
          }
        },
        {
          "group": "io.micronaut.views",
          "module": "micronaut-views-velocity",
          "version": {
            "requires": "3.8.2"
          }
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "org.freemarker",
          "module": "freemarker",
          "version": {
            "requires": "2.3.31"
          }
        },
        {
          "group": "com.github.jknack",
          "module": "handlebars",
          "version": {
            "requires": "4.3.1"
          }
        },
        {
          "group": "gg.jte",
          "module": "jte",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "gg.jte",
          "module": "jte-kotlin",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "com.fizzed",
          "module": "rocker-runtime",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.google.template",
          "module": "soy",
          "version": {
            "requires": "2022-03-02"
          }
        },
        {
          "group": "org.thymeleaf",
          "module": "thymeleaf",
          "version": {
            "requires": "3.1.1.RELEASE"
          }
        },
        {
          "group": "org.apache.velocity",
          "module": "velocity-engine-core",
          "version": {
            "requires": "2.3"
          }
        },
        {
          "group": "io.micronaut.views",
          "module": "micronaut-views-core",
          "version": {
            "requires": "3.8.2"
          }
        },
        {
          "group": "io.micronaut.views",
          "module": "micronaut-views-freemarker",
          "version": {
            "requires": "3.8.2"
          }
        },
        {
          "group": "io.micronaut.views",
          "module": "micronaut-views-handlebars",
          "version": {
            "requires": "3.8.2"
          }
        },
        {
          "group": "io.micronaut.views",
          "module": "micronaut-views-jte",
          "version": {
            "requires": "3.8.2"
          }
        },
        {
          "group": "io.micronaut.views",
          "module": "micronaut-views-pebble",
          "version": {
            "requires": "3.8.2"
          }
        },
        {
          "group": "io.micronaut.views",
          "module": "micronaut-views-rocker",
          "version": {
            "requires": "3.8.2"
          }
        },
        {
          "group": "io.micronaut.views",
          "module": "micronaut-views-soy",
          "version": {
            "requires": "3.8.2"
          }
        },
        {
          "group": "io.micronaut.views",
          "module": "micronaut-views-thymeleaf",
          "version": {
            "requires": "3.8.2"
          }
        },
        {
          "group": "io.micronaut.views",
          "module": "micronaut-views-velocity",
          "version": {
            "requires": "3.8.2"
          }
        }
      ]
    },
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "micronaut-views-bom-3.8.2.toml",
          "url": "micronaut-views-bom-3.8.2.toml",
          "size": 2226,
          "sha512": "ecc8e95a8afa4e60229dcdf02362728df459556e25c4d631b2e4d9472f756add792ce78d31c40bf48fb466f38a27ddc60db18740a153ae673768dacb8e713a56",
          "sha256": "7e0df6b67e7418eee52fa13152129a7e8f380704f1d5f34235629572e6e2685c",
          "sha1": "7f05a46a268d575467aff16434c6b36497b8a18a",
          "md5": "cd9c2f8bdbefebdb50674beac4fe2952"
        }
      ]
    }
  ]
}
