{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-test",
    "version": "5.3.32",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.32"
          },
          "excludes": [
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            },
            {
              "group": "xmlpull",
              "module": "xmlpull"
            },
            {
              "group": "org.slf4j",
              "module": "jcl-over-slf4j"
            },
            {
              "group": "org.hamcrest",
              "module": "hamcrest-core"
            },
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-test-5.3.32.jar",
          "url": "spring-test-5.3.32.jar",
          "size": 792435,
          "sha512": "873ab3402b00ee569e5dc20ad35d7f7d166a26e9ccee5e214597ce1a13da53cd71f541428e49a0e1d846d950be10e9c45d05dbbc526f362bf1d78a3d62e0a999",
          "sha256": "8f8687215b90ff6f024f223dc18587db673a29e9e4d39c6f1965b220cdf258ff",
          "sha1": "ef4de37832a8fce1264ac0ebed6cbec2690e48d4",
          "md5": "095a9654f3ba80383f98abfdb2b47725"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.32"
          },
          "excludes": [
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            },
            {
              "group": "xmlpull",
              "module": "xmlpull"
            },
            {
              "group": "org.slf4j",
              "module": "jcl-over-slf4j"
            },
            {
              "group": "org.hamcrest",
              "module": "hamcrest-core"
            },
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-test-5.3.32.jar",
          "url": "spring-test-5.3.32.jar",
          "size": 792435,
          "sha512": "873ab3402b00ee569e5dc20ad35d7f7d166a26e9ccee5e214597ce1a13da53cd71f541428e49a0e1d846d950be10e9c45d05dbbc526f362bf1d78a3d62e0a999",
          "sha256": "8f8687215b90ff6f024f223dc18587db673a29e9e4d39c6f1965b220cdf258ff",
          "sha1": "ef4de37832a8fce1264ac0ebed6cbec2690e48d4",
          "md5": "095a9654f3ba80383f98abfdb2b47725"
        }
      ]
    }
  ]
}
