{
  "formatVersion": "1.1",
  "component": {
    "group": "org.grails",
    "module": "grails-gradle-plugin",
    "version": "6.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "grails-gradle-plugin-6.1.2.jar",
          "url": "grails-gradle-plugin-6.1.2.jar",
          "size": 384274,
          "sha512": "01057fafba9eeab905942f55bd87312d856c36d63ec31da4801cb7d24ca9db75a8fae20edacc96ec8e6d1b9b99993efa63c66afe2a9c43a496e18b37a374a97e",
          "sha256": "4cc8c601ca34cb9ab56f031cb5ea65f2892f31903b50e2f770db2ca7d16abec2",
          "sha1": "1caef8ae4b67be86870179099f693580c0244ca9",
          "md5": "d61d351b1fd73db0ceb2398669724d60"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.gradle-nexus",
          "module": "publish-plugin",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.bmuschko",
          "module": "gradle-nexus-plugin",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "org.grails",
          "module": "grails-bootstrap",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "org.grails",
          "module": "grails-gradle-model",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "org.grails",
          "module": "grails-shell",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-gradle-plugin",
          "version": {
            "requires": "2.7.18"
          }
        },
        {
          "group": "io.spring.gradle",
          "module": "dependency-management-plugin",
          "version": {
            "requires": "1.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "grails-gradle-plugin-6.1.2.jar",
          "url": "grails-gradle-plugin-6.1.2.jar",
          "size": 384274,
          "sha512": "01057fafba9eeab905942f55bd87312d856c36d63ec31da4801cb7d24ca9db75a8fae20edacc96ec8e6d1b9b99993efa63c66afe2a9c43a496e18b37a374a97e",
          "sha256": "4cc8c601ca34cb9ab56f031cb5ea65f2892f31903b50e2f770db2ca7d16abec2",
          "sha1": "1caef8ae4b67be86870179099f693580c0244ca9",
          "md5": "d61d351b1fd73db0ceb2398669724d60"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "grails-gradle-plugin-6.1.2-javadoc.jar",
          "url": "grails-gradle-plugin-6.1.2-javadoc.jar",
          "size": 261,
          "sha512": "9f19956d0b66eea301d6f9fcb2bc701746ade0e820db115ccd90a7f2f77b47aa6d529c2eafda31162107cb2b3325c5b5561799630a388c759de04db20ddfd76d",
          "sha256": "ee54dee72ac2e8871bc2da96b846c4d200d13b7c6e6a1d3ba5b1d3b612ebe878",
          "sha1": "731a6201a6f96c83060d34ca3887c8e600c25ff6",
          "md5": "f39ab3fa74986539a35206a748dcbae7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "grails-gradle-plugin-6.1.2-sources.jar",
          "url": "grails-gradle-plugin-6.1.2-sources.jar",
          "size": 46254,
          "sha512": "99982f563660d401d39808bbe1f835b24e23a0e607800147aa51b53c3f984e6e7cb0e7bcaa344420ce2162b6dfde341d2853754d9cf8c86ec668fc7a089633cb",
          "sha256": "9d7ea7bb39f917c3ef7559253b087b562f2889c9feff30420111b0b1c6242214",
          "sha1": "7b9037d49034238d10c89a32b76c2890fe0f9921",
          "md5": "b40eccffca8a547a0e7371f1f7e41c81"
        }
      ]
    }
  ]
}
