{
  "formatVersion": "1.1",
  "component": {
    "group": "org.grails",
    "module": "grails-plugin-services",
    "version": "6.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "javax.servlet",
          "module": "javax.servlet-api",
          "version": {
            "requires": "4.0.1"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-test",
          "version": {
            "requires": "5.3.31"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy",
          "version": {
            "requires": "3.0.11"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            },
            {
              "group": "*",
              "module": "commons-cli"
            },
            {
              "group": "*",
              "module": "ant"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "jcl-over-slf4j",
          "version": {
            "requires": "1.7.36"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-tx",
          "version": {
            "requires": "5.3.31"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-core",
          "version": {
            "requires": "6.1.2"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-plugin-datasource",
          "version": {
            "requires": "6.1.2"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "grails-plugin-services-6.1.2.jar",
          "url": "grails-plugin-services-6.1.2.jar",
          "size": 17680,
          "sha512": "5f3c0142af39a6b46cd8b03d004ab27e14fb68640dfdedf532af91a6a4eda1f69fe5c275212efc3eeed9cae833760fcfe08336982fe3062237cc627de62d03e6",
          "sha256": "feaf70ba8cc8fe01a957c12a43d0d3f45580c49a0d8c8e5640cafd5b0c796e59",
          "sha1": "32cb817cef5260e36dc2b74d82cfefc2afb79690",
          "md5": "2f18545f64b9543a28e6b8017b2fe6a8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "javax.servlet",
          "module": "javax.servlet-api",
          "version": {
            "requires": "4.0.1"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-test",
          "version": {
            "requires": "5.3.31"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy",
          "version": {
            "requires": "3.0.11"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            },
            {
              "group": "*",
              "module": "commons-cli"
            },
            {
              "group": "*",
              "module": "ant"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "jcl-over-slf4j",
          "version": {
            "requires": "1.7.36"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-tx",
          "version": {
            "requires": "5.3.31"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-core",
          "version": {
            "requires": "6.1.2"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.grails",
          "module": "grails-plugin-datasource",
          "version": {
            "requires": "6.1.2"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "grails-plugin-services-6.1.2.jar",
          "url": "grails-plugin-services-6.1.2.jar",
          "size": 17680,
          "sha512": "5f3c0142af39a6b46cd8b03d004ab27e14fb68640dfdedf532af91a6a4eda1f69fe5c275212efc3eeed9cae833760fcfe08336982fe3062237cc627de62d03e6",
          "sha256": "feaf70ba8cc8fe01a957c12a43d0d3f45580c49a0d8c8e5640cafd5b0c796e59",
          "sha1": "32cb817cef5260e36dc2b74d82cfefc2afb79690",
          "md5": "2f18545f64b9543a28e6b8017b2fe6a8"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "grails-plugin-services-6.1.2-javadoc.jar",
          "url": "grails-plugin-services-6.1.2-javadoc.jar",
          "size": 261,
          "sha512": "40bc6cb65cf20e594cb1ec0705e91dd91c58a431b74d1e0755985a0b4fafb7e655a003d50b955c4958b98ca1152f5f04cfc33cbbf70918d7c8ddabc1d1dd0a3d",
          "sha256": "65d3ed36721ac7876e6777dadf4fcdd29f629560f656ad5301e18303d43ca1dc",
          "sha1": "1da147f2c7831faf8f2b3f9667891a2c0412a2b6",
          "md5": "e92aacb8da54f2617ae790c1ecaeed51"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "grails-plugin-services-6.1.2-sources.jar",
          "url": "grails-plugin-services-6.1.2-sources.jar",
          "size": 4280,
          "sha512": "e8a688c62ad449a11c0d0a81caab53d91a09860d2b3a07866d7cec01f117e79f816d99ebb5d8b7a3d3ca16b0c05b7ebadb171ef93fac809624e265fcbeb7d6b1",
          "sha256": "d8d66f74685cafa782c4f59c0c4e984e816079c78ad8f36798af42783b9f8c41",
          "sha1": "6c7585a8f493b637c2c955891047c4fe90405b16",
          "md5": "9071ace17843f4492660367754cdd125"
        }
      ]
    }
  ]
}
