{
  "formatVersion": "1.1",
  "component": {
    "group": "org.grails",
    "module": "grails-datastore-gorm",
    "version": "8.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy",
          "version": {
            "requires": "3.0.11"
          }
        },
        {
          "group": "org.grails",
          "module": "grails-datastore-core",
          "version": {
            "requires": "8.0.4"
          }
        },
        {
          "group": "org.grails",
          "module": "grails-datastore-gorm-validation",
          "version": {
            "requires": "8.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "grails-datastore-gorm-8.0.4.jar",
          "url": "grails-datastore-gorm-8.0.4.jar",
          "size": 955422,
          "sha512": "4b2084f1138823807a78bccf9053ae3db4e8f74005fcdcbf70e898efb4dd0d76c4bb36bd192c9fb8f84c7ccc3feb2eb44f650ddf9cf0e95d3e031f3a4ed85b9a",
          "sha256": "118dd817e2ddaaaee94d6a6fcf43d8d1e22d6cdbb54d6c7ee04c8dd8aaa15bcf",
          "sha1": "d030b0979bab4500bb3f4230a3386cc29c37df39",
          "md5": "6253258e74d0adacce0129eeab7fd150"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "javax.el",
          "module": "javax.el-api",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy",
          "version": {
            "requires": "3.0.11"
          }
        },
        {
          "group": "org.grails",
          "module": "grails-datastore-core",
          "version": {
            "requires": "8.0.4"
          }
        },
        {
          "group": "org.grails",
          "module": "grails-datastore-gorm-validation",
          "version": {
            "requires": "8.0.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.el",
          "version": {
            "requires": "3.0.1-b12"
          }
        }
      ],
      "files": [
        {
          "name": "grails-datastore-gorm-8.0.4.jar",
          "url": "grails-datastore-gorm-8.0.4.jar",
          "size": 955422,
          "sha512": "4b2084f1138823807a78bccf9053ae3db4e8f74005fcdcbf70e898efb4dd0d76c4bb36bd192c9fb8f84c7ccc3feb2eb44f650ddf9cf0e95d3e031f3a4ed85b9a",
          "sha256": "118dd817e2ddaaaee94d6a6fcf43d8d1e22d6cdbb54d6c7ee04c8dd8aaa15bcf",
          "sha1": "d030b0979bab4500bb3f4230a3386cc29c37df39",
          "md5": "6253258e74d0adacce0129eeab7fd150"
        }
      ]
    }
  ]
}
