{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fasterxml.jackson.core",
    "module": "jackson-annotations",
    "version": "2.15.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "maven": {
      "version": "3.8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.15.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-annotations-2.15.0.jar",
          "url": "jackson-annotations-2.15.0.jar",
          "size": 75564,
          "sha512": "a35abe45ffd708ec5f312e293026f564b405ea82ba7e999783c65e9172095761ba52229949572bb8ee10a264050f486d0ef334a9eab2c77be359fcb1788f393f",
          "sha256": "91adcd3dcf5fd9a16499934e7536a23d456692a0093e3d4fd52f138c3936348c",
          "sha1": "89b0fd554928425a776a6e97ed010034312af21d",
          "md5": "cb0a97fc66b8cfa001aee80d51dc6722"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.15.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-annotations-2.15.0.jar",
          "url": "jackson-annotations-2.15.0.jar",
          "size": 75564,
          "sha512": "a35abe45ffd708ec5f312e293026f564b405ea82ba7e999783c65e9172095761ba52229949572bb8ee10a264050f486d0ef334a9eab2c77be359fcb1788f393f",
          "sha256": "91adcd3dcf5fd9a16499934e7536a23d456692a0093e3d4fd52f138c3936348c",
          "sha1": "89b0fd554928425a776a6e97ed010034312af21d",
          "md5": "cb0a97fc66b8cfa001aee80d51dc6722"
        }
      ]
    }
  ]
}
